### ISSUE TITLE
Improve Wallet unlock and create...

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#102]
This should be event based not layout based.  For example:

``` javascript
 _buyClick(params...) {
    setState({show_wallet: <Wallet onUnlock={this._buy.bind(this, params)}/>})
} 
render() {
    return {this.state.show_wallet}
}
```

**Comment by jcalfee** [comment]
usage: https://github.com/cryptonomex/graphene-ui/commit/806e3c72cfb59c33ff6f048ef4e5edf9164855cc

**Comment by jcalfee** [comment]
related: https://github.com/cryptonomex/graphene-ui/issues/107

**Comment by jcalfee** [comment]
Alternative design... Two cases now:
- Login only site (no browsing)
- View everything but login where necessary

Both cases use the modal so it should preserve the original URL request used to enter the application.

Case 1 site-wide lock:
App.jsx 

``` javascript
componentDidMount() {
    WalletActions.created_and_unlocked( unlocked => {
        this.setState({site_unlocked: true})
    }, locked => {
        this.setState({site_unlocked: false})
    })
}
```

Case 2, unlock on when needed:
Transfer.jsx

``` javascript
onConfirm() {
    WalletActions.created_and_unlocked( success => {
        AccountActions.transfer(....
    }, optional_error => {
        notify.error("Transfer canceled")
    })
}
```

In both cases the a `<WalletModal ...` component will appear in App.jsx's render method (just like `<AccountNotifications/>`) and hook in by `ref` in the same way.

Both cases may be added to the code but the open access site behaviour could be controlled with a boolean in app/config.js.

**Comment by svk31** [comment]
I prefer case 2 but with a twist: 

If the wallet is locked, hide certain parts of the app like the "BuySell" and "MyOpenOrders" components of the exchange, and let the user manually trigger a login if they want to access those parts of the app.

Login should be avaiable in the top right as per most sites.

**Comment by valzav** [comment]
I would prefer case 2 as well but for a different reason and I have user friendly solution for entering password to unlock wallet.
The reason: unlock is needed only when user makes transaction, this is not frequent use case, so let user to use the wallet without unlocking until it's really needed, also if lock wallet by timeout, user won't be bothered with popup until making transaction.
Solution - let users to unlock wallet using transaction confirmation dialog. We just need to add password field to it if wallet is locked.
What do you think? Let's discuss this in Slack.

**Comment by jcalfee** [comment]
Create wallet is unchanged.. Lock and Unlock happen as actions now..  Most cases are captured by the transaction send.
