### ISSUE TITLE
Unexpected Password Prompt when clicking on Assets tab on account page

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#107]
![image](https://cloud.githubusercontent.com/assets/347290/8957941/e4e63c52-35cf-11e5-9c15-c11a4849a31e.png)

**Comment by bytemaster** [comment]
![image](https://cloud.githubusercontent.com/assets/347290/8958023/66363b2c-35d0-11e5-9dab-f396c456ecd0.png)

It also prompted me for a password when I clicked to the transfer tab.   

Is this because my login expired?     
1. There should be a setting on the settings page that allows me to control my logout period.
2. There should be a button in the top left that allows me to "lock" or "unlock" the wallet at will.

**Comment by jcalfee** [comment]
Did your url change?  The wallet will stay open until you close or refresh the page.  

No expiration yet, I'll put your list into a new ticket.

**Comment by jcalfee** [comment]
This happened because the wallet was locked.  This will be improved so it will only prompt you when you go to create the asset: https://github.com/cryptonomex/graphene-ui/issues/102
