### ISSUE TITLE
Create Asset Link is Broken 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#110]
![image](https://cloud.githubusercontent.com/assets/347290/8958473/01bfadba-35d3-11e5-9ed7-1bd4fc105bde.png)

Entire wallet disappears and the webpage displays:

Cannot GET /true 
![image](https://cloud.githubusercontent.com/assets/347290/8958463/f849100a-35d2-11e5-99e0-4598fc0a17f3.png)

**Comment by jcalfee** [comment]
duplicate: https://github.com/cryptonomex/graphene-ui/issues/100

**Comment by bytemaster** [comment]
A duplicate of itself??
