### ISSUE TITLE
Error Importing Existing Accounts from File

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#112]
![image](https://cloud.githubusercontent.com/assets/347290/8958857/7330d382-35d5-11e5-9001-c5597bc25340.png)

**Comment by jcalfee** [comment]
This is an old wallet..  A new required date was added.. I have not been making them backwards compatible ..

In Chrome under Settings... search on "local" .. Chrome will give you tooltips on where to click.  The 1st click is under Content Settings .. when you get into cookies and data you can search on "local" again and click X next to the size of the local storage for "localhost"

jcalfee [8:44 AM]
That will immediately clear it .. you can refresh the wallet page..
