### ISSUE TITLE
First Open of New Wallet should 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#114]
I am presented with an empty dashboard, but instead what should happen is:

![image](https://cloud.githubusercontent.com/assets/347290/8959628/e9c0968c-35d9-11e5-8f00-5f7229b91d29.png)

If this is a hosted wallet provider, then `CREATE` should take the use directly to their registered account.

If this is a wallet is not connected to a service provider then it should link to a faucet page to register the account which should then REDIRECT the user back to their wallet after registration is complete.

**Comment by bytemaster** [comment]
The user interface should be designed for mobile.

There needs to be a link to the settings page so that the user can change the language and/or the API SERVER url.  But the user should not be allowed to do anything other than SAVE and return back to the welcome screen.   

The welcome screen should not enable the IMPORT or CREATE buttons if no connection to the API server can be found.

**Comment by bytemaster** [comment]
![image](https://cloud.githubusercontent.com/assets/347290/8960074/3d6577ce-35dc-11e5-86ac-1ac201d98d15.png)

Existing create wallet page has scroll bar to the right of the create button which makes it possible to lose information.    Also, the text fields should not expand beyond a reasonable width.

**Comment by svk31** [comment]
I'll create the landing page template at least, will flesh out as possible when we start hooking up faucets or wallet providers

**Comment by valzav** [comment]
@svk31 this page already exists (CreateAccount.jsx), this is how I planned it. https://app.uxpin.com/dms/Desktop/Default/2703835#?id_page=25125726
I'll make necessary changes

**Comment by svk31** [comment]
The transition to this screen only happens on the initial load, if the user navigates elsewhere he's still presented with an empty screen..

**Comment by valzav** [comment]
@svk31 yes, this is the idea - force users to create wallet and account right after application loads for the first time. I'll remove top navigation from this page later so users wouldn't be able to navigate elsewhere.

**Comment by valzav** [comment]
Based on our today's discussion, this behaviour will be changed after testnet release - users would be allowed to browse without registering (creating wallet with password) and asked to create wallet and account only when they perform some action that requires a private key.
