### ISSUE TITLE
Add Websocket API URL under settings 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#115]
The wallet should not hard-code the API url, especially because it may be provided by a separate domain.

**Comment by jcalfee** [comment]
I suggest this as well:
`echo 'module.exports = { wss_url="wss://xxxxx/web_socket" } > rpc_api/config.js`

We know our business partners are going to fork and change this.  They can change this in their fork and it will remain anytime they want to merge.

**Comment by jcalfee** [comment]
When a web-socket changes I believe the only safe practical thing to do is to reset the chain-store’s cache and close the current wallet.  For an operation like that I would like to see a "Save" or "Change" button press to confirm the new web socket URL.

I can help, but I believe I should probably add a WIF view/export feature first.  What do you think?

**Comment by valzav** [comment]
I think the easiest way to handle this is to refresh the page, what do you think - should I add a button for this?

**Comment by jcalfee** [comment]
If you will call reset on the chain store and close wallet we will not put stress on mobile phones or slow bandwidth connections.  If you have any hiccups at all I can fix it very easy so don't spend any of your time on that.

**Comment by jcalfee** [comment]
Also, a basic test is very important.  Change to a web-socket that does not exist and make sure one can get back to that screen to change it back (to correct it).

**Comment by valzav** [comment]
> Also, a basic test is very important.  Change to a web-socket that does not exist and make sure one can get back to that screen to change it back (to correct it).

Wrong ws connection will get user to InitError page where user can change the connection

**Comment by svk31** [comment]
Yep, think we can close this now no?

**Comment by valzav** [comment]
What would be nice to have is checking entered connection - if we can connect to it we can show it in green and add button to switch to this connection, we can either refresh the page or reset cache.
But let's address this later, I'll create a separate issue for this.
