### ISSUE TITLE
Import keys cannot handle large json files

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#119]
I have over 20 MB wallet backup files (json). When I tried to import these files, the wallet gave me an error message; "walletbackup.json is an unrecognized format"

**Comment by jcalfee** [comment]
I have seen large wallet files contain unicode characters messing up the import.  In the mean time, we are much better off testing with this key file below, it is easier to read and can be edited if needed.  Although I'm not sure if Vikram has checked it in yet.  Here is a ticket you can watch.  The import keys should accept this format already.

https://github.com/cryptonomex/graphene/issues/214
