### ISSUE TITLE
[UI] / [Market.jsx] - Top Nav is missing 

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#121]
![Missing Top Nav - screenshot](https://cloud.githubusercontent.com/assets/6280810/9025599/45a0da8c-390b-11e5-9e95-a5ec62cb1bd4.png)

**Comment by svk31** [comment]
That most likely means your wallet wasn't working or not installed, only reason I can see for it. Are you able to reproduce it?

**Comment by valzav** [comment]
Top nav is not shown if you didn't create wallet, normally you shouldn't be able to navigate anywhere besides wallet/account creation screen, probably you used bookmarked location.
Later we are planning to allow browsing without wallet creation, maybe in a week or so.
Let's discard this issue for now.

**Comment by c055** [comment]
mh but i've created a wallet before AFAIK ..
