### ISSUE TITLE
Order confirmation dialog issues

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#130]
1.  It sets the order expiration to 5 years from now, but to the casual observer that wasn't immediately clear.  I suggest the confirmation be in "relative" time... ie:

30 seconds,
1 minute
1 hour
1 day
1 week
1 month
1 year

With a mouse over that shows the absolute date.
1. The confirmation does not display a price any where nor reflect the values the user ACTUALLY entered.    When confirming an action a user shouldn't have to do math to verify it is what they want.
2. If there is insufficient funds it should disable the submit button and notify the user while they are entering data. 
3. I really like that we show the transaction details (what is actually going on the wire), but we need to abstract things a bit for orders.

**Comment by jcalfee** [comment]
@svk31 expiration is in seconds.  So, 10 minutes from now should be `Math.round(Date.now()/1000) + (chain_config.expire_in_min * 60)` .. @bytemaster what about checking NTP?

**Comment by jcalfee** [comment]
Also, there is `tr.set_expire_minutes(10)`
