### ISSUE TITLE
Conflict in Notification Dialogs

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#133]
![image](https://cloud.githubusercontent.com/assets/347290/9063240/7e9b83f2-3a94-11e5-925b-f2dc4eff6a2b.png)

**Comment by jcalfee** [comment]
I have a solution.. @valzav can we modify your css?

https://github.com/cryptonomex/graphene-ui/commit/d89722ee6668c1e9220bade099b62d2fec59b136

**Comment by jcalfee** [comment]
note: the comment is: "Adjust the css position for notices.. bottom messages can't be seen"

**Comment by svk31** [comment]
I've moved the "New transaction" notifications to the bottom, let me know if that works for you if not we can try something else.

**Comment by svk31** [comment]
Any feedback on the new positioning? Can we close this?

**Comment by jcalfee** [comment]
You can close it.. I would have like to move the notification messages to the bottom though.  They come up so often and just get in the way or are a bit distracting.  If you still want the let me know, I just need to move some positioning code that @valzav added to move the notice below the toolbar.  That will not be needed anymore.

**Comment by valzav** [comment]
Right now we are using two different libraries for the notifications, we need to stick to one of them.

**Comment by svk31** [comment]
Actually there's only one library, the operation notifications are just a custom component using the Foundation notification layout. The reason they're still separate is that the library doesn't support React components as input so we can't reuse the operation formatting from Operation.jsx there. see #72 for this though

**Comment by jcalfee** [comment]
If you make a feature (issue) request he might add it.  He was very helpful in getting us setup with the Notification Actions system.
