### ISSUE TITLE
Add GUI Console

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#14]

**Comment by VoR0220** [comment]
What will the GUI need to contain in terms of fields? I assume basic accounts and sending back and forth would be a good start but where to go from there?

**Comment by valzav** [comment]
What do you think about exposing $g object from graphene-ui/cli to window so users can use browser's console?

**Comment by VoR0220** [comment]
As in run a localhost node out of their browser using the $g object? Forgive me, I'm still trying to work out what the $g object is doing (I've been doing this a little part time).

**Comment by valzav** [comment]
Just run "npm start" when you are in ./cli dir to see it in action. This is where $g is defined https://github.com/cryptonomex/graphene-ui/blob/master/cli/app.js#L33

**Comment by valzav** [comment]
Ideally it would be great to have a functional style interface, e.g. in order to send money, you do:

> account("alice").transfer(5,"BTS").to("bob")
> // so it would make this possible:
> a = account("alice")
> a.balance() // prints something like ["100 BTS"]
> t = a.to("bob")
> t.transfer(5,"BTS")
> t.transfer(10,"BTS")
> a.balance() //  ["85 BTS"]

**Comment by VoR0220** [comment]
This is what I get:

> cli@0.0.1 start /home/vor0220/graphene-ui/cli
> webpack; node ./bundle.js
> 
> Note: The code generator has deoptimised the styling of "/home/vor0220/graphene-ui/dl/lib/bytebuffer_3.5.4.js" as it exceeds the max of "100KB".
> Note: The code generator has deoptimised the styling of "/home/vor0220/graphene-ui/dl/src/common/dictionary_en.js" as it exceeds the max of "100KB".
> Hash: 44a594e9a91232261733
> Version: webpack 1.8.11
> Time: 7043ms
>        Asset     Size  Chunks             Chunk Names
>    bundle.js   1.3 MB       0  [emitted]  main
> bundle.js.map  1.73 MB       0  [emitted]  main
> - 163 hidden modules
> 
> WARNING in ../dl/lib/bytebuffer_3.5.4.js
> Critical dependencies:
> 1:544-552 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. >Try to require the original source to get better results.
> @ ../dl/lib/bytebuffer_3.5.4.js 1:544-552
> 
> WARNING in ../dl/~/websocket/lib/BufferUtil.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/bufferutil in >/home/vor0220/graphene-ui/dl/node_modules/websocket/lib
> @ ../dl/~/websocket/lib/BufferUtil.js 9:19-57
> 
> WARNING in ../dl/~/websocket/lib/BufferUtil.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ../build/default/bufferutil in >/home/vor0220/graphene-ui/dl/node_modules/websocket/lib
> @ ../dl/~/websocket/lib/BufferUtil.js 11:19-57
> 
> WARNING in ../dl/~/websocket/lib/Validation.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/validation in >/home/vor0220/graphene-ui/dl/node_modules/websocket/lib
> @ ../dl/~/websocket/lib/Validation.js 9:21-59

WARNING in ../dl/~/websocket/lib/Validation.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/default/validation in /home/vor0220/graphene-ui/dl/node_modules/websocket/lib
 @ ../dl/~/websocket/lib/Validation.js 11:21-59
Graphene > !!! WebSocket Error  ws://localhost:8090
[App.js] ----- ERROR -----> { type: 'error',
  target: 
   { _listeners: 
      { onopen: [Function],
        onerror: [Function],
        onclose: undefined,
        onmessage: [Function] },
     _url: 'ws://localhost:8090',
     _readyState: 3,
     _protocol: undefined,
     _extensions: '',
     _bufferedAmount: 0,
     _binaryType: 'arraybuffer',
     _connection: undefined,
     _client: 
      { domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        config: [Object],
        _req: null,
        protocols: [],
        origin: undefined,
        url: [Object],
        secure: false,
        base64nonce: 'lLZWkD26qUH4EMRFzEZM0A==' } } } undefined
Graphene > 

Is this to be expected?

**Comment by valzav** [comment]
Are you running a witness node?
On June 30, 2015 at 4:11:11 PM, VoR0220 (notifications@github.com) wrote:

This is what I get:

cli@0.0.1 start /home/vor0220/graphene-ui/cli
webpack; node ./bundle.js

Note: The code generator has deoptimised the styling of "/home/vor0220/graphene-ui/dl/lib/bytebuffer_3.5.4.js" as it exceeds the max of "100KB".
Note: The code generator has deoptimised the styling of "/home/vor0220/graphene-ui/dl/src/common/dictionary_en.js" as it exceeds the max of "100KB".
Hash: 44a594e9a91232261733
Version: webpack 1.8.11
Time: 7043ms
Asset Size Chunks Chunk Names
bundle.js 1.3 MB 0 [emitted] main
bundle.js.map 1.73 MB 0 [emitted] main
- 163 hidden modules

WARNING in ../dl/lib/bytebuffer_3.5.4.js
Critical dependencies:
1:544-552 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
@ ../dl/lib/bytebuffer_3.5.4.js 1:544-552

WARNING in ../dl/~/websocket/lib/BufferUtil.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/bufferutil in /home/vor0220/graphene-ui/dl/node_modules/websocket/lib
@ ../dl/~/websocket/lib/BufferUtil.js 9:19-57

WARNING in ../dl/~/websocket/lib/BufferUtil.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/default/bufferutil in /home/vor0220/graphene-ui/dl/node_modules/websocket/lib
@ ../dl/~/websocket/lib/BufferUtil.js 11:19-57

WARNING in ../dl/~/websocket/lib/Validation.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/validation in /home/vor0220/graphene-ui/dl/node_modules/websocket/lib
@ ../dl/~/websocket/lib/Validation.js 9:21-59

WARNING in ../dl/~/websocket/lib/Validation.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/default/validation in /home/vor0220/graphene-ui/dl/node_modules/websocket/lib
@ ../dl/~/websocket/lib/Validation.js 11:21-59
Graphene > !!! WebSocket Error ws://localhost:8090
[App.js] ----- ERROR -----> { type: 'error',
target:
{ _listeners:
{ onopen: [Function],
onerror: [Function],
onclose: undefined,
onmessage: [Function] },
_url: 'ws://localhost:8090',
_readyState: 3,
_protocol: undefined,
_extensions: '',
_bufferedAmount: 0,
_binaryType: 'arraybuffer',
_connection: undefined,
_client:
{ domain: null,
_events: {},
_eventsCount: 0,
_maxListeners: undefined,
config: [Object],
_req: null,
protocols: [],
origin: undefined,
url: [Object],
secure: false,
base64nonce: 'lLZWkD26qUH4EMRFzEZM0A==' } } } undefined
Graphene >

Is this to be expected?

**Comment by VoR0220** [comment]
That might explain some things.

**Comment by VoR0220** [comment]
alright, no longer getting the error....that's nice. Alright then. What am I manipulating exactly with $g? Is it merely a message to be pushed into the stdin?

**Comment by jcalfee** [comment]
https://www.youtube.com/watch?v=31xhGDBoCgs
