### ISSUE TITLE
Display a warning if wallet is loaded in Incognito Mode

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#143]
When visiting the wallet for the first time, if you are in incognito mode it should warn the user that any wallet created will be lost if not backed up prior to closing the window.  

See this link for an example that will work in some browsers:
http://jsfiddle.net/w49x9f1a/

We should attempt to minimize false positives.

**Comment by theoreticalbts** [comment]
Fails on Firefox.

Maybe you should warn the user to back up their wallet before closing the window regardless of whether they're incognito or not?

**Comment by valzav** [comment]
I think we shouldn't let users to create wallets in incognito mode

**Comment by jcalfee** [comment]
There is a case for incognito mode, a user needs to access a wallet one time then wipe the machine clean.  Of course it would be far better to create a RAM only wallet that never gets cached to disk.  In addition any leakage of info will be erased by the incognito feature.  It is also a tool for testing by the end user and developer, they can test the restore function or wallet in a way that guarantees a restore bug can't effect the result without effecting there existing wallet.

**Comment by wmbutler** [comment]
@valzav @jcalfee I view this a fairly important item, especially as it related to inexperienced users. I created a wallet in incognito mode and didn't see any warnings (Chrome). I'd suggest we verify this and patch with this release if you agree.

**Comment by jcalfee** [comment]
We need to make a feature requests to add a incognito detection test as a w3c standard.  I'm not aware of any work around.

**Comment by jcalfee** [comment]
If the user tries to leave the page with BACKUP REQUIRED in the footer we could alert with a message..  Incognito mode or not...

**Comment by svk31** [comment]
We already have this message implemented: 
![image](https://cloud.githubusercontent.com/assets/6890015/11539272/94e6ed54-9926-11e5-9c76-b84e7b5df0bd.png)

**Comment by wmbutler** [comment]
nice!
