### ISSUE TITLE
Error Creating Wallet 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#148]
![image](https://cloud.githubusercontent.com/assets/347290/9305991/7ff14d2a-44c3-11e5-9291-54d614f95e64.png)

![image](https://cloud.githubusercontent.com/assets/347290/9305996/84d8e55a-44c3-11e5-9d96-f95b4edf9c47.png)

**Comment by jcalfee** [comment]
Run `npm install` and restart your web node.
