### ISSUE TITLE
Build Asset Details page

### ISSUE THREAD

**Issue by ChronosCrypto** [cryptonomex/graphene-ui#149]
The Asset page at /asset/{assetSymbol} currently consists only of an unordered list of relevant properties. This page needs to be built out as a compelling informational page for the asset.

**Comment by valzav** [comment]
I suggest to create a special github repo that would be hosting assets descriptions in different languages as well as other help copy. We just need to define asset description format that GUI would understand and render properly. GUI can either fetch this data on start provided repo url or it can be build process step - the build script would fetch assets pages and render them into html pages.

**Comment by valzav** [comment]
I'm closing this issue due to Chronos departure
