### ISSUE TITLE
Error Importing Wallet

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#155]
![image](https://cloud.githubusercontent.com/assets/347290/9329988/0dee882a-4584-11e5-8ab6-e2d842292e0d.png)

I imported part of my wallet, then reloaded the page.  It forgot about my partial import so I reloaded my backup.json file.    It detected my unclaimed balances.  Then I clicked import and I got DB errors.

**Comment by jcalfee** [comment]
This looks like your wallet was imported and saved to disk.  I just pushed a change to instead report in the UI:
 "This wallet has already been imported"

When on `http://localhost:8080/#/existing-account` you should be able to re-load and the Claim Balances section should appear along with a wallet unload modal.  There have been many changes, if you will clear your database `shimIndexedDB.deleteDatabase("graphene_db")` and `git pull` and try to break it again and let me know.  I was not able to break it as you described.

I'm still using 1 transaction for the import so it should not be possible to get a inconsistent state on disk.  It is possible for a bug to mess up ram though.
