### ISSUE TITLE
[Exchange] - ADD - Search on top of asset overview 

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#165]
…

**Comment by svk31** [comment]
Exchange overview already has one, do you mean in Explorer -> Assets ?

**Comment by c055** [comment]
yea

**Comment by wmbutler** [comment]
How about a very simple filter operation

![screen shot 2015-11-05 at 11 56 45 am](https://cloud.githubusercontent.com/assets/1254810/10975355/82659e28-83b4-11e5-8ada-a2bb07d55e23.png)

**Comment by c055** [comment]
to save space let's bring it on row ..
