### ISSUE TITLE
Claim button it doesn’t indicate that there is some work going on in the background

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#167]

**Comment by jcalfee** [comment]
The bottleneck is signing... I will look at deferring the signatures until after the transaction is confirmed.  The transaction confirmation dialog can report 'Signing....' before it broadcasts..

**Comment by valzav** [comment]
We can have custom states in the TransactionConfirmStore later, for now if you need to wait until user clicks confirm, you need to subscribe to TransactionConfirmStore events, find example in CreateAccount.jsx - look at onFinishConfirm callback, you need to watch for 'broadcasting' state.

**Comment by valzav** [comment]
One way to have custom states I can think of is to have a beforeBroadcasting function on transaction object and make TransactionConfirmActions to call in its broadcast method. 
Is it difficult for you to alter transaction object and add beforeBroadcasting function to it?

**Comment by jcalfee** [comment]
Part 1: move signing into the broadcast .. now, it will be covered by the spinner and allow for quick preview and serialization of the transaction

Part 2: (new ticket) Upgrade canonically valid signature algo for faster signing

**Comment by jcalfee** [comment]
https://github.com/cryptonomex/graphene-ui/issues/169
