### ISSUE TITLE
Question: How can I defined a reusable component in the Graphene GUI?

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#19]
I'm trying to defined my required properties on a reusable component via (class MyReusableComponent extends React.Component).propTypes....  It does not work, a React warning directed me to use React.createClass (instead of class ... extends React.Component).  When I do this in our app and nest <MyReusableComponent/> in the root element, render does not work because this is undefined: React.createClass({..., render: () => {this === undefined}).

According to the docs, that should have worked..
ref: https://facebook.github.io/react/docs/reusable-components.html

Note, there are other things like getInitialState() that do not work either.

**Comment by valzav** [comment]
Take a look how it's done with es6 classes e.g. in Forms/AutocompleteInput.jsx starting at line 80. Also when you use classes getInitialState is replaced with constructor.

**Comment by jcalfee** [comment]
When I tested the es6 class components I found propTypes to be ignored.  Try using the component but leave out a required property.  There will be no error from reactjs.

**Comment by jcalfee** [comment]
Lets just discuss in the messenger... I don't think we need ticket open for this.
