### ISSUE TITLE
Various issues arised from #111 related to creating an account on signup

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#192]

**Comment by jcalfee** [comment]
I do not have a faucet configured .. I am getting an error when I try to create my first account: `ERROR AccountActions.createAccount Error: value required for registrar_id: null` .. and the GUI reports "Failed to create account: account - unknown error"  This should probably say something about using a faucet instead?

**Comment by valzav** [comment]
yes, the first account is supposed to be created via faucet. I think "unknown error” means it couldn’t connect to the faucet, I’ll take a look if I can improve errors reporting.

> On Sep 10, 2015, at 10:23 AM, James Calfee notifications@github.com wrote:
> 
> It looks like the createAccount was designed to work without a registrar. https://github.com/cryptonomex/graphene-ui/blob/1e5139c5ffe9d70b14f77cc56924c41abda130d4/web/app/components/Account/CreateAccount.jsx#L57-L62 https://github.com/cryptonomex/graphene-ui/blob/1e5139c5ffe9d70b14f77cc56924c41abda130d4/web/app/components/Account/CreateAccount.jsx#L57-L62 .. But I am getting an error when I try to create my first account: ERROR AccountActions.createAccount Error: value required for registrar_id: null .. and the GUI reports "Failed to create account: account - unknown error" Should this say something about using a faucet instead?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/cryptonomex/graphene-ui/issues/192#issuecomment-139252326.

## 

Regards,
Val
