### ISSUE TITLE
Improve app Footer (so it is always a footer)

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#20]
I noticed that when I add a new App.jsx Route to a new component, the component will render but the footer "[logo] BitShares 2.0 ..... Head block # 1" does not remain at the bottom.   Rather than mock up each component with the magic to fix it, is there something we can add to App.jsx to fix it for all routes?

**Comment by svk31** [comment]
I think all you need to do is have the outermost element in your component be 

``` javascript
<div className="grid-block">
...
</div>
```

**Comment by jcalfee** [comment]
Thanks... I have moved stuff around so I can't test it full-circle.  It appears to not mess anything up though.  So, if you see the footer breaking free on any of your new components, please give something like this a try:

```
            return (
                <div className="grid-frame vertical">
                    <Header isUnlocked={this.state.isUnlocked}/>
                    <MobileMenu isUnlocked={this.state.isUnlocked} id="mobile-menu"/>
                    <Notifier class="overlay-notification"/>
                    <div className="grid-block">
                        <RouteHandler/>
                    </div>
                    <Footer/>
                </div>
            );
```
