### ISSUE TITLE
Website doesn't load when using Firefox private browsing

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#201]
The symptom is a gray screen and the following messages in JS console:

```
InvalidStateError app.js:40:0
```

[App.jsx] ----- App.willTransitionTo error -----> DOMError { name: "InvalidStateError", message: "A mutation operation was attempted …" } app.js:4:7397
    Unhandled promise rejection DOMError { name: "InvalidStateError", message: "A mutation operation was attempted …" }

The specific cause is the IndexedDB `open()` call [here](https://github.com/cryptonomex/graphene-ui/blob/2d467726acc2aa0ba3efdacfdff3baac2a5b43bd/dl/src/idb-root.js#L20) throws an exception when Firefox is set to forget history (for example, private browsing / incognito mode sets this, but I think it can also be enabled for non-private browsing in some settings screen).  louism reply to [this StackOverflow question](http://stackoverflow.com/questions/14082932/invalid-state-error-in-firefox-for-indexed-db) helped me track down the issue.

We should catch this exception and tell the user the website is not compatible with their privacy settings.  Related:  #143

**Comment by jcalfee** [comment]
That is a FF issue..

You can simply not use incognito mode.  I'm not so sure incognito works in RAM only anyways.  If it does not, it is just as good to clear the Db from the console or setup when you are done.

Run these separately to clear all Wallets:

```
resolve(WalletManagerStore.onDeleteAllWallets())
iDB.root.deleteDatabase(true)
```

https://bugzilla.mozilla.org/show_bug.cgi?id=781982
![image](https://cloud.githubusercontent.com/assets/204121/9825804/83d7ec64-589b-11e5-895c-56f5c6b8c385.png)

**Comment by theoreticalbts** [comment]
> You can simply not use incognito mode

Yeah, that's the obvious workaround for this problem.  The issue is that I got absolutely no information about what was wrong, I just saw a gray screen.  It took me an hour with the debugger to figure out what was going on and that incognito mode might be affecting it.

So the UI should catch the exception and display a message to the user on the actual web page along the lines of, "Couldn't open IndexedDB.  This may be because you are in Private mode, or you have browser history disabled.  Please come back without using Private mode."

It seems like it should be very simple for one of you web devs to make that happen, and it changes the user experience from "it's the developers' fault this buggy website is broken and there's nothing I can do to make it work, I guess I just have to wait for them to fix it" to "it's my fault I'm using unusual browser settings, and I can fix it myself in five seconds by disabling private mode."

**Comment by jcalfee** [comment]
Good Point!  I'll have a look, thanks for re-opening.   According to this ticket "there is no reliable or accurate way to detect if someone is browsing in an incognito/private/safe browsing mode" ... I can detect it and put a hint that this could be caused by incognito mode to hold us over in the mean time.

Some research is needed to see how our IndexedDb shim handles older browsers, maybe some other types of errors can be separated out from this general message.

**Comment by jcalfee** [comment]
@valzav this error is happening during the initial application loading in `App.willTransitionTo`.  Can you recommend a way to report this in the UI?
I'm able to trap it here:

```
    Apis.instance().init_promise.then(() => {
        return iDB.init_instance(window.openDatabase ? (shimIndexedDB || indexedDB) : indexedDB).init_promise.catch(
            error => {
            console.error('[App.jsx] Unable to initialize IndexedDb Database',error)
        }).then(() => {
```

I caught the error and did not re-throw it.  Still nothing rendered in the browser window so I don't have a way to report it in the UI (`notify` for example).

**Comment by jcalfee** [comment]
I guess we could transition to an error page and pass that error in as a string...

**Comment by jcalfee** [comment]
It would be nice if we could render a `<AppFatalErrors/>` component during the `App.willTransitionTo` passing a error string like `idb_init_promise` and an object `error` in as parameters.  The component could do something like (if FF and error == idb_init_promise) then say (this could be caused by private browsing) ...

**Comment by jcalfee** [comment]
Or `window.location.href =` to a static page.

**Comment by wmbutler** [comment]
Should we tie this to #143 and display the same message we display for Chrome Incognito? We can always circle back and add something better for developers later.

**Comment by jcalfee** [comment]
This can be closed.. valzav added an alert message that basically says this error could be caused by incognito mode.. I can confirm it worked.  If it does not re-open..
