### ISSUE TITLE
Market Displays Mixed Asset Pairs

### ISSUE THREAD

**Issue by Riverhead** [cryptonomex/graphene-ui#203]
Viewing CORE/USD and then switching to CORE/NOTE it loads the CORE/NOTE fields and labels but prices are still CORE/USD

<a href="http://imgur.com/49m1fpS"><img src="http://i.imgur.com/49m1fpS.png" title="source: imgur.com" /></a>

**Comment by svk31** [comment]
I'm unable to reproduce this, how are you switching?

**Comment by Riverhead** [comment]
I too am now unable to reproduce which makes this useless as a bug report. Anyway, here is what I was doing:

1) Sold a small amount of bit USD (0.16 USD) for ~40 Core
2) Try to sell some NOTE to myself for CORE so went to the Exchange link and selected the Core / NOTE pair.
3) Put in 1000 Note into the sell quantity and then moved over to the depth list to select the lowest price. Once clicked the list flipped from the small NOTE list (just my orders on there) to the USD list and the values below the input fields changed to CORE / USD values. Everything else stayed NOTE.

I was thinking browser lag but it had the correct depth list then switched to USD prices.

**Comment by svk31** [comment]
Market data always gets reset when you switch markets, whether that's just flipping or navigating to a new market, so I'll write this down to either lag or possibly (more likely imo) and unrelated bug in ChainStore that has since been fixed. Feel free to reopen if you see encounter this again.

**Comment by Riverhead** [comment]
Sounds good. I haven't seen it since and I've been using the UI a lot. I'll
only reopen it if I can reproduce it or capture a log file or something
else useful.
