### ISSUE TITLE
Market visually accepts cancel from insufficent fund transaction

### ISSUE THREAD

**Issue by Riverhead** [cryptonomex/graphene-ui#205]
Canceled an order without the funds to pay the fee and while the transaction pop-up indicated correctly that the transaction failed the market visually reacted as if it hadn't. Screenshot 1of2 is after I closed the "Failed" dialog box and Screenshot 2of2 is when I left the exchange and came back in which returned it to the correct state.

Notice that order is listed with the "Cancel" option in the second photo but not the first.

![After Dialog close Image](http://i.imgur.com/QE8XUqe.png)

![After returning to market Image](http://i.imgur.com/slitL4Z.png)

**Comment by svk31** [comment]
This is a remnant from when we didn't have the confirmation popup and wanted to do optimistic updates of the orderbook state, I'll remove it.
