### ISSUE TITLE
FormattedAsset is turning up empty.. is it decorator or chain store?

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#207]
After a wipe the browser's database and import `testnet-shared-private-keys-export.json`, the "nathan" balance claims shows up empty.  The balance claim is passing an amount and asset id to FormatAsset. 

I wonder if it is not loading or refreshing the asset from the ChainSore.  When I refresh the page it works.

![image](https://cloud.githubusercontent.com/assets/204121/9881052/ea33ccc6-5b93-11e5-86f3-3d47640def8f.png)

These are the values being passed into FormattedAsset:

```
BalanceClaim.jsx:97... asset_id 1.3.0
BalanceClaim.jsx:98 ... balance.unvested.unclaimed 1000000000000
```

If I try to check it off and claim the balance, almost every element in the transaction confirm dialog is empty..

I attempted to init the ChainStore earlier in the Apps startup (in the transactionTo) but that did not help.

**Comment by valzav** [comment]
Did you fix this already? I can take a look..

**Comment by jcalfee** [comment]
No, I was wondering if we should use a static page or try to use a component.. or if you had another idea.

**Comment by jcalfee** [comment]
verified
