### ISSUE TITLE
Create Account needs some more options (so it can work without a faucet)

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#208]
Create Account needs: registrar, referrer, and a referrer percent

A review for this tasks:
`registrar //This account pays the fee. Must be a lifetime member.`
https://github.com/cryptonomex/graphene/blob/test2b/libraries/chain/include/graphene/chain/protocol/account.hpp#L48-L55

**Comment by jcalfee** [comment]
The AccountStore does not have a myAccounts list.. If it did we should see a pay_from when the selected account from this list being used as the registrar and referrer.  This should probably be renamed to use linkedAccounts...

**Comment by jcalfee** [comment]
I'll look into filtering linkedAccounts for this screen..

**Comment by valzav** [comment]
Could you add myAccounts list to AccountStore?

**Comment by jcalfee** [comment]
depends on https://github.com/cryptonomex/graphene-ui/issues/214#issuecomment-140762281

**Comment by jcalfee** [comment]
I was thinking about a getMyAccounts static method.  It will change a bit and need to consider key references instead of linked Accounts.  Linked Accounts is ready now though and works reasonably well.

https://github.com/cryptonomex/graphene-ui/blob/master/dl/src/stores/AccountStore.js#L42-L76
