### ISSUE TITLE
Implement Wallet Login Protocol

### ISSUE THREAD

**Issue by valzav** [cryptonomex/graphene-ui#216]
https://github.com/cryptonomex/graphene/wiki/Wallet%20Login%20Protocol

**Comment by wmbutler** [comment]
@valzav Curious as to where this sits on the priority list. You thinking a month away or longer?

**Comment by valzav** [comment]
this is of low priority

**Comment by wmbutler** [comment]
OK, putting it in December.

**Comment by wmbutler** [comment]
Moving way out to January so we can focus.

**Comment by valzav** [comment]
Not of high priority, closing for now
