### ISSUE TITLE
Consider this behaviour using BindToChainState with another decorator

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#219]
If I defined like this:

``` javascript
@connectToStores
@BindToChainState()
class BrainkeyAccounts ...
```

I get this error:
`Uncaught Error: connectToStores() expects the wrapped component to have a static getStores() method`

And swapping them around:

``` javascript
@BindToChainState()
@connectToStores
class BrainkeyAccounts ...
```

Then BindToChainState can not see my propTypes so they do not get resolved.  Is there a way for `BindToChainState` to return its original object?  connectToStores is by design hiding non-exported methods so I don't this it is an option to request a change on that side.

fyi, just a feature request.. Turns out I really did not need to bind both on the same component.

**Comment by valzav** [comment]
I've encountered this issue too, solved by splitting component into several smaller ones.
Not sure how to make them work together - BindToChainState returns the wrapper, it cannot return initial component.

**Comment by jcalfee** [comment]
closing for now
