### ISSUE TITLE
BindToChainState did not update its ChainTypes.ChainAccountsList component

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#220]
Summary: Basically, I found the decorator's `this.chain_accounts_list` is empty at the time some chain store data came in and that it did not update its component leaving the UI empty.

1) Uncomment BindToChainState's `console.log("-- Wrapper.update -->", this.chain_accounts_list)`
2) set DEBUG = true in ChainStore

Create a wallet (or keep your existing one) then goto `http://localhost:8080/#/wallet/brainkey` and enter a brainkey that will resolve with at least one account.  Observe in the console that in the very end, the ChainStore will log `full_account:` and your account(s) then nothing else.  At that point I followed its call to updateSubscribers (enabled a breakpoint) and trapped again in BindToChainState's update.  It receives that event, however its `this.chain_accounts_list` is be empty to it will not pass along the data to its component.  The accounts do not show up in the browser's UI.

Optional (fyi): trigger a re-render and the accounts will display.  One way to do this is to run:

``` javascript
resolve(WalletManagerStore.onDeleteAllWallets()); iDB.root.deleteDatabase(true);
```

**Comment by valzav** [comment]
Sorry, forgot to tell you about additional parameter to the decorator: keep_updating, use it like this:
@BindToChainState({keep_updating: true})
This parameter affects a small optimization - without this parameter decorator stops after it gets all its initial objects resolved, e.g. first time your accounts list is empty or has one account, it retrieves account and marks its state as resolved, later you add more accounts to the list but it won't proceed unless keep_updating is true.
I should have documented this..
