### ISSUE TITLE
Market Interface Enhancements

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#230]
![image](https://cloud.githubusercontent.com/assets/347290/10033472/bd89adc0-6157-11e5-94f3-211fa68a79bb.png)

**Comment by svk31** [comment]
That's already the case, try going to #/exchange/trade/ABITUSDA_USD for example. About the position, there's not really enough space where you've put them, there is on your screen but on smaller screens there won't be, especially if the user has big balances and the asset names are long.

We could put the buttons up top next to the account selector but that feels awkward too, not sure really. We probably need to make them smaller at least, I'll play around with it but feel free to do so yourself as well.

**Comment by valzav** [comment]
Most logical place for the Borrow button is next to Buy button - when you are looking to get BitUSD you may want to buy it or borrow it. So I would put Borrow and Buy very close to each other.

**Comment by valzav** [comment]
I think Borrow button takes too much space when put inside or above the form, in the transaction below I moved it to the top-right corner and changed its style to be less saturated - this is for advanced users anyways so they will find their to this button.

**Comment by svk31** [comment]
Looks good to me, I added some padding-right to the block because it was behind the scrollbar, closing this now.
