### ISSUE TITLE
A few translation issues

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#232]
The name "delegates" has been deprecated but still occurs on some pages:
- https://graphene.bitshares.org/#/explorer/blocks
  
  ACTIVE DELEGATES: 33

"Delegates" also occurs in a URL and a prompt on the page that URL points to:
- https://graphene.bitshares.org/#/explorer/delegates
  
  Total number of delegates active: 11

Finally, there are two translation items (on your account's main page!) which are simply missing:
- https://graphene.bitshares.org/#/account/????/voting
  
  Missing translation: en.account.votes.approve_worker
  Missing translation: en.account.votes.reject_worker

I suggest grepping for "delegate" in the codebase and translation files and purging it wherever it occurs.

**Comment by neura-sx** [comment]
Also, there is a minor spelling mistake when you invert the trading pair on the market page. BORROWW instead of BORROW.

![spelling-bug](https://cloud.githubusercontent.com/assets/11573977/10071403/e7cfd150-62b9-11e5-9bc5-81f5f5af2fa5.png)
