### ISSUE TITLE
Collateral dialog precision and editing issues

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#233]
The collateral position dialog has precision issues.  E.g. with feed at 0.0995 USD/CORE, borrowing $10 at a collateral ratio of 2 sets collateral to 1.9900000000000002 CORE.

Here are all the problems I found in 5 minutes of playing with this dialog:
- Asset precision is wrong, 2x collateral should be `201.0051` (exact number is about `201.00502512562812` by my calculations, but this should be rounded up, see next point).
- You should round up to the next-highest satoshi, that way if you set the slider at exactly the required collateral amount, you won't get an invalid transaction.
- The feed price is not flipped in a flipped market.
- Displays last decimal place far in excess, you are using floats somewhere.  Ideally you only use integer arithmetic.  If that's not feasible, at least truncate the decimal result of floating-point arithmetic.
- Selecting either text field should highlight the existing text, so if you click on a field and start typing, it will replace the text with what you type.
- The fields annoyingly undo your edits if the result of an edit would be an invalid value.  So if you have "15" in the "Amount to borrow" field, select all the text (which should happen automatically as per the previous point), and type "0.25", the result is "15.25".  Similarly, the backspace / delete key cannot delete the last nonzero character of an amount.  Problems typing amounts that begin with "0." or "." will be particularly problematic for BitAssets such as BitBTC which have a high enough unit value that borrowing fractional amounts is economically practical for small-time users.  My preference as a user is to never have the UI directly edit what I enter, because that's a recipe for me to blame executing an order with (potentially financially disastrous) unintended values on the UI's behavior.  If I give the UI something invalid, it should tell me when I go to confirm the action, and give me a little warning icon next to the invalid field.  (The warning icon is non-essential, but it makes the UI feel really slick and polished if you have it, because it lets me fix mistakes as they're entered, which is less cognitive load than finding out they're invalid at the very end and then having to go back.)
- The required maintenance level of collateral should be displayed.
- The drop-downs for asset names are pointless as they only give me one choice.
- Each of the three fields should have a "lock" icon allowing that field to be locked.  Locking a field should unlock the others (so only one field can be locked at a time).  Then adjusting either unlocked field will update the other unlocked field.  This addresses the common use case of maintaining the same collateral ratio, with this UI you'd be able to just lock the collateral slider and enter the new position amount.  The unlocked field should be rounded correctly (collateral up, borrow amount down) to produce a valid transaction when the slider is exactly at the minimum required collateral level.

**Comment by svk31** [comment]
The precision thing is a hassle all around, we get javascript floating point errors like that from the simplest of calculations.. I guess we can try rounding to next-highest satoshi. 

What exactly constitutes a flipped market here? The feed price is only given one way and there's no reference as to what's flipped or not.. You can click on any price and it'll flip, that's the easiest way we've found to deal with this. They're even reversed between them, the core exchange rate and settlement_price are flipped with respect to each other. In general it's also a hassle to reason about..

I've assumed the required maintenance level value of 1750 is a ratio of 1.75, is that right?

I like the lock option, and will see what I can do about the rest.

**Comment by mindphlux1** [comment]
I submitted a PR that introduces fixes the calculation bug by introducing round the collateral value to the precision of the CORE asset.

https://github.com/cryptonomex/graphene-ui/pull/314

**Comment by wmbutler** [comment]
Please close @svk31 if this has been addressed. I see a commit.

**Comment by svk31** [comment]
Parts of it have been adressed and many changes have been made to the Modal since that time, so I'd say the Modal is good enough as is. As there are more important things to work on I'm pushing this back a couple milestones.

**Comment by wmbutler** [comment]
Sounds good. @theoreticalbts can you make a note to review this after 1225 is released to let us know if this is resolved in you opinion?

**Comment by wmbutler** [comment]
Closing since no response from @theoreticalbts
