### ISSUE TITLE
Market depth chart wrongly converted when the trading pair is inverted

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#240]
When the trading pair is inverted, the market depth chart is not properly converted. It should be symmetrical and it clearly isn't. Maybe it is just a scaling issue.

![out-of-scale-bug-01](https://cloud.githubusercontent.com/assets/11573977/10071620/82155c48-62bb-11e5-806a-40e0e40178b9.png)

![out-of-scale-bug-02](https://cloud.githubusercontent.com/assets/11573977/10071622/83943896-62bb-11e5-9af8-debbea33a4b7.png)

**Comment by svk31** [comment]
This is simply a matter of the x-axis range changing, in the reversed plot the x range in non-reversed units is around 5 CORE/ABITUSDA to around 33 CORE/ABITUSDA, compared to around 2 - 35 in the normal plot
