### ISSUE TITLE
Serialization appears to be broken using latest build of the toolkit 

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene-ui#25]
After building the toolkit and updating the serialization using js_operation_serializer I get this error when trying to place an order:

order error: 0 exception: unspecified
Invalid hex character ','
    {"c":","}
    th_a  hex.cpp:13 from_hex
graphene-ui signer address GPHFAbAx7yuxt725qSZvfwWqkdCwp9ZnUama digest 64c23e327934cd07ae13abf988ca6dbece6816149240595d2bdb6df4e0b9d4c9 public GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV transaction 000093459455000001010000000000000000000ff4010000000000000140ff1005000000000080e7fc5e00 {"ref_block_num":0,"ref_block_prefix":1435780499,"relative_expiration":0,"operations":[[1,{"fee":{"amount":"0","asset_id":"1.4.0"},"seller":"1.3.15","amount_to_sell":{"amount":"500","asset_id":"1.4.1"},"min_to_receive":{"amount":"85000000","asset_id":"1.4.0"},"expiration":"2020-07-01T19:44:00","fill_or_kill":false}]],"signatures":["11, XW\u0012e\\u001f}Y�mI�@�Q�4�\u0011\u0002�\u0003�k�k+�-6<�\u0005�\u0016\u001d�\"�(�1\u001f\u000e2F|�{Xl�'�2"]}

**Comment by jcalfee** [comment]
https://github.com/cryptonomex/graphene-ui/commit/c2b1c79f41405baec2c7186d163a423d463a92a1
https://github.com/cryptonomex/graphene-ui/commit/10edfc5c76b2e8266eca4ca48c1034e119cfd19e
https://github.com/cryptonomex/graphene-ui/commit/2440586ced552aa687c16ae4aaa7a92f89af07cf
https://github.com/cryptonomex/graphene-ui/commit/16e7358e7d823be37213f13b83e29bf74bdf2b41
