### ISSUE TITLE
Wrong password ignored when updating a third-party collateral position

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#250]
When updating a third-party collateral position the user is asked for a wallet password but no matter what s/he enters in the password text field the application still proceeds.

How to recreate:
(1) Lock the wallet
(2) On the Dashboard page choose an account that does not belong to you but has at least one open collateral position
(3) Try to update the collateral position by clicking the UPDATE button and moving the slider a bit in the pop-up window.
(4) When you click the "ADJUST POSITION" button you'll be asked for the wallet's password
(5) Enter a wrong password (or click the CANCEL button)
(6) The application will still proceed to the confirmation screen even though it should not

The bug occurs in both Chrome and Firefox (on Windows 7)

**Comment by neura-sx** [comment]
Update: similar thing happens on the market page when trying to place an order while the active account is not yours - the app lets you proceed without the password.

**Comment by wmbutler** [comment]
I'd classify this as a pretty important bug. Bumping this to current milestone.

**Comment by wmbutler** [comment]
@valzav which dev is best equipped to solve this?

**Comment by valzav** [comment]
@svk31

**Comment by svk31** [comment]
I can't reproduce this as described, although there is an unhandled error when updating someone else's margin position. I'll push a fix for that, but I can't get past the unlock screen, not in the Borrow Modal nor in the market page

**Comment by wmbutler** [comment]
ok @neura-sx please test and close.
