### ISSUE TITLE
Witnesses page broken on Firefox

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#261]
Console messages:

```
TypeError: i is null vendors.js:17:10789
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vendors.js:19:30281
Connecting... app.js:6:17385
"connecting to wss://graphene.bitshares.org:8090" app.js:6:17789
db init done app.js:4:7136
AddressIndex load 10 app.js:42:21288
ChainStore Init app.js:50:15474
synced and subscribed, chainstore ready app.js:50:15913
"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of t. See https://fb.me/react-warning-keys for more information." vendors.js:1:20307
Warning: Failed propType: Invalid prop `amount` of type `string` supplied to `t`, expected `number`. Check the render method of `r`. vendors.js:1:20307
Warning: Failed propType: Invalid prop `decimalOffset` of type `string` supplied to `t`, expected `number`. Check the render method of `r`. vendors.js:1:20307
TypeError: A date or timestamp must be provided to formatRelative() app.js:51:16493
Error: Invariant Violation: findComponentRoot(..., .0.0.2.1.0.1.0.0.0.0.1.0.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``. vendors.js:1:12615
TypeError: i is null vendors.js:17:10789
TypeError: A date or timestamp must be provided to formatRelative() app.js:51:16493
TypeError: i is null
```

I suspect the cause is that tables created in 40c0f4ea18a6400445a3ac3323d830f233b3d228 need `<tbody>` -- see http://stackoverflow.com/questions/26689900

**Comment by valzav** [comment]
I’m working on a fix for this issue

> On Oct 1, 2015, at 12:09 PM, theoreticalbts notifications@github.com wrote:
> 
> Console messages:
> 
> TypeError: i is null vendors.js:17:10789
> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vendors.js:19:30281
> Connecting... app.js:6:17385
> "connecting to wss://graphene.bitshares.org:8090" app.js:6:17789
> db init done app.js:4:7136
> AddressIndex load 10 app.js:42:21288
> ChainStore Init app.js:50:15474
> synced and subscribed, chainstore ready app.js:50:15913
> "Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of t. See https://fb.me/react-warning-keys for more information." vendors.js:1:20307
> Warning: Failed propType: Invalid prop `amount` of type `string` supplied to `t`, expected `number`. Check the render method of `r`. vendors.js:1:20307
> Warning: Failed propType: Invalid prop `decimalOffset` of type `string` supplied to `t`, expected `number`. Check the render method of `r`. vendors.js:1:20307
> TypeError: A date or timestamp must be provided to formatRelative() app.js:51:16493
> Error: Invariant Violation: findComponentRoot(..., .0.0.2.1.0.1.0.0.0.0.1.0.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``. vendors.js:1:12615
> TypeError: i is null vendors.js:17:10789
> TypeError: A date or timestamp must be provided to formatRelative() app.js:51:16493
> TypeError: i is null
> I suspect tables created in 40c0f4e https://github.com/cryptonomex/graphene-ui/commit/40c0f4ea18a6400445a3ac3323d830f233b3d228 need <tbody> -- see http://stackoverflow.com/questions/26689900 http://stackoverflow.com/questions/26689900
> —
> Reply to this email directly or view it on GitHub https://github.com/cryptonomex/graphene-ui/issues/261.

## 

Regards,
Val
