### ISSUE TITLE
Wallet auto lock

### ISSUE THREAD

**Issue by valzav** [cryptonomex/graphene-ui#265]
- [x] setting to control timeout
- [x] lock wallet automatically after timeout has elapsed

**Comment by jcalfee** [comment]
Can the wallet auto-lock reset itself on activity?  The wallet just locked on me in the middle of using it.  

The console reported:  `auto locking after 600 s`

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#19
