### ISSUE TITLE
Lock/unlock icon is not updated after the unlocking process is cancelled

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#267]
When you lock your wallet and then try to unlock it but abort the unlocking process, the "lock/unlock" icon in the top right corner becomes inconsistent with the current status of the wallet .

Chrome / Win 7

![unlock-icon-bug](https://cloud.githubusercontent.com/assets/11573977/10250235/e88c7c6c-6929-11e5-81c5-c271e2594ec4.png)

**Comment by neura-sx** [comment]
Also, it takes 2 clicks to dismiss the "Unlock wallet" pop-up with the CANCEL button. The first time you click nothing happens.

**Comment by valzav** [comment]
> Also, it takes 2 clicks to dismiss the "Unlock wallet" pop-up with the CANCEL button. The first time you click nothing happens.

This is already fixed, I'll update hosted wallet later today.
