### ISSUE TITLE
If you're online when witnesses change, old witnesses stay visible

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#270]
If the set of witnesses changes (for example due to new witness(es) being voted in), you need to reload the page, otherwise old witnesses will still be displayed.

**Comment by svk31** [comment]
This should not be the case after I migrated the witnesses page to use the BindToChainState decorator as we're now notified of changes in the witness list as well as the witnesses themselves. Closing but reopen it if it's still an issue for you.
