### ISSUE TITLE
IE 11 import problem

### ISSUE THREAD

**Issue by testzcrypto** [cryptonomex/graphene-ui#271]
No import button: 
![image](https://cloud.githubusercontent.com/assets/4957705/10263186/acc5721a-6a05-11e5-8e0f-f2daa10795a6.png)

**Comment by wmbutler** [comment]
Bumping this to current Milestone

**Comment by valzav** [comment]
Spent a lot of time today trying to make it work in IE - no luck.
Let's cease IE support until we have time and resources to fix it.

**Comment by wmbutler** [comment]
OK, let's detect for it and present a banner to the user. I'll UX it.

**Comment by wmbutler** [comment]
![screen shot 2015-11-09 at 8 16 59 pm](https://cloud.githubusercontent.com/assets/1254810/11051660/dfeeb88c-871e-11e5-87dc-8ecd8d4e4e78.png)

**Comment by jcalfee** [comment]
Some browsers do not offer full support for the BitShares wallet. ...

**Comment by jcalfee** [comment]
We recommend the chrome browser.

**Comment by jcalfee** [comment]
Correction, like you have it: "the Google Chrome Browser"

**Comment by wmbutler** [comment]
Updated.

**Comment by wmbutler** [comment]
Duplicate #474
