### ISSUE TITLE
Application pages forgetting their state (UX enhancement)

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#272]
The #/explorer/accounts page has a very nice feature: it's able to keep its state, i.e. when you navigate away from it and then navigate back to it, the page remembers the content of the filter field.

![state-remebered](https://cloud.githubusercontent.com/assets/11573977/10263727/987a43b0-69f8-11e5-95a6-53aa7baa6266.png)

Would it be possible to apply the same functionality on other pages? e.g. 
# /explorer/witnesses
# /explorer/committee-members
# /markets
# /transfer

This would make a very nice UX enhancement.

**Comment by svk31** [comment]
I've added this for the first three on your list, I think the transfer page needs some more thought as to what should be remembered or not so I'm leaving it out of this.

**Comment by wmbutler** [comment]
@neura-sx please verify and close. Transfer state will be worked at a later time once it's been re-imagined.

**Comment by neura-sx** [comment]
In version 151119 ([Chrome / Win7] & [FF / Win7]) I don't see any improvement in this respect.

e.g. when I enter something into the filter text field on the explorer/witnesses page, then navigate away and come back to this page - the filter text field is always reset (i.e. it's empty).

Whereas on the explorer/accounts page it works as it should - I can enter a filter value and then navigate away from this page and later on come back and it still "remembers" the filter value.

**Comment by svk31** [comment]
That's because it's not in that version, it's only live in master branch of graphene-ui.

**Comment by wmbutler** [comment]
@neura-sx This will be in 1125 minus the Transfer State.
