### ISSUE TITLE
Memo missing on the transfer confirmation pop-up (UX enhancement)

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#273]
The memo message is not being shown on the transfer confirmation pop-up.
It's not critical but it would be nice to have it as in some cases the memo might be very important (e.g. some exchanges require it).

![memo-unconfirmed](https://cloud.githubusercontent.com/assets/11573977/10263740/482b5fe2-69f9-11e5-996b-8309751f2b04.png)

**Comment by wmbutler** [comment]
This is a pretty easy win.
