### ISSUE TITLE
Cancel all Orders Button on Exchange (UX enhancement) 

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#275]
![group](https://cloud.githubusercontent.com/assets/6280810/10270822/89cc41b8-6afe-11e5-8c4b-3bcdcb925ac9.png)

**Comment by svk31** [comment]
Not sure this is feasible due to the confirmation transaction dialog, there's no queue of transactions there as far as I know. @jcalfee what do you think, is it possible?

**Comment by valzav** [comment]
I'm closing it for now, we can address this later.
