### ISSUE TITLE
The asset details page crash - Invariant Violation: processUpdates()

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#281]
The asset details page #/asset/XXX produces this error:

--Uncaught Error: Invariant Violation: processUpdates(): Unable to find child 2 of element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like..

How to recreate:
1. Reload the entire app in the browser
2. Navigate to #/explorer/assets
3. Click on any asset

It happens on both Chrome and Firefox (Win 7).
This refers to the online version https://graphene.bitshares.org

**Comment by svk31** [comment]
I've been getting this as well in Chrome Ubuntu 15. It's a really strange bug as something's happening that shouldn't be happening: React is assigning identical data-reactid attributes to every element in the MarketCard component. I'm yet to figure out why, the good thing is it doesn't happen very often and even when it does it doesn't break the GUI, you just need to click a few more times to get into a market.

**Comment by svk31** [comment]
I was able to fix this in the Markets page but I can't quite tell why it's happening in the Asset page. In the markets page it was due to a <Link> component that was wrapping the MarketCard content, fixed by replacing that with an onClick function.

**Comment by svk31** [comment]
I'm fairly certain this was fixed here: ea92a1ef6df81767a56a064856560ffbd9dea7f9

**Comment by wmbutler** [comment]
@neura-sx please confirm and close if you agree.

**Comment by wmbutler** [comment]
Closing after no response form @neura-sx
