### ISSUE TITLE
in Safari wallet backup download button opens new empty window, nothing downloaded

### ISSUE THREAD

**Issue by valzav** [cryptonomex/graphene-ui#282]

**Comment by ghost** [comment]
Yes this issue still persists .

**Comment by valzav** [comment]
https://github.com/eligrey/FileSaver.js/pull/175

**Comment by wmbutler** [comment]
I think we need a bit more dialog on this issue. @valzav was your link a proposal for leaving it as is as a compromise? With everything on the table I'd suggest we push this to December and ask our users to use Chrome and Firefox for now. @arslanmito would you be good with that?

**Comment by wmbutler** [comment]
Closed for now. Can revisit when we focus on Safari compatibility.
