### ISSUE TITLE
Connection interrupted error when app is loaded

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#285]
When the URL https://graphene.bitshares.org is loaded in the browser this error shows up in the console:

--The connection to wss://graphene.bitshares.org/ws/ was interrupted while the page was loading.

Might not be critical as the app continues without further issues. It only happens in Firefox (Win 7).

**Comment by valzav** [comment]
I couldn't replicate this

**Comment by neura-sx** [comment]
Right now my Firefox on Win7 shows the same error as above and a blank screen. Clearing the cache did not help.

![8090-bug](https://cloud.githubusercontent.com/assets/11573977/10396867/08e4c8b8-6ea5-11e5-9bcf-a76e84d21102.png)

**Comment by neura-sx** [comment]
Now I am even more confused. I've tried it on two different machines, both using Win 7 and Firefox v. 41.0.1. The results are different:

First machine: when loading the URL the console shows the error ("The connection to wss://graphene.bitshares.org:8090/ was interrupted while the page was loading") but still loads the app and works fine despite the error.

Second machine: when loading the URL the console shows the same error plus further errors and I get a blank screen: 
![8090-x-bug](https://cloud.githubusercontent.com/assets/11573977/10398936/097d58a2-6eb0-11e5-8fe5-98c1ae7691ae.png)

I've cleared the cache and the Firefox storage folder (C:\Users[user name]\AppData\Roaming\Mozilla\Firefox\Profiles\sv58jek7.default\storage\default - I'm assuming this where the wallet is being stored) but nothing helps - still a blank screen as on the screen-shot above.

If you could advise me what files I need to clear I'll be glad to investigate it further.

**Comment by valzav** [comment]
I have access only to Windows 10 machine - FF 41.0.1 works perfectly.
Could someone else test it in FF on Win7?

**Comment by neura-sx** [comment]
I've posted it on the forum:
https://bitsharestalk.org/index.php/topic,18614.msg242750.html#msg242750

In the meantime could you specify what files I need to delete to completely reset the GUI in the browser? I am a bit confused about the URL behaving differently in the same browser on two different machines so I'd like to make sure both browsers are completely clean.

**Comment by neura-sx** [comment]
Also, please note that when I load 
https://graphene.bitshares.org/
the URL automatically changes to 
https://graphene.bitshares.org/#/init-error

Maybe this will help you guess what's going on.

**Comment by valzav** [comment]
run this commands in the browser’s console:
iDB.root.deleteDatabase(true); iDB.deleteDatabase(true);

> On Oct 9, 2015, at 1:38 PM, neura-sx notifications@github.com wrote:
> 
> Also, please note that when I load 
> https://graphene.bitshares.org/ https://graphene.bitshares.org/
> the URL automatically changes to 
> https://graphene.bitshares.org/#/init-error https://graphene.bitshares.org/#/init-error
> Maybe this will help you guess what's going on.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/cryptonomex/graphene-ui/issues/285#issuecomment-146941742.

## 

Regards,
Val

**Comment by neura-sx** [comment]
Done, didn't help - still the same errors and a blank screen as in the last screen-shot above.

> > iDB.root.deleteDatabase(true);
> > InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
> > deleting graphene_db_ app.js:7:19953
> > iDB.deleteDatabase(true);
> > InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
> > deleting undefined

**Comment by valzav** [comment]
probably this is because of your firewall blocking port 8090, I've updated it to use port 443, please try to refresh the page and see if it helps

**Comment by neura-sx** [comment]
The same situation persists with the port switched to 443. And I am not behind any firewall.
On one machine I get the error but the app still loads, on the other machine I get the error and a blank screen like this:

![8090-443-bug](https://cloud.githubusercontent.com/assets/11573977/10404248/a7db221a-6ed1-11e5-9ad9-6f6dbf78525d.png)

**Comment by neura-sx** [comment]
I've managed to give it a go on a completely different machine located in a different country (it's a remote Windows 2012 server) and the same error pops up in the console (i.e. "The connection to wss://graphene.bitshares.org/ws/ was interrupted while the page was loading.") but the app still loads and works without any further issues. So it might be the case that the error exists but goes unnoticed unless you keep the js console opened. And only on one machine (out of three that I've tried) it ends up with a blank screen.

**Comment by valzav** [comment]
I see you have some more errors after the first one, I think black screen is caused by them. I've seen some strange errors in FF using incognito mode, please make sure it's off in your browser.

**Comment by neura-sx** [comment]
As you can see on the screen-shot, the only extra error is the "Unknown error", coming right after the interrupted connection error. After that there are only errors reported by the logger.
To my best knowledge I am not using anything non-standard in my FF settings and I have Adblock disabled. And never been using the incognito mode.
The GUI used to work on this machine, it started showing this blank screen right after one of the most recent updates.
If you are willing to use the Team Viewer remote access tool I'll be happy to grant you access to this machine so that you can try to debug it here.

**Comment by svk31** [comment]
This is due to the trailing slash in your ws url, it shouldn't be there. You can go to settings and remove it and it should work again.

**Comment by Alok123456** [comment]
Hey, i have been trying to run Graphene-ui app from rock-paper-scissors-devel branch in mozilla on ubuntu 16.04 but it's continuously throwing me on page init-error[http://localhost:8080/#/init-error] even though i have made the flag "network.websocket.extensions.permessage-deflat" as false  in  about:config page .And it's giving me several errors but those errors were in chrome to still it got worked but in mozilla it's not.
Here are some of those errors, so what should i do now, please help me with that your help will be appreciable. 
![screenshot from 2016-11-23 17-01-50](https://cloud.githubusercontent.com/assets/20416373/20560306/a589d3b0-b19e-11e6-945d-37f8d4e93588.png)
![screenshot from 2016-11-23 17-02-13](https://cloud.githubusercontent.com/assets/20416373/20560307/a58de356-b19e-11e6-9b1e-11ad41efaba5.png)

**Comment by svk31** [comment]
I use Firefox without any issues or special flags.

Are you sure that websocket endpoint is actually working? Try with wss://bitshares.openledger.info/ws instead..

**Comment by Alok123456** [comment]
No, i am not at all sure if that websocket enpoint is working or not. So, i used your's but it showing me an error and is not redirecting me to any page which is mentioned in below screenshoot
![screenshot from 2016-11-23 18-01-38](https://cloud.githubusercontent.com/assets/20416373/20562119/064f60da-b1a8-11e6-8275-6f463d854f40.png)

**Comment by Alok123456** [comment]
In chrome i am running the Graphene-ui app with your websocket end point but it's giving me some errors and behaving to get create account but not creating and giving me the error of lost connection.Like below:
![screenshot from 2016-11-23 18-30-59](https://cloud.githubusercontent.com/assets/20416373/20562778/6e1ed56c-b1ab-11e6-9f2e-f09a38cc1565.png)

**Comment by svk31** [comment]
It looks like you might be having some issues with the ws library, it could be caused by conflicting versions in the dl and web folder. Make sure you only have one version of graphenejs-ws installed.
