### ISSUE TITLE
look at/copy foundation's joyride popover implementation

### ISSUE THREAD

**Issue by valzav** [cryptonomex/graphene-ui#302]

**Comment by jcalfee** [comment]
link?  I get lost trying to find a live demo..

**Comment by valzav** [comment]
http://foundation.zurb.com/docs/components/joyride.html http://foundation.zurb.com/docs/components/joyride.html

> On Oct 8, 2015, at 5:00 PM, James Calfee notifications@github.com wrote:
> 
> link? I get lost trying to find a live demo..
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/cryptonomex/graphene-ui/issues/302#issuecomment-146683562.

## 

Regards,
Val

**Comment by valzav** [comment]
or maybe use popup instead http://webrafter.com/opensource/react-foundation-apps/popup ?

**Comment by jcalfee** [comment]
Joyride

**Comment by wmbutler** [comment]
Closing this since it's really not an issue.
