### ISSUE TITLE
UIA issue and display

### ISSUE THREAD

**Issue by juanfranblanco** [cryptonomex/graphene-ui#315]
Trying to issue an UIA (Assets screen), when prompted to enter username to issue the asset, after typing 3 characters (normally) the screen will freeze, and no further input will be possible.

Afterwards the UIA in the Assets screen won't be displayed anymore, refreshing the screen does not solve this.

Chrome.

**Comment by svk31** [comment]
This was fixed a few days ago finally (sorry I totally forgot about it)

**Comment by juanfranblanco** [comment]
Great, no need to apologise
