### ISSUE TITLE
Market search filters not working

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#321]
Market search filters on the https://graphene.bitshares.org/#/markets page has stopped working after the latest update. An attempt to enter search criteria does nothing.

Win 7, Chrome

**Comment by svk31** [comment]
It's not that they stopped working it's only that they've been refactored to work differently (and I forgot to enfore capital letters)

For now we don't have an api call to lookup partial matches of asset symbols, so the searches here have to be exact. It will get replaced by a proper lookup later on that works similar to how the old functionality was (that functionality was unreliable and had to be replaced)
