### ISSUE TITLE
Wrong mouse cursor over BACKUP BRAINKEY RECOMMENDED

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#322]
The mouse cursor over the text BACKUP BRAINKEY RECOMMENDED in the bottom toolbar is wrong. Should be a hand pointer suggesting an action instead of a cursor suggesting an input field.

Win 7, Chrome.

**Comment by jcalfee** [comment]
I don't think it is platform specific.  The change I pushed should fix it though.  Thanks for point this out.
