### ISSUE TITLE
Price level lables on the market depth chart are not clearly visible 

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#324]
These text labels are hardly visible:

![untitled](https://cloud.githubusercontent.com/assets/11573977/10437334/9b9214f2-712c-11e5-977a-770d0b435a08.png)

**Comment by wmbutler** [comment]
Has this been resolved with that commit?

**Comment by svk31** [comment]
I'd say yes, the text is now white so should be visible. There's also just the one line in general, only in markets with active call orders are the other lines shown.

**Comment by wmbutler** [comment]
Closing...thanks.
