### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by pch957** [cryptonomex/graphene-ui#328]
the chinese translation, some error
Fee Rate: it's the price at which USD will get converted to BTS in order to pay fees
Settlement Price: it's feed price

**Comment by AlexChien** [comment]
I will take care of this issue tonight along with other translations.

**Comment by AlexChien** [comment]
It seems that this fee rate is only used when transferring USD (or other assets), will convert 20 BTS transaction fee to transferred asset using this rate.  When placing order, it charges 5 BTS standard fee.  So I will call it 转账手续费汇率。

It's displayed right beside settlement price / margin call price is bit confusing though.

**Comment by AlexChien** [comment]
AlexChien/graphene-ui@56ad52dfc6
