### ISSUE TITLE
Transfer Dialog does not fall back to BTS fee when there is no core exchange rate or funded fee pool

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#329]

**Comment by wmbutler** [comment]
@valzav may need your help getting this bug assigned and worked. It's been around for a while and there don't seem to be any takers.

**Comment by svk31** [comment]
Looks to me like the first part (incorrect core rate) was already handled, I've added a check to make sure the fee pool has sufficient balance, if it doesn't we fall back to fees paid in BTS.
