### ISSUE TITLE
GUI is extremely slow with too many accounts

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#33]
Now I have 1149 accounts (generated from flood_network). The wallet becomes extremely slow and is almost unusable.

**Comment by svk31** [comment]
The wallet will soon transition to the JS wallet architecture which should remove this problem, up until now we've only been using the 15 or so accounts that exist in the genesis block and we have no real logic so far that distinguishes between your own accounts and someone else's account. This means we just lump everything into memory.

I'll keep an eye on performance though but closing this for now as it's not really relevant yet.
