### ISSUE TITLE
Test import of prefixed accounts

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#334]
As reported privately, an exchange had an issue with a prefixed account.  And https://github.com/cryptonomex/graphene/issues/376 may be the same problem.

The GUI needs to try `$ACCT`, `bts-$ACCT`, and `bts-bts-$ACCT`.

**Comment by wmbutler** [comment]
Need a dev to claim this. Moving to 1118

**Comment by wmbutler** [comment]
@theoreticalbts doesn't look like this is is going to get worked. Thoughts?

**Comment by wmbutler** [comment]
Closing since nobody seems to care to respond to this issue :)
