### ISSUE TITLE
Duplicate copy of old witness appears when online during a witness change

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#336]
Two copies of "verbaltech2" appear.

Environment:  Head block #34850 on BitShares main network via bitshares.org/wallet, had the tab open for approximately 3 hours, Firefox on Ubuntu Linux 14.04.

I suspect this bug was triggered by a witness change at 2015-10-14T20:00:00 or so.

Related: #270

**Comment by wmbutler** [comment]
Need some guidance on this. It needs to be claimed if it's a valid bug. @valzav can you assist?

**Comment by svk31** [comment]
I'll have a look but it's a tough one to reproduce which is why it's not been handled yet..
