### ISSUE TITLE
Some buttons lead to a blank page (packaged web bundle)

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene-ui#337]
See:
http://gfycat.com/PaltrySandyBallpython

Clicking "Retry" leads to an empty page in both the electron and the web ui.

Using the bundle created from "npm run-script build" in web/

**Comment by wmbutler** [comment]
@maqifrnswa can you comment on this and let us know if it's still an issue?

**Comment by maqifrnswa** [comment]
fixed!
