### ISSUE TITLE
No Market History in web wallets

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene-ui#339]
I have already made one transaction, and I remember, that it appears in the market history.. right now it is empty. Why is that?

This is strange. People are going to think, that this exchange is not used... and they will be afraid to even try it.

![1jk5kfa](https://cloud.githubusercontent.com/assets/201263/10518103/28c3ea6e-7360-11e5-9eee-94a29ab005bb.png)

**Comment by svk31** [comment]
Unfortunately we still don't have an api call to retrieve market history, see https://github.com/cryptonomex/graphene/issues/47

**Comment by noisy** [comment]
:open_mouth: Guys.. this should be a blocker for the release!  Right now this exchange looks silly!  :confused: How this could even happen, that this was ignored since Jun 14?

**Comment by noisy** [comment]
@svk31 I guess, this ticket can be now closed.
