### ISSUE TITLE
Please release official wallet for linux!

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene-ui#341]
As far as I know, there is unofficial package described here: https://bitsharestalk.org/index.php/topic,18872.msg243541.html#msg243541

But it doesn't work at all. How this even could happen, that there is no official package? I don't want to be forced to use online wallets!

**Comment by maqifrnswa** [comment]
please describe how it doesn't work at all, I've been using both the light wallet and the cli wallet on multiple machines. All work perfectly. What issues are you having?

**Comment by valzav** [comment]
I can confirm that official wallet will be built the same way @maqifrnswa did it. Please be careful with data your directory and create backups often.

**Comment by noisy** [comment]
@maqifrnswa I am refering to my screencast which you have already linked in https://github.com/cryptonomex/graphene-ui/issues/337

![screencast](http://fat.gfycat.com/PaltrySandyBallpython.gif)

Nevertheless, this package should be linked as official together with packages for other systems, all in one place on https://github.com/bitshares/bitshares-2/releases

**Comment by maqifrnswa** [comment]
Got it. If you want something more official, my plan is to get a worker proposal and operate a bitshared repo off of launchpad. I also can get the ppa:bitshares/bitshares name too. If there's any way to help out with distribution, let me know.

Also the white screen bug isn't a bug in the Linux build, it happens on all OSes.

**Comment by valzav** [comment]
@noisy thanks for the screencast - it's really helpful.
I think you have two issues, one - for some reason it couldn't connect to Web Socket api (maybe you have firewall?) and second issue - RETRY button doesn't work in light wallet, I'm fixing it right now.

**Comment by noisy** [comment]
@maqifrnswa:

> Got it. If you want something more official, my plan is to get a worker proposal and operate a bitshared repo off of launchpad. I also can get the ppa:bitshares/bitshares name too. If there's any way to help out with distribution, let me know.

Sounds perfect! :)

**Comment by valzav** [comment]
Official light wallet for Linux is released, find it here
https://github.com/bitshares/bitshares-2/releases/download/v2.15.286/bitshares-light_2.15.288_amd64.deb
@maqifrnswa I will support your ppa maintainer worker proposal.
