### ISSUE TITLE
Illegal account names don't work in the GUI

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#343]
The GUI's valid name check is incorrectly being applied when importing an account.  So names which exist in the genesis, but which would be illegal to register as new names, cannot be imported into the GUI.

User `k3` reported this [here](https://bitsharestalk.org/index.php/topic,19087.new.html)

**Comment by theoreticalbts** [comment]
Update:  testz claims this has already been fixed, just not deployed.  If this is in fact fixed, feel free to close the ticket.

**Comment by valzav** [comment]
I enabled 2 letter accounts yesterday, somebody needs to update bitshares.org http://bitshares.org/ wallet’s files.
BTW should I allow 1 letter accounts as well?

> On Oct 15, 2015, at 2:32 PM, theoreticalbts notifications@github.com wrote:
> 
> Update: testz claims this has already been fixed, just not deployed. If this is in fact fixed, feel free to close the ticket.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/cryptonomex/graphene-ui/issues/343#issuecomment-148482107.

## 

Regards,
Val

**Comment by svk31** [comment]
Looks like there are some founder accounts with only one character so I would say yes.

**Comment by wmbutler** [comment]
@valzav Dropping this into the current sprint as well. I guess it can be closed after 1 letter accounts are allowed?
