### ISSUE TITLE
it is too slow that import wallet from bts1.0to bts2.0

### ISSUE THREAD

**Issue by pureland** [cryptonomex/graphene-ui#345]
I have a bts1.0 wallet include about 50k  keys , I try to export it to bts2.0 , it is too slow !
I also heard some people have  250k keys,  it is too slow make he give up import 
is there many child keys in wallet , and most of keys is useless in bts2.0  since there no balance on these keys , so consider include these keys before import process ?

**Comment by jcalfee** [comment]
I am working on this.   I adding worker threads to support this...   Their
is an open graphene-ui ticket.

**Comment by wmbutler** [comment]
Duplicate #319
