### ISSUE TITLE
Add option to pay fees in BTS if possible

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#356]
On the settings page there should be a "preferred fee paying asset" that defaults to CORE.  

On the transfer page, add selector that allows the user to select which asset type they want to pay the fees in.

**Comment by wmbutler** [comment]
![screen shot 2015-11-05 at 2 42 08 pm](https://cloud.githubusercontent.com/assets/1254810/10979613/6c803e3a-83cb-11e5-9be2-fe06b57a7fbd.png)

**Comment by wmbutler** [comment]
And this is a concept for the payment screen. I think it's nice for the user to always see the fee they pay regardless of the chosen asset. The dropdown would display BTS if CORE is the default and another asset if that the default is something else. The user would not be allowed to change the value in the input field, but the value would dynamically change based upon the asset chosen from the dropdown.

![screen shot 2015-11-05 at 3 04 03 pm](https://cloud.githubusercontent.com/assets/1254810/10980257/0b3da44c-83cf-11e5-8e09-f379f9b342d5.png)

**Comment by wmbutler** [comment]
@svk31 You think this will be worked in this Milestone or pushed to 1125? Seems like your area of expertise.

**Comment by svk31** [comment]
This is @jcalfee's domain really, he's the one behind all the transaction processing. I could have a look but I'm worried I might break something.

There's a related issue here: market trading fees. They're currently paid in whatever asset you're selling, which means a bid in the USD:BTS market has fees in BTS, while an ask has fees in USD. 

Would it be preferable to always pay fees in BTS, or always in USD (or whatever the quote asset is)?

**Comment by wmbutler** [comment]
@jcalfee bumping this to you based upon @svk31 comment above. @bytemaster since you opened this, can you chime in on the fees question above. I expect you have an opinion on this.

**Comment by wmbutler** [comment]
@jcalfee Will you be able to commit to this in 1202 or does it need to get pushed further out?

**Comment by abitmore** [comment]
Wouldn't we'll have the feature "pay by receiver"? It's conflict to this issue.

**Comment by svk31** [comment]
I've added the fees selector, it lets you choose any asset for which you have a positive balance to pay the fees with. Changing the asset type to send will automatically set the fee to be in that asset.
