### ISSUE TITLE
In the block explorer, create a page that shows the current fee schedule.

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#357]

**Comment by wmbutler** [comment]
If I could get some clarity as to what a 'fee schedule' is, I'll start to UX this.

**Comment by svk31** [comment]
It just means a list of what all the current fees are. You can see an example on cryptofresh: http://cryptofresh.com/fees

**Comment by wmbutler** [comment]
Let's have a card in the Explorer tab that links off to Cryptofresh for an easy win and circle back later.

![screen shot 2015-11-23 at 4 05 03 pm](https://cloud.githubusercontent.com/assets/1254810/11349891/b857de3c-91fc-11e5-9c82-4d6fed8125ae.png)

**Comment by svk31** [comment]
Yes I like that. Your icon's OK but since Cass made all the others I'd prefer if he made this one too, to keep them consistent. @cassiopaia ?

**Comment by c055** [comment]
yep will do

**Comment by c055** [comment]
![bildschirmfoto 2015-11-24 um 12 53 02](https://cloud.githubusercontent.com/assets/6280810/11365940/54822f30-92aa-11e5-93f8-db5ff174c278.png)

**Comment by c055** [comment]
top left icon...

**Comment by svk31** [comment]
Works for me!

**Comment by xeroc** [comment]
https://github.com/cryptonomex/graphene-ui/tree/FeeSchedule
