### ISSUE TITLE
Have the wallet save market orientation preferences for every pair

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#358]
1. All FormattedPrice components should default to showing the price in the preferred orientation
2. Toggling the orientation of a formatted price toggles the preference
3. Toggling the market view toggles the preference.

**Comment by wmbutler** [comment]
@bytemaster has a great point here. In general, a user will prefer to view a keypair in the same order regardless of the screen they are on. This is a bit of a refactor and would also address points in #415. I'll consolidate this to that record and close this as a duplicate.
