### ISSUE TITLE
Market Order: The Price should come first

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#361]
http://i.imgur.com/zLmyenB.png

As you can see the screenshot, I tried to order at 0.000016 TRADE.BTC/BTS. But for some reasons, final confirmation box tells me the price is 0.00001599xxx. In this case, order cannot be filled, and users will be annoyed. The price should come first. If I ordered at 0.000016, it should be 0.000016.

**Comment by clayop** [comment]
The decimal bug still exists.

**Comment by svk31** [comment]
I've refactored the prices in the Exchange to use price objects like in the backend, but I'm not comfortable with pushing it live tomorrow without testing so I'd prefer to push this back to the next milestone

**Comment by wmbutler** [comment]
Can you place an overall estimate on this?

**Comment by svk31** [comment]
It's almost done, just a couple hours more on my end to make sure it all works as expected.
