### ISSUE TITLE
Clicking on the charts, gives 1 decimal wrong input to the "Price" field (GUI Exchange)

### ISSUE THREAD

**Issue by liondani** [cryptonomex/graphene-ui#369]
When I want to place a price order clicking on the charts, for example 
251 BTS/USD, I get on the "Price" field" 2510 BTS/USD... the price moves one decimal...
so I must then manually correct the "price" field and move the the separator 1 decimal to the left.

The prices on the charts change there after also....
(same with all markets)

**Comment by svk31** [comment]
Related to https://github.com/cryptonomex/graphene-ui/commit/e323da0c172108fae0ab668bc525d41657e6a280, already fixed in dev

**Comment by liondani** [comment]
on which block will we see this update?
