### ISSUE TITLE
Cannot remove default markets

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#373]
Is it intended? In my opinion, users should have full control on their favorite market list

**Comment by svk31** [comment]
Please be more specific, are the "remove" minus buttons not working for you?

**Comment by clayop** [comment]
No it doesn't work

**Comment by svk31** [comment]
Anyone else able to reproduce this? It works fine for me..

**Comment by clayop** [comment]
FYI, Windows 10 64bit. Both light wallet and web wallet (chrome) do not work.

**Comment by svk31** [comment]
Tested this yesterday in windows 10 64 bit, worked fine in Chrome and IE

**Comment by wmbutler** [comment]
@clayop is this still an issue for you? Sounds like it works for @svk31 Anything you can do to elaborate?

**Comment by clayop** [comment]
After clean install with new version, it works.
But in web wallets, it still remains. (if I create new wallet in incognito mode, removing works) So maybe I need deep refresh.
