### ISSUE TITLE
The cross-hair line on the price history chart jumps unexpectedly

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#375]
https://bitsharestalk.org/index.php/topic,19417.msg249450.html#msg249450

**Comment by neura-sx** [comment]
It's almost fixed now. 

The only problem (a small one indeed) is that when you move the mouse upwards (from the volume section of the chart towards the price section) the horizontal part of the cross-hair line behaves quite randomly: sometimes it shows up just after you enter the price section and sometimes you need to move the mouse much higher to make it show up.

**Comment by wmbutler** [comment]
@neura-sx 

Is this still an issue? If not close. If so, please screenshot or give a very specific example so I can duplicate it.

OS:
Browser:

**Comment by neura-sx** [comment]
Yes, in the 2.0.151119 release the bug is still there.
In both [Chrome / Win 7] and [Firefox / Win 7].

As you can see in those two screen-shots below: when you roll your mouse from the bottom part of the screen upwards there is always a moment when you are close enough to the price history chart so that the horizontal part of the cross-hair shows up. But the problem is it shows up differently for different candles - it seems like there is some random factor deciding about it. Or maybe it's not so random - it seems to be related to a candle's height.

![01](https://cloud.githubusercontent.com/assets/11573977/11331242/4fd2a110-91b8-11e5-9c9a-77759ab1015a.png)
![02](https://cloud.githubusercontent.com/assets/11573977/11331244/52f76600-91b8-11e5-90e5-4c288bd133b2.png)

**Comment by wmbutler** [comment]
I see this. It's just cosmetic. Moving it to mid-December.
