### ISSUE TITLE
The details of mouse-hovering over a price candle are difficult to read

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#379]
https://bitsharestalk.org/index.php/topic,19417.msg249458.html#msg249458

**Comment by neura-sx** [comment]
It's much better now but if you could add a leading 0 for all the figures making up the timestamp, it would be perfect as it would make the number of characters constant and thus not jumping when the mouse is being moved.

e.g. 11/2/2015, 9:00:00 ---> 11/02.2015, 09:00:00

**Comment by wmbutler** [comment]
Seems like an easy number formatting fix.
