### ISSUE TITLE
Referral support

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene-ui#38]
Not sure what this really needs to entail but we need to come up with something if we haven't already. Some combination of integration with faucet, and then a page to track your own referrals or maybe a general referral scoreboard?

**Comment by valzav** [comment]
yes, we have plans for this but not sure this is needed for the alpha

**Comment by vikramrajkumar** [comment]
Sure, moving to beta then. I'm just making my best guesses -- you can move things how you think is best.
