### ISSUE TITLE
The market orders list should have a total column for both currencies

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#381]
https://bitsharestalk.org/index.php/topic,19417.msg249461.html#msg249461

**Comment by wmbutler** [comment]
Is this request satisfied? Please close if so.

![screen shot 2015-11-26 at 10 46 45 am](https://cloud.githubusercontent.com/assets/1254810/11426563/00fc433c-942b-11e5-8c48-c8bd4b4b17c3.png)

**Comment by neura-sx** [comment]
Yes, I think it's satisfying as it is.
You can always flip the market to see the totals expressed in the other currency.
