### ISSUE TITLE
Expose the version number of the current release in the GUI

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#384]
https://bitsharestalk.org/index.php/topic,19417.msg249305.html#msg249305

**Comment by wmbutler** [comment]
This gets my vote, and a quick win.

**Comment by wmbutler** [comment]
Proposed UX

![screen shot 2015-11-05 at 11 15 10 am](https://cloud.githubusercontent.com/assets/1254810/10974114/864de186-83ae-11e5-974b-a117949a447c.png)
