### ISSUE TITLE
The market depth charts should be perfectly symmetrical

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#385]
https://bitsharestalk.org/index.php/topic,19417.msg249638.html#msg249638

**Comment by wmbutler** [comment]
I think this one can be closed.

**Comment by neura-sx** [comment]
This is "nice-to-have" kind of feature but I agree - if it's not easily fixable it should be closed.

**Comment by wmbutler** [comment]
Closing....bigger fish to fry :)
