### ISSUE TITLE
Market Search Page should display top available markets sorted by volume

### ISSUE THREAD

**Issue by ghost** [cryptonomex/graphene-ui#387]
https://bitsharestalk.org/index.php/topic,19417.msg249651.html#msg249651

**Comment by wmbutler** [comment]
Seems reasonable. Adding to 1.0.15.1118 release

**Comment by svk31** [comment]
The reason it's not been done is it's not really feasible atm, unless of course we poll every single market and calculate their volume, but that would be problematic since we're talking hundreds or even thousands of api calls...

**Comment by wmbutler** [comment]
ok, @sharedworld closing since not feasible. Maybe circle back on this at a later date?
