### ISSUE TITLE
My favourite Markets Page should not display "Base Supply" but rather "Total BTS Collateral" 

### ISSUE THREAD

**Issue by ghost** [cryptonomex/graphene-ui#389]
https://bitsharestalk.org/index.php/topic,19417.msg249656.html#msg249656

**Comment by wmbutler** [comment]
This is just a label change. Agree/Disagree?

**Comment by svk31** [comment]
This issue doesn't really make sense to me because: 1. only market pegged assets have collateral backing them, and 2. a market of say usd: btc doesn't need to show anything for BTS.

**Comment by wmbutler** [comment]
Sounds good. I'll close it.
