### ISSUE TITLE
Proposed transactions support

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene-ui#39]
I don't know if we have this already but I think we need it to at least test the Delegate workflow for changing chain rules.

**Comment by jcalfee** [comment]
depends on https://github.com/cryptonomex/graphene/issues/434

**Comment by jcalfee** [comment]
depends: https://github.com/cryptonomex/graphene-ui/issues/472

**Comment by jcalfee** [comment]
depends: #473

**Comment by wmbutler** [comment]
Moving this to 1118 since it's still in the In Progress pipeline.

**Comment by wmbutler** [comment]
@jcalfee will this be moved to 1125 or will it be complete with 1118?

**Comment by wmbutler** [comment]
Closing since there have been no comments or activity in 14 days.
