### ISSUE TITLE
Explorer Blockchain Page should not display "Last Block" but rather "Next Block"

### ISSUE THREAD

**Issue by ghost** [cryptonomex/graphene-ui#391]
https://bitsharestalk.org/index.php/topic,19417.msg249660.html#msg249660

**Comment by wmbutler** [comment]
Rather than changing the label, looks like they are saying x seconds ago. Please close if you agree this is resolved @sharedworld

**Comment by svk31** [comment]
Yea we can't really say "Next block" because we don't know when that will be. Only thing we can be sure of is that the last block received was x seconds ago.
