### ISSUE TITLE
"View All" Button in orderbook

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#396]
Some traders want to see all market orders. View all button will be great option for them. (example: poloniex)

**Comment by wmbutler** [comment]
@clayop I'm not clear on this. Maybe a screenshot would help me.

**Comment by clayop** [comment]
![image](https://cloud.githubusercontent.com/assets/9971632/10983908/8f6fa378-83ca-11e5-99c6-a56b10fc7258.png)

**Comment by wmbutler** [comment]
Got it. I'll push this to the December Milestone. Thanks!

**Comment by svk31** [comment]
This was actually added in the last release, didn't find this issue though when I made the commit. https://github.com/cryptonomex/graphene-ui/commit/3841bc396e918cd275bb3aff8dfe3d2837a86c8a
