### ISSUE TITLE
Trollbox is missing, and is a requirement for the exchange to flourish. 

### ISSUE THREAD

**Issue by luckybit2014** [cryptonomex/graphene-ui#405]
Information exchange is critical to the success of the Graphene UI because it increases stickiness. To increase stickiness we need a troll box.

The initial troll box can be based on IRC. It should have the capability to keep logs as an archive. It should be open source and capable of being decentralized later. The archive is important because it allows speculators to establish reputations, example would be Fontas who is someone most Bitcoin traders have heard about.

http://trollboxarchive.com/

Models which can be used as mockup examples include BTC-E:

https://i.imgur.com/DkhqtEU.png

Notice in the BTC-E mockup the troll box is always visible during trading. This is essential because people exchange information in real time during the speculating process. In order to maximize stickiness the interface should always display certain information and the troll box must always be visible unless they decide to collapse it.

Example 2 (Mcxnow):
https://mcxpump.files.wordpress.com/2013/09/mcxfee.png?w=705&h=527

In the Mcxnow example you also see a troll box which also has prominent real estate and always open on screen. Mcxnow was one of the most popular and successful exchanges of it's time and just by examining the interface you can see that the troll box was a critical element of their design.

Implementing the troll box will allow Graphene exchanges to be seen as "real exchanges" and not just Bitshares 2.0 wallets.

**Comment by jcalfee** [comment]
For added security a plug-in like this should support a local library the exchange can save on the server and communicate via CORS requests.  This prevents the trollbox from automatically upgrading itself, that needs to be done manually so a code review can take place.

**Comment by decentral-exchange** [comment]
How about using https://kiwiirc.com/ .. its a Javascript implementation of an IRC client ..

However, it requires a nodeJS server to handle the IRC protocol :(

**Comment by xeroc** [comment]
@decentral-exchange 
I don't think that's a problem .. let bitshares.org and/or bitshares.eu host the nodejs "gateway" so to speak ..

**Comment by valzav** [comment]
I think we need to post messages on BitShares blockchain - no need to use external services.
So what is needed is ability to post arbitrary messages to account's feed using custom ops.
Anybody who is following an account will see those messages. For the trollbox we just need to filter messages with specific hashtag, e.g. for USD/BTS market it would be #usd_bts.

**Comment by jcalfee** [comment]
@valzav DL is planning a key value operation now.  You might mention this tomorrow morn when you see him.

**Comment by luckybit2014** [comment]
Posting messages directly on the blockchain would lead to blockchain bloat. The messages would have to be small.

On the other hand you can put the hashes on the blockchain and treat it like a DHT. There is also the Bitmssage way of doing things. What are the capabilities we gain that favor the Bitshares blockchain vs external gateways?

@jcalfee When you mentioned "key value operation" do you mean its mean storing hash values? But if you use the method @valzav mentioned it sounds a bit more like Twitter than IRC.

**Comment by noisy** [comment]
In my opinion, storing messages in the blockchain over complicate a lot of things. [Minimum viable product](https://en.wikipedia.org/wiki/Minimum_viable_product) first! So, lets add simple trollbox to the webwallet, based on single server as backend, and lets check what people thinks about that.

This will give bitshares users a business value with with minimal development effort.

**Comment by jonnybitcoin** [comment]
yes please just add a simple trollbox asap. irc is fine and it must display on the trading page. This is a free form of customer service for us all.

**Comment by wmbutler** [comment]
Seems like trying to build the whole trollbox on the blockchain is admirable but maybe trying to do too much at once. What if we just api into an existing infrastructure for the first iteration, otherwise, waiting until some other items are in place and putting this in mid-January.

**Comment by svk31** [comment]
Trollbox finally implemented here: https://github.com/cryptonomex/graphene-ui/commit/6611f81ab2ee29dcbb7f0e1de19f5211bd933ffe

Protocol used is WebRTC so it's a peer 2 peer messaging system, with a central server only used for peer discovery.
