### ISSUE TITLE
Receiver of Asset Issuance does not show up in Recent Activity

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#408]
For example,

"Was issued 1,000 OPENLTC by openledger-wallet      22 minutes ago"
-> openledger-wallet was issued 1,000 OPENLTC by openledger-wallet

**Comment by svk31** [comment]
I actually noticed this too and fixed it in a commit yesterday

**Comment by svk31** [comment]
e570c1da40de363ec2934ad8537df16b395236ef
