### ISSUE TITLE
[Account Overview] - Recent acitivity bug?

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#409]
![bugreport-screen](https://cloud.githubusercontent.com/assets/6280810/10814447/6200b53e-7e26-11e5-8b8a-19424160d918.png)

**Comment by svk31** [comment]
Is this on Openledger? If so I fixed this yesterday, it's an unsupported operation type, most likely a blinded transfer.

**Comment by c055** [comment]
yep . ok so then pls feel free to close directly ;D

**Comment by svk31** [comment]
They're actually "transfer_from_blinded" type operations, I had only seen "transfer_to_blinded" yesterday, will add support for this as well.

![image](https://cloud.githubusercontent.com/assets/6890015/10814572/105fcbb0-7e27-11e5-85b6-1e7220ef1713.png)

**Comment by svk31** [comment]
Fixed by c849240e17fbdff3aba9729a23111f476f5cf77b
