### ISSUE TITLE
Buggy price display on market page

### ISSUE THREAD

**Issue by dnotestein** [cryptonomex/graphene-ui#411]
For some reason it's showing some strange price for BTC:TRADE.BTC market pricing shown on lower right corner of webwallet. Particularly strange is the units are wrong also. See attached picture below (red circle)
![price_display_bug](https://cloud.githubusercontent.com/assets/5102968/10827994/61515aea-7e48-11e5-9d5e-c2ca104b5548.png)

**Comment by svk31** [comment]
Yea I've noticed this too, I just looked into it and the reason for it is that the core_exchange_rate for TRADE.BTC is defined in the opposite direction to all the other assets. TRADE.BTC has base 1.3.0, BTC and the rest have quote 1.3.0.

I guess I should code a more generic conversion method that will take into account this kind of stuff but it's a bit involved so it'll have to wait a bit. You could fix it on your end by inverting your core_exchange_rate however.

**Comment by dnotestein** [comment]
I really think these needs to be fixed (and reasonably soon), because it's likely to keep happening. Also, I'm wondering if it's related to strange "equivalent-values" being printed on user account pages (Ronny from ccedk reported a problem about it to me today).

**Comment by svk31** [comment]
Fixed by 13b19e464714995a0eb8f408344aecdb5c24125a
