### ISSUE TITLE
[UX] - Account RA - Change all Asset pairs within same cat on click ! 

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#415]
![bildschirmfoto 2015-11-01 um 11 51 18](https://cloud.githubusercontent.com/assets/6280810/10868444/e12a3a0a-808e-11e5-9486-636c363f5c01.png)

**Comment by wmbutler** [comment]
Also from bytmaster on issue #358
1. All FormattedPrice components should default to showing the price in the preferred orientation
2. Toggling the orientation of a formatted price toggles the preference
3. Toggling the market view toggles the preference.

**Comment by wmbutler** [comment]
Now, the question becomes can we reasonably allow a  user to set their preferred order per trading pair. Do we just make that passive so we remember their preference across all screens once they have selected it on one screen? Seems like the easiest way.

**Comment by c055** [comment]
https://github.com/cryptonomex/graphene-ui/issues/415#issuecomment-159932192

+1
