### ISSUE TITLE
[UX] - Exchange - MyFavMarket Section - Complete Row to be functional as button 

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#416]
![bildschirmfoto 2015-11-01 um 12 37 15](https://cloud.githubusercontent.com/assets/6280810/10868676/785519ee-8095-11e5-8e45-0ad0b53ee402.png)

**Comment by c055** [comment]
then we could get rid of all buttons there entirely …and also it would be nice if row would be highlighted .. as on buy/sells table...

**Comment by noisy** [comment]
> Make row instead clickable

@cassiopaia but then you will use a possibility of clicking "CNY/BTC" to change an currency orientation.

**Comment by c055** [comment]
yep was thinking same as welll - will think more about ..

**Comment by wmbutler** [comment]
Would you mind closing this and re-opening once you have a reformulated the idea @cassiopaia ?

**Comment by svk31** [comment]
Closing since it's been refactored and the row is clickable now anyway.

**Comment by wmbutler** [comment]
Also, highlighting active row was already added and will be release with 1125
