### ISSUE TITLE
[UX] - Account > Permissions  - Enhancement ...Permission settings history like on transfer page

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#418]
![Account > Permissions](https://cloud.githubusercontent.com/assets/6280810/10869871/8042df02-80bc-11e5-8da7-ac2bde81c516.png)

**Comment by c055** [comment]
would this make sense?

**Comment by svk31** [comment]
Kind of, but the operation performed here is an account_update, for which we don't have much of a text really (it just says the account was updated). I could certainly add the history though, and we could work on improving the text from Operation.jsx later on

**Comment by wmbutler** [comment]
Added this to the December Milestone.
