### ISSUE TITLE
"Read more" link doesn't work in BorrowModal

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene-ui#419]
"Read more" link doesn't work on:

Exchange

![419_exchange](https://cloud.githubusercontent.com/assets/201263/10872289/fb5e2c68-80fe-11e5-8d25-023c762358b8.png)
and on Collateral Position:

![419_collateral_position](https://cloud.githubusercontent.com/assets/201263/10872292/08317ad0-80ff-11e5-9192-10def1ed2b5d.png)

**Comment by svk31** [comment]
fixed by 148c7afe1d36b2d2452a410fee19ed8ff7ca9f8a
