### ISSUE TITLE
build fail on windows

### ISSUE THREAD

**Issue by cgafeng** [cryptonomex/graphene-ui#42]
I build the ui success on ubuntu and mac, fail on win7x64, any idea?

```
[694] ./app/assets/fonts/Roboto-Bold.eot 0 bytes [optional] [built] [failed]
[696] ./app/assets/fonts/Roboto-Bold.ttf 0 bytes [optional] [built] [failed]
[697] ./app/assets/fonts/Roboto-Bold.woff 0 bytes [optional] [built] [failed]
......
......
WARNING in ./app/assets/fonts/Roboto-Bold.eot
Module parse failed: I:\private\code\graphene-ui\web\app\assets\fonts\Roboto-Bold.eot Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./app/assets/fonts ^\.\/.*$
```

**Comment by svk31** [comment]
Looks to me like you're missing a webpack loader, did you do "npm install" in the web directory before building?

**Comment by cgafeng** [comment]
yes, i run "npm install", and sure the file-loader is install.
I build and run success on ubuntu and mac, so i don't think i miss some step.

**Comment by valzav** [comment]
Maybe regexp in web/webpack.config.json, line 36 doesn't work on Windows, try to alter it and see if it affects the error message.

**Comment by ChronosCrypto** [comment]
@cgafeng Is this still an issue? The Windows build has changed significantly since July 7.

**Comment by cgafeng** [comment]
It's ok now.
