### ISSUE TITLE
Webpage link should be clickable on worker approval card, and worker card should have normal cursor on hover

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene-ui#421]
![enchantedflusteredconey](https://cloud.githubusercontent.com/assets/201263/10872813/2b9ce576-810a-11e5-9a4d-c1b56973d650.gif)

**Comment by c055** [comment]
mh - i'm thinking of .. if linking directly out of the wallet is really a good idea .. if .. we should highlight them as external links..so user knows he is leaving the wallet... like a redirect ala blockchain.info ..

**Comment by noisy** [comment]
@cassiopaia user will know for sure that he is leaving a wallet because I used `target="_blank"` in [proposed fix](https://github.com/cryptonomex/graphene-ui/pull/422), which mean, that link will be opened in new tab.

**Comment by wmbutler** [comment]
This looks complete to me. @cassiopaia will you please close it if you agree?

**Comment by noisy** [comment]
@wmbutler it is already merged: https://github.com/cryptonomex/graphene-ui/pull/422

**Comment by c055** [comment]
sure but they should get a big warning as well IMO
