### ISSUE TITLE
Improve the BACKUP REQUIRED alert...

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#426]
Like a nice animated tool-tip that points to the footer where it says BACKUP REQUIRED?

svk [8:28 AM]
haha yea that would be cool

svk [8:28 AM]
a bouncing arrow

svk [8:28 AM]
using react-motion :simple_smile:

**Comment by jcalfee** [comment]
https://github.com/wwayne/react-tooltip/issues/47

**Comment by wmbutler** [comment]
This looks complete close? @jcalfee

**Comment by jcalfee** [comment]
Yes, it is complete, thanks.  I have more ideas here but the new wallet backup proposal by DL is going to be the focus now..
