### ISSUE TITLE
Market Feature: Include Fee button

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#427]
https://bitsharestalk.org/index.php/topic,19687.msg252750.html#msg252750

In general, exchanges include trading fees in people's order. However, since some prefer fee inclusion and others not, we'd better have "Include Fee" button on the market page.

**Comment by wmbutler** [comment]
Not sure I'm totally clear on this. If I say I want to spend $100 on a trade to buy 5 shares at $20 per share, I'm not factoring my fees into that. I expect to have fees deducted from whatever I have in my account.

I'd think that a nice summary with a lineitem for the fee would be the best way to handle it. Am I misinterpreting your proposal?

**Comment by clayop** [comment]
What I want to is including all fees in orders, as done by all other exchanges.
See the poloniex example:
![image](https://cloud.githubusercontent.com/assets/9971632/10987027/2ecf09cc-83e4-11e5-951e-38bf5d0739e2.png)
In this example, a user will get 99800 BTS

We have two types of fees-market fee(for each UIA) and trading fee(10 BTS equivalent). The former is included in order already, as like poloniex example. But what makes people annoyed is the trading fee.

If I have 1 BTC and want to buy 100k BTS at 0.00001 BTC/BTS. If I put 1 BTC in my order box, I cannot execute my order because I don't have additional 0.0001 trading fee in my account. So I have to run calculator and deduct 0.0001 from 1 BTC. To avoid this thing, the trading fee should be automatically included in the order.

So, 
1) Placing 1 BTC order at 0.00001 BTC/BTS
2) Converted to 0.9999 BTC order at 0.00001 BTC/BTS (trading fee deduction)
3) Get 99990 \* 0.998 = 99790.02 BTS (market fee deduction)

**Comment by wmbutler** [comment]
#469 has UX for fees included.
