### ISSUE TITLE
The Decimal Bug Still Exists

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#434]
http://imgur.com/NBq9pv8.png
![image](https://cloud.githubusercontent.com/assets/9971632/10926225/d8fee6ca-8249-11e5-8c79-68e593269a0a.png)

274.2892291748562 vs. 274.2892288825665

Order is not filled

**Comment by bytemaster** [comment]
This is caused by GUI issues.  The blockchain is perfectly precise in its comparison of orders.

**Comment by wmbutler** [comment]
Bumping this to high priority for next release if possible. These are confidence killing issues.

**Comment by cgafeng** [comment]
+1

**Comment by wmbutler** [comment]
@svk31 maybe you can knock this one out at the same time #469 Seems similar.

**Comment by svk31** [comment]
See #361, I prefer to push this to the next milestone

**Comment by wmbutler** [comment]
Pushed to 1118
