### ISSUE TITLE
Switching users while in a market does not update BORROW USD values

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#435]
Reproduce:
- Navigate to USD:BTS Exchange
- Choose account A from dropdown at top
- Borrow some USD and set collateral and save
- Close the "borrow USD" modal
- Switch to account B form dropdown at top
- Open "Borrow USD" modal (you will see the same values as those on account A)

Thanks for looking into this.

**Comment by svk31** [comment]
My commit should fix this but I can't test because the dropdown is broken for some reason on my machine.

**Comment by svk31** [comment]
This has introduced a new bug it seems but I'll track that in a different issue.

**Comment by wmbutler** [comment]
Happy to book this bug for you if you like. Let me know.
