### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#436]
@valzav I'd like to help if you are interested. My skillsets include:
- Managing milestones
- Prioritizing issues
- Working with ZenHub to bring pipelines and order to github issues
- UX mockups

I am comfortable with long distance collaboration. I use screenhero and slack for quick screenshares/chat to get in sync with remote volunteers. I'm interested and motivated to make time for this if you are in a position to let me help.

**Comment by valzav** [comment]
@wmbutler, yes this would be absolutely great to have you helping us to maintain this repo and maybe graphene toolkit's one and play a release manager role. I can send you invitation to dev slack channel to discuss more details.
