### ISSUE TITLE
Hide the prefix of a asset, if you trust one account 

### ISSUE THREAD

**Issue by pureland** [cryptonomex/graphene-ui#438]
Hide the prefix of a asset, if you trust one account 
I notice add many asset like opendash, but it is ugly show the asset "opendash" in wallet.
can we set if trust the account of asset issuer , then can hide prefix of a asset .
eg , I trust openlegder that can been set in wallet config , then the opendash asset is show as dash in my wallet.

**Comment by pureland** [comment]
more asset can include a parameter that mean what is prefix , when it is registered

**Comment by svk31** [comment]
Don't think we'll do this, it could mean having multiple BTC in your account for example with no way of telling them apart.

**Comment by wmbutler** [comment]
Agreed. This is probably a bad idea for all kinds of reasons.
