### ISSUE TITLE
[UX] - Exchange - Account chevron dropdown - filtered to owned Accounts

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#439]
Currently all starred/favorite Accounts are listed at the exchange ACC drop down .. 

![exchange - drop down](https://cloud.githubusercontent.com/assets/6280810/10937597/26544aa0-82f4-11e5-93dd-e9895717b9ec.png)

But let's say i've starred approx. 40 accounts .. then the complete dropdown is useless.. as it won'T scroll to bottom listed accounts then .. IMO it would make much more sense .. if just my own listed accounts would get filtered by the dropdown.

Thoughts?

**Comment by c055** [comment]
or at least the drop down should be scrollable as well

**Comment by c055** [comment]
another idea would be maybe also nice .. i will post a screenshot ASAP

**Comment by c055** [comment]
![bildschirmfoto 2015-11-04 um 12 53 33 rectangle 1 bildschirmfoto 2015-11-04 um 13 07 01](https://cloud.githubusercontent.com/assets/6280810/10937735/46208794-82f5-11e5-948c-614ef65a4bbb.png)

**Comment by wmbutler** [comment]
We might consider having stars (favorites) on the account dashboard and only displaying starred accounts in the dropdown.

![screen shot 2015-11-05 at 10 47 44 am](https://cloud.githubusercontent.com/assets/1254810/10973294/c886c5b2-83aa-11e5-82b2-a4a8b9edd924.png)

**Comment by c055** [comment]
yep or an heart .. anyway .. yep i would like that :)

**Comment by wmbutler** [comment]
Pushing this to 2.0.151118 since we added several bugs with higher priority to the upcoming release.

**Comment by wmbutler** [comment]
Probably a simpler solution. I think I misunderstood the intent of the original request.
