### ISSUE TITLE
can not cancel proxy voting account 

### ISSUE THREAD

**Issue by pureland** [cryptonomex/graphene-ui#440]
can not cancel proxy voting account

**Comment by wmbutler** [comment]
Maybe something like this with a circle-x to the right of the assigned proxy?

![screen shot 2015-11-05 at 8 40 53 pm](https://cloud.githubusercontent.com/assets/1254810/10987063/941c1d1a-83fd-11e5-838d-01fe48be33c3.png)

**Comment by svk31** [comment]
I already fixed this here: 13681d1474c18ede3efd40095103289e6c3252d7
