### ISSUE TITLE
Cannot Update Asset

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#441]
Error message:
base.asset_id != quote.asset_id:

I guess BTS/BTS (cannot choose my asset) is the cause.

**Comment by wmbutler** [comment]
Can you elaborate? Screenshot?

**Comment by clayop** [comment]
![image](https://cloud.githubusercontent.com/assets/9971632/10987217/14f3cfa4-83e6-11e5-9bfa-cca8af51d623.png)

Cannot change BTS to my asset name

**Comment by svk31** [comment]
I can handle this, although I think there might also be an issue in the operation construction code that sets the quote and base id to 1.3.0, one of the two really should be set to the id of the newly created asset. @clayop did you create this asset using the GUI?

**Comment by clayop** [comment]
It is an existing asset from 0.9.3

**Comment by svk31** [comment]
I think this is important so if you don't mind I'd like to put this in the pipeline for the next release @wmbutler
