### ISSUE TITLE
Warn user when switching to any connection other than wss://bitshares.openledger.info/ws

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#444]
This isn't the perfect solution but it's quick and will probably save some headache if we get it out sooner rather than later.

"You must be running a local node in order to use this feature. If you aren't running a local node, your wallet will be inaccessible when you return to the browser. Only select this if you know what you are doing."

Reason: if a user switches their connection in Chrome, their wallet is no longer accessible until the edit:

__openlegder_defaults.connection

**Comment by valzav** [comment]
I just removed localhost option, it's not a full solution but still an improvement.

**Comment by wmbutler** [comment]
Excellent.
