### ISSUE TITLE
Showing Deposit/Withdraw Fees

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#449]
Gateways may have deposit/withdraw fees, but the amount(or rate) is hidden in the GUI.
So, make another column "FEE" in between DEPOSIT TO and BALANCE, and show the fees there.

**Comment by noisy** [comment]
plus add another column with current spread of BTC.SOMETHING:BTC exchange

**Comment by wmbutler** [comment]
I'm thinking we can close this if we agree to adopt this concept #465. Thoughts?

**Comment by clayop** [comment]
Agreed. Thanks.
