### ISSUE TITLE
Asset select menu on Transfer page shows USD when balance is 0.

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#452]
I Transferred all of my USD to another account. Then, I wanted to do the same thing with the EUR. So, I went back to the Transfer screen, clicked on the asset select menu, and the USD was still an option in that menu even though I emptied it already.

**Comment by wmbutler** [comment]
Another high priority bug IMO. Inconsistencies like these hurt confidence. Adding to current Milestone.
