### ISSUE TITLE
We need a "Back" button

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#453]
As I am drilling down into different screens, I need an easy way to get back to the sub-screen that I was just on. So, we need browser-style forward and back buttons please.

**Comment by wmbutler** [comment]
If you are using a web browser, you can use the browser back buttons, but agreed this needs to be a standard part of the UI.

**Comment by kenCode-de** [comment]
Sorry, I should have mentioned that, I use the Linux Light Client.

**Comment by clayop** [comment]
+1 Many friends of mine asked it too.

**Comment by wmbutler** [comment]
Most browsers put these in the upper left corner so let's keep convention

![screen shot 2015-11-21 at 8 29 02 pm](https://cloud.githubusercontent.com/assets/1254810/11321467/97bf773a-908e-11e5-8b5c-ebeb7c9a72cd.png)
![screen shot 2015-11-21 at 8 28 54 pm](https://cloud.githubusercontent.com/assets/1254810/11321468/97c106c2-908e-11e5-9cd4-b6aa4a88abcb.png)

**Comment by wmbutler** [comment]
These are fontawesome arrows and I shifted the header menus over to accommodate them.

![screen shot 2015-11-21 at 8 53 01 pm](https://cloud.githubusercontent.com/assets/1254810/11321538/07d9bd7a-9092-11e5-815e-3b6010cd7bc0.png)

**Comment by svk31** [comment]
Should these be visible for light clients and hosted wallets?

**Comment by wmbutler** [comment]
Yes. It wouldn't be terrible for them to be on the web stuff as well. Might be easier and they could perform the same function as the back and forward buttons built into the browser. Your call though.

**Comment by svk31** [comment]
Yep definitely easier so if that's ok I'll just add them without any logic for turning them off.

**Comment by wmbutler** [comment]
Would be great if you could give them a hover state as well.

**Comment by kenCode-de** [comment]
Looks-wise, they should match all the other buttons in the ui like the Generate buttons you see in the Deposit/Withdraw screen. Mouseover effects should be subtle.

**Comment by wmbutler** [comment]
So, more like this? Uglier but consistent :)

![screen shot 2015-11-23 at 11 39 53 am](https://cloud.githubusercontent.com/assets/1254810/11342762/f123b8ce-91d6-11e5-9313-81ca4edec922.png)

**Comment by svk31** [comment]
Yea I prefer the first one tbh

**Comment by kenCode-de** [comment]
I love it, hover makes the light gray go to the same shade of white as the word Dashboard, or vise versa effect. No fill necessary.

**Comment by kenCode-de** [comment]
They could be a tad smaller..

**Comment by svk31** [comment]
It is more consistent though as you say so I'll go with that

**Comment by svk31** [comment]
I've spent far too much time getting this right in terms of alignment etc so I don't wanna spend even more time getting the size right, I'm sure someone more css savy than me can get right... The functionality is there though.

![image](https://cloud.githubusercontent.com/assets/6890015/11344188/0ffbf8b8-9210-11e5-93d9-3a0cc23f72ad.png)

**Comment by wmbutler** [comment]
It's fine. It's not technically a bug so leave it as is.

**Comment by kenCode-de** [comment]
I'm still in love with it, thanx for adding it! :)

**Comment by valzav** [comment]
I think back and forward buttons need to be shown only in light wallets, in a browser they just duplicate browser's buttons. What do you think?

**Comment by wmbutler** [comment]
Well, in the interest of time, I don't see the harm in displaying them in the web as well. But feel free to make the call.

**Comment by kenCode-de** [comment]
When it comes to supporting a customer with Technical Support, the Rep must be able to assume a consistent interface when speaking with the customer over the phone. For example, the Rep will say (do you see the left and right arrow buttons in the top right corner next to the word Dashboard? 

If each wallet version starts looking different, light wallets vs web wallets etc, it will make Tech Support a real nightmare over time. Consistency is very important IMO.

**Comment by wmbutler** [comment]
I'm fine with the duplicated controls.
