### ISSUE TITLE
Need ability to "Send it all" or "Spend it all" easily

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#454]
In the Transfer screen fill out the From and To fields, then, select which Asset you want to send. When the asset is selected in the select menu, it displays the balance of that asset just above the select menu. 

The Trade buy/sell screen does the same thing. 

Allow me to click on the balance remaining (Trade screens allows this already) so that I can easily empty the account. Fees must be automatically deducted, or, popup a dialog box that asks me if I want to Send it all (Transfer screen), or Spend it all (Trade screen).

**Comment by clayop** [comment]
Related to this?
https://github.com/cryptonomex/graphene-ui/issues/427

IMO, fees are automatically included in trading, and deposit/withdraw. But we should give options to users in transfer (with including fee button)
