### ISSUE TITLE
Need ability to click on the Block number

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#455]
I want to easily prove to someone that I paid their bill. 

I open the light client, I find that transaction and click on it. It shows me the block number at the top of the screen. 

I would like to be able to click on that block number so that it loads up the block explorer (so I can email the link to my creditor), ie: 
http://cryptofresh.com/b/677376

**Comment by svk31** [comment]
Not sure I get what you want here. You want a link from the internal block explorer to an external one link cryptofresh?

**Comment by kenCode-de** [comment]
yes please. this way it will open the users default browser with cryptofresh displaying that blocks info. makes it easier to send a URL to someone as proof that you paid them or vice versa.

**Comment by wmbutler** [comment]
@svk31 This is on a later milestone. Don't sweat this for a couple of weeks.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#20
