### ISSUE TITLE
When claiming from many small balanceid, the transaction times out

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene-ui#456]
To prevent that, I would recommend to put the expiration time in the transaction only after the (unsigned) transaction is finalized

**Comment by wmbutler** [comment]
This needs to be claimed and worked by someone. @valzav thoughts? Moving to 1118

**Comment by svk31** [comment]
@jcalfee is best equipped to handle this.

**Comment by jcalfee** [comment]
jcalfee
I increase the expiration time for about 1 sec per signature.
Also, I group balance claims in groups of 60 ..
so the trx does not become too large..

jcalfee [1:14 PM] 
So did you have the issue more than maybe 2 weeks ago?

xeroc [1:14 PM] 
i'd say so .. yes

**Comment by wmbutler** [comment]
@jcalfee I assigned this to you as well. If you are able to get into the groove, please claim items you are working on. Thanks.

**Comment by xeroc** [comment]
Another case:
https://bitsharestalk.org/index.php?topic=20081.msg255901;topicseen#new

**Comment by wmbutler** [comment]
@jcalfee Can you squeeze this edge case in before the Milestone ends?

**Comment by xeroc** [comment]
@wmbutler: James talked to me about this already and he had it fixed .. I think the case above may have another reason that needs investigation first .. wouldn't count on this being fixed today already as we need input first

**Comment by wmbutler** [comment]
ok, so I'll push it again, close it if you think it enough of an edge case to not worry about it.

**Comment by wmbutler** [comment]
Closing due to no feedback for many months.
