### ISSUE TITLE
Buy/Sell BTS

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#457]
The idea here is to create a dead simple, one stop process for assisting users with acquiring BTS from their BTC wherever they may have it stored. Making it easy for people to acquire BTS is critical and although technically it can be done with the existing wallet, is needs to be easier. Coinbase handles this function for millions of people and it's a pretty smooth process.

**Comment by wmbutler** [comment]
![screen shot 2015-11-06 at 12 04 20 pm](https://cloud.githubusercontent.com/assets/1254810/11003076/8b71de08-847e-11e5-9b56-f0618690a147.png)

**Comment by c055** [comment]
![screen1](https://cloud.githubusercontent.com/assets/6280810/11005095/2fe2807c-84bc-11e5-946d-d095fb21e2e8.png)

**Comment by c055** [comment]
if we develop this as own component, we would be able to use it as well — let’s say for example — user register a new account - first time user … then after register

he would get a modal with this BTC > Buy — and at bottom .. a checkbox ..
where he is able to remove this modal each time when he logs in .. opt-out

**Comment by clayop** [comment]
Great idea. Just don't forget include all fees in the final statement. (So it should be 0.9813 BTC)

**Comment by wmbutler** [comment]
Absolutely. We will UX/UI this out here.

**Comment by wmbutler** [comment]
Will do. Personally, I'd prefer to handle the gateway / deposit in an altogether different way. I'd like to propose a design for this in the next day or two. Maybe it'll make more sense after I post it. The basic gist is that our end users should be able to bring in funds natively or convert them while bringing them in and this should be a single operation that is clearly explained so users understand what they are doing.

**Comment by wmbutler** [comment]
Deposit/Withdraw was UX'd as issue #465. Renaming this this to Buy/Sell BTS

**Comment by wmbutler** [comment]
OK, here is an initial proposal for Buy / Sell BTS. This has a lot of moving parts but I think it could be a solid revenue generator. Essentially, what's happening with this is that, much like Coinbase, we would be removing the confusion of the trading platform for people who just want to acquire BTS. The fees are higher, but it's because we can essentially guarantee the trade. This will work equally well on both the buy and sell side. So explaining this fully:

AMOUNT is essentially a block of three values that display according to whatever changes are made in each box. Their value is constrained to one another. If I type 700 for USD, we would run calculations based upon the markets to display comparable values for BTC and BTS. All 3 fields are editable in real time per keystroke.

PAYMENT METHOD allows the end user to choose where they are going to extract funds from to facilitate the buy order. We should limit this to BTC related accounts at first, but it could easily get expanded to LTC, DOGE, etc.

FEE and TOTAL are calculated and the user cannot alter them.

All FIAT values displayed (USD in the UX) would be set in a user prefs somewhere else. As a US customer, I generally want to understand the magnitude of my buy/sell but looking at it in terms of my local FIAT.

**Comment by wmbutler** [comment]
![screen shot 2015-11-08 at 12 13 50 am](https://cloud.githubusercontent.com/assets/1254810/11018916/a0751844-85ad-11e5-93fa-184477e1edda.png)

**Comment by clayop** [comment]
+1
Is "59,400 BTS (USD 693.00)" correct?

**Comment by wmbutler** [comment]
Yes. updated.

**Comment by valzav** [comment]
A agree that Deposit/Withdraw can be improved and made more user friendly, but why BTS needs a dedicated buy/sell section?  Not much users care about BTS or even know it exists.

**Comment by wmbutler** [comment]
I don't understand your statement. "Not much users care about BTS or even know it exists."

BTS is the underlying asset that drives everything we are working on. An investment in BTS is implicitly an investment in the foundation of the Bitshares ecosystem. I would expect that creating an effortless way for people to acquire BTS within the web wallet would be the single greatest priority. If it's not, then I have fundamentally missed the point of BTS somewhere along the line.

@bytemaster thoughts?

**Comment by wmbutler** [comment]
https://github.com/cryptonomex/graphene/issues/450

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#21
