### ISSUE TITLE
Market List Arrangement: Several options

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#458]
Users want to customize market lists. So here are options.
1. Sort by volume, when clicking volume column
2. Sort by 24h change, when clicking 24h change column
3. Sort manually, when clicking "customize" button: users can arrange market list order

**Comment by c055** [comment]
Explorer > Markets (old trade intro page) ? 

Or do you mean issue referenced here ? https://github.com/cryptonomex/graphene-ui/issues/448#issuecomment-154348640

**Comment by clayop** [comment]
Similar. In addition to that, users can sort their favorite markets

**Comment by c055** [comment]
yep just by clicking on the Table TH Titles ..

**Comment by clayop** [comment]
Can they drag market names and make their own lists?

**Comment by c055** [comment]
possible but not that easy to implement AFAIK .. @valzav ? idk if something in this direction is on the list .. 

http://gaearon.github.io/react-dnd/examples-sortable-stress.html

**Comment by clayop** [comment]
That's what I want exactly. But for now, sorting by volume and 24h change is enough. Please put low priority on manual sorting, if it takes long.

**Comment by wmbutler** [comment]
I think we should break manual sorting into a separate issue. It will take significantly longer to do and would delay getting the other pieces completed. I'll open a new issue called Custom market sort order.

#464 will handle point 3
#448 addresses points 1 and 2

Closing this as a duplicate.
