### ISSUE TITLE
Where are the candlesticks?

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#461]
Candlesticks are supposed to indicate the trading range line, the open and closing price, right? 

Currently they look like a 1 pixel line that my (less than perfect) eyes can see. 

Please make the candlesticks look like candlesticks.

**Comment by svk31** [comment]
This is a limitation of Highstock, the candlestick line width is tied to the border line width, if I make it thicker it looks like this:

![image](https://cloud.githubusercontent.com/assets/6890015/11338587/4b075cce-91f5-11e5-95ab-cac4331efbce.png)

That's worse imo so this won't be changed.
