### ISSUE TITLE
Custom Market sort order

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#464]
The discussion took place in #458 but the idea is to carve out the custom sort into this issue since it will be more complicated.

Sort manually, when clicking "customize" button: users can arrange market list order

**Comment by svk31** [comment]
I'm not sure what the purpose of this issue is, nor the value of this "custom sort".

Currently you can sort the market lists by volume, price change and name. What else is needed?

**Comment by wmbutler** [comment]
I took it from another user request, but I agree, it's probably low priority. I think the idea is that a user could assign an arbitrary sort order based upon their preference by dragging and dropping.
