### ISSUE TITLE
Deposit/Withdraw UX concept

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#465]
The deposit/withdraw functionality of the current wallet is functional, however, it hides important information that is necessary for new users to gain comfort. This is a particularly critical time for our interaction with the client. We have the benefit of knowing that they have a $0 balance when they first create their wallet and we should customize the UX to make it easy for them. The sentence: **Now that you’ve created your account, it’s time to bring in some funds** should be present only if their account balance is $0.

I'm proposing this as a process of 3 steps.
- Choose the gateway provider
- Choose the currency to deposit
- Choose the deposit amount

It's my belief that a user needs tangible numbers to help them with their calculations. And, generally speaking, they want those number in a currency they can reference easily. I think that **always** displaying their default currency in parentheses is a great idea because it aids them in their decision. See the "You are Planning..." paragraph that should populate dynamically based upon the 3 values chosen above.

Once the user has made the decisions, they should be able to display a QR code and address that they can easily copy/paste.

**Comment by wmbutler** [comment]
![screen shot 2015-11-07 at 8 51 05 pm](https://cloud.githubusercontent.com/assets/1254810/11018297/6af1f9c4-8591-11e5-959a-a27118d10b14.png)

![screen shot 2015-11-07 at 7 23 19 pm](https://cloud.githubusercontent.com/assets/1254810/11018115/eca04508-8586-11e5-8638-0ac2b5bb79af.png)

**Comment by wmbutler** [comment]
And the withdraw screen would look like this:

![screen shot 2015-11-20 at 3 57 41 pm](https://cloud.githubusercontent.com/assets/1254810/11311709/792f0ac8-8f9f-11e5-9b32-e92d6668ee83.png)

**Comment by clayop** [comment]
Good.
But instead of a long paragraph, I prefer simple expression like Coinbase, especially for non-English speaking users.

E.g. in your withdraw screenshot, the paragraph can be simplified as follows,

(Amount: 2.3 OPENBTC) - duplicated with AMOUNT TO WITHDRAW
Fee: 0.015 OPENBTC
Total Payout: 2.285 BTC

**Comment by wmbutler** [comment]
I agree. Updated the UX accordingly.

**Comment by clayop** [comment]
@wmbutler Thanks! Please do the same on deposit menu too.

e.g.

Gateway: Open Ledger
Amount: 2.3 BTC
Fee: 0.015 BTC
Total: 2.285 OPENBTC

**Comment by wmbutler** [comment]
yep, all updated.

**Comment by clayop** [comment]
One more thing. Transfer fee is also considered in the calculation.

**Comment by wmbutler** [comment]
@clayop so, what do you think, break down the transfer fee and the Bitshares Network Fee or just consolidate the two?

**Comment by clayop** [comment]
I think it's too informative. Consolidating the two may be enough for users.

**Comment by wmbutler** [comment]
OK, so the `Fee` line is good enough then? It can include all fees that the user pays as part of the transaction.

**Comment by clayop** [comment]
Yes. Thank you.

**Comment by valzav** [comment]
I think rather than have DEPOSIT and WITHDRAW tab on top, we may have ask user to select conversion pair as a first step.

**Comment by valzav** [comment]
Also I think it's important to provide more information, users might have a lot of questions, like:
- what is  GATEWAYBTC vs. real BTC and BitBTC
- what gateway to chose - there should be some comparison table that shows liquidity, reputation etc

**Comment by wmbutler** [comment]
#521

**Comment by kenCode-de** [comment]
Right now in light wallet v2.0.151119 the Deposit/Withdraw screen is a mess with all the Bridges and Gateways starting to appear. 

I love the layout above using drop-down select menus instead. Sort them alphabetically too so that we do not play favorites with any one of them. The white arrow buttons are not consistent, so make those consistent with svg's back/forward button designs for consistency. 

I don't think the extra menu items on the left panel are necessary.

**Comment by svk31** [comment]
Moved to bitshares-ui
