### ISSUE TITLE
Advanced Chart Index

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#466]
According to a day trader, additional chart index is attractive feature for traders.
He asked to add some basic index (there are tens of auxiliary index, see https://tradeblock.com/markets/bfnx/xbt-usd/2h  "Technical") into BitShares DEX. These features can be chosen in "Advanced" button (See poloniex's gear button)

The list is as following:
- [x] RSI
- [x] SMA Period
- [x] Average True Range
- [x] EMA 1 Period

IMHO, this has low priority at the moment, but in a long-run it's quite required.

**Comment by wmbutler** [comment]
Agreed. I'll mark this as an enhancement but not assign it to a Milestone yet.

**Comment by wmbutler** [comment]
This needs to be further broken down, otherwise this issue will just keep getting carried forward.
