### ISSUE TITLE
Get rid of the horizontal scroll-bar in Recent Activity

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#470]
Linux mint light client v2.0.151103 

On the right side of the screen there is a horizontal scrollbar that makes me scroll sideways since one of the transactions in that "Recent activity" area has a long URL that was pasted into the memo field. 

Please wrap the cell contents so that I don't have to scroll sideways, thanx :)

**Comment by wmbutler** [comment]
Better yet, we should decide on max characters to be displayed like:

`https://www.google.com/this/and....`

**Comment by kenCode-de** [comment]
Or raise fees for every byte consumed by the memo.

**Comment by kenCode-de** [comment]
I foresee the "memo" field becoming something much more. That field is like a BLOB, it could store binary images, memo text, the permalink to an online document, or even the hash of a smartcontract on another chain altogether...
