### ISSUE TITLE
Transaction.jsx unimplemented proposal_create 

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#472]
console error: unimplemented op:  [22, Object]

The transaction confirmation dialog does not display the proposal create operation, instead it falls back to the tree view.

``` json
[22,{"fee":{"amount":"2000000","asset_id":"1.3.0"},"fee_paying_account":"1.2.17","expiration_time":"1970-01-17T17:58:18","proposed_ops":[{"op":[0,{"fee":{"amount":"2000000","asset_id":"1.3.0"},"from":"1.2.28","to":"1.2.17","amount":{"amount":"900000","asset_id":"1.3.0"},"extensions":[]}]}],"extensions":[]}]
```

**Comment by jcalfee** [comment]
Also needed: proposal_update, and proposal_delete

**Comment by svk31** [comment]
I can add this but I need the json data for _update and _delete.

I assume proposed_ops can contain an unlimited (or at least large) amount of additional operations?

If you've already made these transactions on the blockchain it would be a great help to actually have the block numbers.

**Comment by jcalfee** [comment]
Let wait on update and delete...  I look at how you do create in this commit.   Maybe I can add those later...

No, not a lot for a while...  One initially.  A simple overflow just in case...

**Comment by jcalfee** [comment]
Once the witness node is updated I'll put a proposal on the blockchain....

**Comment by wmbutler** [comment]
Can this stay in 1118, or do we need more time? @jcalfee

**Comment by svk31** [comment]
This is like 30 mins of work once I actually have a transaction to work with.

**Comment by wmbutler** [comment]
This is still in testing. I can't close 1118 until someone does something with this item. @jcalfee @svk31

**Comment by wmbutler** [comment]
Should I move it to 1125?

**Comment by wmbutler** [comment]
Closing since this issue is orphaned with no comments.
