### ISSUE TITLE
Enable proposed tranfers

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#475]
depends https://github.com/cryptonomex/graphene-ui/issues/473
depends https://github.com/cryptonomex/graphene-ui/issues/472

This commit is originally on the develop branch in `graphene`.  It needs to be in the witness node before releasing...
depends https://github.com/cryptonomex/graphene/commit/b03ac00b6c8f1dc00a47616b7571d79ee3381f23

Include the `propose` feature in the transfer dialog:
git revert 6d1466722497ba5449ff7a632fea5f8025da6911

**Comment by wmbutler** [comment]
Closing this. @jcalfee
