### ISSUE TITLE
Bad zoom level for market wall view

### ISSUE THREAD

**Issue by dnotestein** [cryptonomex/graphene-ui#477]
It's not possible to see the order wall for market with a large spread. In included screenshot, the graph is blank. You can only see the buy and sell order by scrolling left or right (can't find any way to zoom out to see the orders together).
![trademuse_bts_market_graph_bug](https://cloud.githubusercontent.com/assets/5102968/11067222/8696df64-8799-11e5-998a-f9248e78375a.jpg)

**Comment by wmbutler** [comment]
This is a scaling issue. Added for late November.

**Comment by svk31** [comment]
I can't reproduce this anymore, but my latest commit should fix this anyway.
