### ISSUE TITLE
Show BTS balance in Accounts search results table

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#482]
Click on Explore, Accounts, enter BTER in the Accounts search field. 

ID and Account Name columns are shown. There is room on the screen still, could you please also show that users BTS balance in a right-side column? 

This allows me to see which account is most likely used for cold storage, which is that exchanges hot wallet, etc. 

CT contacted me again and is doing a story on proving an exchanges solvency. This would allow me to quickly prove it to them. 

Edit: BTER results on 0 matches. bter shows us a huge list making it very hard to find the right user (hence my request above).

**Comment by wmbutler** [comment]
1125 Milestone.

**Comment by wmbutler** [comment]
Does this fit in with #522 @svk31 ?

**Comment by svk31** [comment]
Unrelated but I could add that as well, the table needs more columns anyway.
