### ISSUE TITLE
Cannot Generate MUSE Deposit Memo

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#484]
![image](https://cloud.githubusercontent.com/assets/9971632/11100001/688d6932-8863-11e5-8b78-762e856129f8.png)

I clicked generate button several times, but it does not show the memo I have to enter.

**Comment by emfrias** [comment]
There was an error in the original implementation, MUSE deposits use a memo instead of new addresses.  Fixed in 12dc274752d1fa606c21ea558947c9cd446cad95

**Comment by clayop** [comment]
Solved. But the deposit doesn't work at the moment.
http://muse.cryptofresh.com/b/522859

**Comment by clayop** [comment]
Memo was wrong. My bad.
