### ISSUE TITLE
QR codes needed BAD

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#492]
1. Click on an account in your wallet (i am using linux light client). 
2. Click on Deposit/Withdraw 
3. Next to the "generate" button, there needs to be a small QR code button as well, ie: 
   [ QR ] 

This will allow me to hold up my phone, scan the qr code, and send some BTC to my light wallet so that I can buy OPENBTC easily. 

Right now however, I have to select and copy that BTC address, paste it into an email, email it to myself, retrieve that email on my phone, copy the btc address again, paste it into mycelium, then send the bitcoin to the address. GACK!

**Comment by c055** [comment]
https://github.com/cryptonomex/graphene-ui/issues/465

**Comment by wmbutler** [comment]
Closing as duplicate #465
