### ISSUE TITLE
Request settlement of bit asset

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene-ui#493]
This needs to be added so that holders of bit assets can reliably convert their assets to BTS.

**Comment by clayop** [comment]
It really needed. What about having "Advanced" button and when users click the button, Borrow USD and Settlement USD are shown?

**Comment by wmbutler** [comment]
I think I need clarification here in order to UX this. Which screens are we talking about. Is this where we can settle up short positions?

**Comment by svk31** [comment]
I've added it as a modal, triggered by clicking on the Settle button that you can see in the background. I also rearranged the table a little cause I felt it fit better like that, but feel free to suggest another arrangement @wmbutler 

Could probably use a bit of help text too.

![image](https://cloud.githubusercontent.com/assets/6890015/11384447/3277a850-9310-11e5-8681-d0731c4baf99.png)
