### ISSUE TITLE
[Feature request] Account overview optimization for many accounts

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene-ui#494]
Just some thoughts to make the accounts overview page more useful for people with several accounts:
- [x] Highlight lifetime member accounts
- [x] Search/Filter for account names (complete in issued #590)
- [x] checkbox to "hide empty" accounts (starring accounts instead)
- [ ] show only those accounts holding asset X
- [ ] sort by recent changes

**Comment by wmbutler** [comment]
Bunch of UI stuff here. I'll get to work on it.

**Comment by wmbutler** [comment]
Moving this 1209 Milestone. I need to UX this. I'd like to consider getting away from the 'cards' view.

**Comment by jonnybitcoin** [comment]
I've got loads of accounts i'm name squatting yet only use one which i have scroll for ages to find each time I click the dasboard. you should be able to choose a "primary account" that is always at the top.

**Comment by c055** [comment]
https://github.com/cryptonomex/graphene-ui/issues/494#issuecomment-159121359

mh i don't know if we talk about same UI section ...i'm not talking about the Dashboard section .. 

it's Account Detail > Overview > ...

**Comment by wmbutler** [comment]
I have some ideas on this.
