### ISSUE TITLE
asset issuer should have ability to fund asset fee pool

### ISSUE THREAD

**Issue by valzav** [cryptonomex/graphene-ui#495]

**Comment by c055** [comment]
+1

**Comment by wmbutler** [comment]
If this requires UX, I'd like to have some more commentary on what this means so I can create some pretty pictures.

**Comment by xeroc** [comment]
If you want you own token you have to
1. create an asset (we can do this already)
2. issue tokens to one of your accounts (missing)
3. sell your tokens in any market (we can do this as well)

to issue tokens you need to run this in the cli:
https://bitshares.org/doxygen/classgraphene_1_1wallet_1_1wallet__api.html#ac4ff8075641a7469265122ff9a66e30e

It requires these parameters:
Parameters
- to_account: the name or id of the account to receive the new shares
- amount: the amount to issue, in nominal units
- symbol: the ticker symbol of the asset to issue
- memo:   a memo to include in the transaction, readable by the recipient
- broadcast:  true to broadcast the transaction on the network 

After verification, the amount of shares pops up in your account.

**Comment by svk31** [comment]
Issuing tokens has been available in the GUI since launch. Funding the fee pool is not available however.

**Comment by svk31** [comment]
There's been so many issues with insufficient balances in fee pools lately I felt it was necessary to add this. 

I also added support for the asset owner to claim the fees, but that requires an update of the OpenLedger witness node so I've hidden it for now in the GUI.

**Comment by abitmore** [comment]
> Issuing tokens has been available in the GUI since launch. Funding the fee pool is not available however.

See https://bitshares.openledger.info/#/account/abit :
- abit created the asset THUMBSUP  

But I can't see my created assets nor issue them to someone with GUI? Shouldn't it be at https://bitshares.openledger.info/#/account/abit/assets ?

**Comment by abitmore** [comment]
My assets appeared on OpenLedger finally. However it took about 10 seconds before they appear on the page https://bitshares.openledger.info/#/account/abit/assets . And they've never appeared in light wallet.
