### ISSUE TITLE
CORE is hard-coded in SettingsStore.js

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#497]
https://github.com/cryptonomex/graphene-ui/blob/eb4def1d75710572456abc37e2bcc2fe223bf4f9/dl/src/stores/SettingsStore.js#L6

Instead an `init` method would be more appropriate so this could update automatically via the chain/config.coffee ..

**Comment by jcalfee** [comment]
[9:06:43 AM] jose david de lavalle tcherassi: I'm signed in, and all tabs: account - explore - transfer work well. But when I click "trade" it becomes unresponsive.

**Comment by jcalfee** [comment]
this is a low priority

**Comment by svk31** [comment]
The only reason this is an issue is because people are using graphene-ui with the BTS chain. In a recent commit I changed the variable in the SettingsStore to BTS instead of CORE so this should no longer be an issue. I suggest we simply leave it like that..
