### ISSUE TITLE
2.0.151118 doesn't load previous wallets

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene-ui#502]
This report is for the electron build:

1) Create a wallet in 2.0.151111
2) Close 2.0.151111
3) Build and open version 2.0.151118
4) BitShares opens to the "Create Account" page. **The previously created accounts appear to be missing**
5) Close 2.0.151118, and open 2.0.151111. **The wallet is still there.**
6) Backup the wallet in 2.0.151111 and close 
7) Open 2.0.151118. Import the new backup, **the wallet is imported**
8) close and reopen 2.0.151118, **the wallet is still there**

It appears that the new wallet can't see the old wallet's data until it is imported

thanks

**Comment by valzav** [comment]
I don't see this issue. Can anybody else confirm?

**Comment by maqifrnswa** [comment]
hm, since I imported the wallet I can't reproduce either -- maybe my db got corrupted somehow

**Comment by wmbutler** [comment]
Please close if you can't reproduce @maqifrnswa
