### ISSUE TITLE
CREATE ASSET button is nearly impossible to read

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#504]
Click on an account in your wallet 
Click on Assets 
Click on CREATE NEW ASSET button 
The CREATE ASSET button at the bottom of that screen is a light gray text label on a medium gray button, it is nearly impossible for my 45 year old eyeballs to read.

**Comment by valzav** [comment]
Probably it's fixed already - here is what I see now:

![image](https://cloud.githubusercontent.com/assets/28658/11275275/ded31270-8eaa-11e5-9cf8-a29c0f12f394.png)

**Comment by kenCode-de** [comment]
whoa cool, i guess i need to grab the latest deb thanx Valentine :)
