### ISSUE TITLE
Newest electron version on npm changed data directories

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene-ui#508]
I got to the bottom of #502 

Electron moved the data directory, they are now found at:
$XDG_CONFIG_HOME/chromium/BitShares2-light
(~.config/chromium/BitShares2-light)
instead of where they were originally:
$XDG_CONFIG_HOME/BitShares2-light

that means if people upgrade electron and rebuild their own electron app, they will not find their wallets as the new folder is empty. Same goes for the packaged versions.

I wanted to let everyone here know that if you update your electron your users won't be able to find their wallets. Either copy over your $XDG_CONFIG_HOME/BitShares2-light to $XDG_CONFIG_HOME/chromium/BitShares2-light, or import your backed up wallets.

https://github.com/atom/electron/commit/83ae9f8d71007944b9f9e5b631740ea7a416e1b9#diff-f61b360ad8984d98baba4d962bf4d259R70

**Comment by wmbutler** [comment]
@maqifrnswa close this when you are ready.

**Comment by maqifrnswa** [comment]
https://bitsharestalk.org/index.php/topic,20184.new.html#new
posted here too, I think this should give enough pointers for people to be aware of any issues
