### ISSUE TITLE
Voting action publishChanges error

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene-ui#51]
This method uses Object.assign which is experimental and at least for me throws an error:

```
Uncaught TypeError: Object.assign is not a function
```

**Comment by valzav** [comment]
I hopped babel would replace it with something more robust.
Do you think we should use some general purpose library for things like that, e.g lodash?

**Comment by svk31** [comment]
Fixed by 0054e190851a965af5fdbb8878e4cb5578a79abe
