### ISSUE TITLE
Display total assets of all account in chosen currency

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#512]
As a user, I should be able to see the value of all of my holdings in whatever trading pair / currency I desire.

**Comment by svk31** [comment]
I've added user selectable unit of value for the conversion today because it was easy after fixing the conversion component. Will add totals in the correct milestone.

**Comment by wmbutler** [comment]
Bumping this to current milestone since you already did work on it. I had originally placed this in next week's milestone. You will notice that when I add issues, I don't necessarily place them in the current milestone because they are quite often low priority compared to the other bugs and items in the current Milestone.

**Comment by wmbutler** [comment]
Might be enough to satisfy the basics...

![screen shot 2015-11-23 at 11 23 58 am](https://cloud.githubusercontent.com/assets/1254810/11342312/b8edf552-91d4-11e5-9409-643c86026eae.png)

**Comment by svk31** [comment]
I've made a new component that calculates equivalent values for all balances in the desired asset. For now there's no dropdown to select your desired currency so you'll have to set it in the settings, but I can add that later.

**Comment by svk31** [comment]
![image](https://cloud.githubusercontent.com/assets/6890015/11381265/6079ab1e-92fb-11e5-9790-4f2098b43982.png)

**Comment by wmbutler** [comment]
Slick.
