### ISSUE TITLE
Error in MarketsActions.subscribeMarket:  ReferenceError: showCallLimit is not defined(…)

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene-ui#513]
Opening BTS:BTC freezes the ui.
bitshares2 ui 2.0.151119

Java console says:

```
Error in MarketsActions.subscribeMarket:  ReferenceError: showCallLimit is not defined(…)
Uncaught ReferenceError: showCallLimit is not defined: app.js:100
```

**Comment by svk31** [comment]
Was fixed here: https://github.com/cryptonomex/graphene-ui/commit/c295d96deb43852f990ad6a9c2370413b3eaba40

**Comment by maqifrnswa** [comment]
Thank you! Great job keeping up with these reports, it's been quite impressive
