### ISSUE TITLE
Clicking on lowest or highest buy/sell price does not result in an eligible market order

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#515]
Study this screen shot first:

![screen shot 2015-11-22 at 1 11 49 pm](https://cloud.githubusercontent.com/assets/1254810/11325506/c2d25084-911d-11e5-97c3-d21a636becc6.png)

In this screen shot, I clicked on the lowest sell price (114.810.56250) and specified .29238 BTC. This value populated correctly in the buy input field, however, during the order confirmation, it gets changed to 114,810.5664139393. Since this value is higher than the lowest offer, it will not execute immediately. IMO, the reason for being able to click on a particular offer, it that the end user whats to execute it immediately. I can only assume that the fractional difference is the 10BTS fee.

It is critical that the price BTS/BTC match in all locations. We should make this a top priority and resolve every edge case in this Milestone. I think it also would be good to modify the market page to include the fee so the confirmation dialog matches it exactly.

I'm going to place a large estimate on this item. I really hope you agree with the importance of this item.

**Comment by svk31** [comment]
Would appreciate some testing here as well.

**Comment by wmbutler** [comment]
I really need to get a test env setup, but haven't yet and not sure I'm clear on how to.

**Comment by c055** [comment]
on which system u are working?

**Comment by wmbutler** [comment]
OS X
