### ISSUE TITLE
RSI and ATR indicators make the price chart too small

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene-ui#516]
When adding one of these indicators the chart yAxes all get set to the same height. Ideally the price chart should remain larger than the volume chart.

![image](https://cloud.githubusercontent.com/assets/6890015/11325905/79c42506-915a-11e5-96d6-73808406d737.png)

**Comment by wmbutler** [comment]
@svk31 should we table all of these and just wait for the react charts?

**Comment by c055** [comment]
+1

**Comment by svk31** [comment]
Yes I was thinking the same thing.

**Comment by wmbutler** [comment]
OK, I'm going to close all issues related to charting bugs. Which Milestone should we target for the charting updates?
