### ISSUE TITLE
There is an unnecessary horizontal scroll-bar on the voting/workers page

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#518]
[Chrome / Win 7] & [Firefox / Win 7]
[version 2.0.151119]

![03](https://cloud.githubusercontent.com/assets/11573977/11332193/c412db98-91c3-11e5-9990-1e5cec5313bd.png)

**Comment by wmbutler** [comment]
This is not present on the OS X version. Need to be tested on Win. Quick, easy fix for the right dev.
