### ISSUE TITLE
 The [FAV MARKETS] / [ALL MARKETS] tabs don't work when accessed for the very first time.

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#519]
[Chrome / Win 7] & [Firefox / Win 7]
[version 2.0.151119]

The [FAV MARKETS] / [ALL MARKETS] tabs are not working properly when a user tries to access the GUI for the very first time. None of them is selected and there is empty space below.
The same refers to [HISTORY] / [ALL HISTORY] tabs.

**Comment by neura-sx** [comment]
Maybe I need to specify this bug a bit more: this happens when you attempt to access the GUI in a browser which has never used the GUI before. So it only happens for the very first time and then does not happen again (I guess it's because some cookie data gets created).

**Comment by wmbutler** [comment]
Well, looks like a fix was added for 1125, so re-open it if it's still present after 1125 is released.
