### ISSUE TITLE
App crashes on the market page - argument is not an object id

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#520]
[Win 7 / Firefox] 
[version 2.0.151119]

An attempt to access a market, e.g.
https://bitshares.openledger.info/#/market/BTS_USD
crashes the GUI as seen in the following screen-shot:

![ol crash](https://cloud.githubusercontent.com/assets/11573977/11332302/f62e76f4-91c4-11e5-9b1e-0ce37d4c3124.png)

**Comment by svk31** [comment]
I can't reproduce this, it works fine for me. (OSX, Firefox v41.0.2)

**Comment by neura-sx** [comment]
Can someone confirm it on Win 7 / Firefox ?

**Comment by wmbutler** [comment]
Added to 1202 Milestone. Need to reproduce on Win/Firefox

**Comment by b33lz38v8** [comment]
my wallet becomes unresponsive when clicking on certain starred markets. could it be related?
win10/chrome

[![starred markets bug](http://img.youtube.com/vi/3zf5gYzuBOE/0.jpg)](http://www.youtube.com/watch?v=3zf5gYzuBOE)

**Comment by wmbutler** [comment]
@b33lz38v8 can you say which markets so we can attempt to reproduce?

**Comment by b33lz38v8** [comment]
they are listed in the video description along with the console errors. but here you go:

BTC:CNY
BTS:EUR
BTS:USD
BTS:SILVER
METAEX.BTC:BTC
BTS:CNY
BTS:BTC
BTC:USD
TRADE.BTC:BTC
BTS:GOLD

**Comment by wmbutler** [comment]
Your report indicated that your browser became unresponsive on **certain** markets. I was hoping you could say which markets caused this behavior. Are you saying that all markets cause this behavior?

**Comment by wmbutler** [comment]
Can you display your console when performing these actions since I can't reproduce:

Developer Tools:

![screen shot 2015-11-23 at 8 33 27 pm](https://cloud.githubusercontent.com/assets/1254810/11355247/8630069e-9221-11e5-9fd4-aa70f3810db4.png)

**Comment by b33lz38v8** [comment]
default starred markets.

causing error:
BTC:CNY
BTS:EUR
BTS:USD
BTS:SILVER
METAEX.BTC:BTC
BTS:CNY
BTS:BTC
BTC:USD
TRADE.BTC:BTC
BTS:GOLD

properly working:
BTS:TRADE.MUSE
BTS:OPENMUSE
BTS:TRADE.BTC
BTS:OPENBTC
BTS:METAFEES
BTS:OBITS
BTS:METAEX.BTC

**Comment by wmbutler** [comment]
Still can't reproduce. Would be helpful to see the output of your console under developer tools.

![screen shot 2015-11-23 at 8 54 55 pm](https://cloud.githubusercontent.com/assets/1254810/11355633/7d65d658-9224-11e5-873b-e20daa1f4561.png)

**Comment by b33lz38v8** [comment]
@wmbutler 
[![console errors](http://img.youtube.com/vi/VmgWe6WURfg/0.jpg)](http://www.youtube.com/watch?v=VmgWe6WURfg)

**Comment by b33lz38v8** [comment]
loading...
[![console errors](http://img.youtube.com/vi/OSGQg5h57OM/0.jpg)](http://www.youtube.com/watch?v=OSGQg5h57OM)

**Comment by svk31** [comment]
Are you running the latest version? I suspect your issue is related to an issue that was fixed this weekend, that only concerns bit assets which is your case.

https://github.com/cryptonomex/graphene-ui/commit/c295d96deb43852f990ad6a9c2370413b3eaba40

**Comment by b33lz38v8** [comment]
i'm on latest commit:
9e98eee2ee37838eab3f682073efdf2eb69ac232

**Comment by svk31** [comment]
@b33lz38v8 I've gone to your site and it all works fine for me.
