### ISSUE TITLE
The Deposit/Withdraw functionality should be organized in a similar way to markets

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#521]
The current approach to the Deposit/Withdraw functionality currently looks very chaotic in terms of UX.
Firstly, there is this artificial split between Bridges and Gateways.
Secondly, each service provider seems to have its own concept of UI (specific to its service) which looks very inconsistent when viewed on a single page.

What I propose is to have the Deposit/Withdraw functionality organized in a similar way markets are organized:
(1) There should be an initial page where all gateway/bridge providers are listed (e.g. Blocktrades, Transwiser, Metaexchange, OpenLedger etc).
(2) Each provider should have its own dedicated page (just as each market has its own page). So by clicking on any provider listed in (1) you would navigate to a separate page which will be organized according to the specific offer of the provider and fully managed by the provider.

In this approach the gateway/bridge functionality would be detached from the account page and listed as a separate item in the top menu bar:
Dashboard | Explore | Deposit/Withdraw | Trade | Transfer

https://bitsharestalk.org/index.php/topic,19417.msg259875.html#msg259875

**Comment by wmbutler** [comment]
I think all of these points are addressed here: #465 Closing as duplicate. Please review #465 and add comments/concerns there.
