### ISSUE TITLE
Show stake percentages at all times in wallet

### ISSUE THREAD

**Issue by luckybit2014** [cryptonomex/graphene-ui#522]
Anywhere that we currently see "Balances" with phrases like "Equivalent Value" or "Amount" we should replace or put next to it "Percentage Stake. If next to an asset you know exactly how much BTS is the equivalent value it psychologically encourages the viewer to immediately dump the asset to claim the value. It's bad psychology for the wallet if you want to encourage increased stakeholder ownership. We want to encourage ownership, and how many BTS a person holds doesn't determine the percentage ownership they have, it's literally just an arbitrary number.

Early on Bytemaster proposed we do away with the "arbitrary numbers" as a representation of ownership and move toward a GUI which displays percentages. I agree with this, especially since UIAs are primarily going to be thought of as stakes or shares, not as coins. The coin mentality is under an assumption that Bitcoin started but it's not applicable for what Bitshares is doing. Bitshares do not have a fixed supply, and are not and have never been coins.

I propose that in the interim a change be made to the interface to allow the user to switch from seeing the number of an asset they own to the percentage. A pie chart with a percentage is all an asset holder ought to see and the number of an asset should be phased out. A holder if rational will want to prefer and increase their percentage ownership over time and the lack of seeing this information encourages a mindset to dump BTS, dump any asset, or to focus on smart coins instead of UIAs.

This feature was discussed almost a year ago but mysteriously it was never implemented? https://bytemaster.github.io/update/2014/12/18/What-is-BitShares/

**Comment by luckybit2014** [comment]
I would say perhaps even better would be just to implement the change and remove the "Equivalent Value" field altogether unless the value is in USD or some other stable currency. It provides arbitrary information like how much BTS something is worth but then the individual has to know how much that is worth in USD if they are trying to preserve USD value. So what do we even gain with that? I'm not saying remove it but at least let the user choose what to display, whether it's Equivalent Value in BTS, or in USD or in Gold or in Euro or whatever else.

On the other hand, the percentages should be listed somewhere, if not in the balances category then where? Not having it at all might negatively effect the psychology, and in my opinion having the percentages more proment in the interface than the balances is a way to help improve the psychology.

People don't need to see balances at all when it's in something like Metafees. They need to know how much percent of Metafees they own and that's it. The only time the amounts matter are when people are trying to buy it, but even then a person might determine they want to buy a certain percentage and maintain that by automatically buying and selling to keep it at the same level over time.

**Comment by svk31** [comment]
I don't think showing value as a percentage is a good idea tbh, it sounds neat but quickly becomes unpractical. And for anyone other than a whale it's just meaningless. Yes you could show parts per million or something but again I don't think it would make sense to most people. To make things worse: bit assets supply is constantly changing, so you'd see your percentage vary on a daily and even hourly basis without having done anything.

Since yesterday you can choose a currency other than BTS for the equivalent value in the settings: USD, CNY, BTC or EUR, I think that should be enough for now.

**Comment by luckybit2014** [comment]
The point is to encourage the people who are whales to want to stay whales. A whale is just a person who has a greater percentage stake than another person. While it might be nice if you could have maximum decentralization have everyone have a fraction of a percent stake, the fact is there will be whales who care about their percent stake.

But even for people who aren't a whale, if you hold 0.005%, you're going to want to keep that 0.005% and grow it. If you feel bad about only holding 0.005% you'll be less likely to sell it all than if you feel like you're rich because you hold some arbitrarily large number of something. If your percentage changes on a daily basis and you see it that is a good thing, that is the whole point of providing that information so that for people who want to know exactly what they own they can know.

Basically I think percentages should be an option. If you don't like percentages then why not add your option in as a choice as well but I prefer percentages in my interface because I don't think in PPM or in arbitrary "amounts". Basically I see both of those tactics as just a way to try to fool people into not knowing how much of a percentage stake in the pie they actually hold.

Also I didn't know they changed the equivalent value thing. That is good. Now they just need to add the percentages and pie charts for people who are long term stakeholders. For long term stakeholders seeing these percentages matter far more than anything else. Remember if we want people to feel like they own companies and not just tokens, we have to actually display it as we would to shareholders and not just to speculators. In a way, the psychology we have is due to the interface favouring short term speculation mindsets.

**Comment by wmbutler** [comment]
I prefer being able to see the overall value of all my accounts in a preferred currency. Seems like this is the way to go. We do need to figure out where this number needs to be displayed. 

If someone is a whale, they are doing the math in their head. I agree that we need ot make it easy for them to know the number of BTS outstanding, etc. but I'm not totally sold on displaying the percentage.

**Comment by luckybit2014** [comment]
@wmbutler If you're a whale who has a goal to own a specific percentage of Bitshares because you're a long term investor type instead of a day trader, then you will care about what percentage you're at.

Also the percentage will let you immediately know if Bitshares is going in the right direction. If fees are burning the percentage of shares you hold will increase over time and this information should make you feel good as a long term investor. So when people say you'll see the percentages changing on a daily basis that is the whole point.

At the same time if Bitshares is generating new shares then you have a right to see that your percentages are going down each day. Also this has to apply to all UIAs and not just to BTS, and because of the nature of UIAs the only thing that matters is the percentage ownership in the company because that is how much you are putting at stake, how much faith you have in the company, how much risk you are taking.

The USD amount if you measure everything in USD will focus all attention on that and people will not care about the UIAs, the DACs, or the Bitshares, and will only focus on the value of the USD. This is fine but you have to understand currencies don't get tracked by percent because currencies inflate forever, but shares in companies do get tracked by percent.

In a way we are displaying Bitshares as a currency trading sort of thing instead of a shareholder emphasis. I think that is part of the reason why it's harder to market it to certain people who like what Bytemaster has to say about financial independence, or like what they read on the blog or forums years ago, but then we don't see any of that in the app.

Ultimately if a UIA represents a share in a DAC, then a shareholder probably will want to know what percentage they hold. Otherwise it's obfuscated like with the banks, where people hold arbitrary numbers of meaningless value because the numbers could be due to inflation, and so they don't actually reflect any ownership of anything. 

Of course I could be wrong, which is why it's best if we have this discussion and maybe see if the community would like to switch to percent. If someone can make a mockup with the percent and pie chart in the interface and compare it with the PPM and other ideas in mockup then perhaps we can let the community discuss it properly. I do think a lot of people in the community of a certain demographic will prefer percentages and I know Bytemaster at one point said he did.

**Comment by wmbutler** [comment]
Interesting. I tend to just care about the overall value of my investment in terms of buying power. I've tagged this as a discussion item.

**Comment by svk31** [comment]
You do make a good case for it even though I doubt there are all that many people out there who have as a goal to own a certain percentage of BTS :)

Either way this shouldn't be too hard to implement so I wouldn't mind adding it, at least as an alternative to the converted value that's shown in the account overview. Using it globally would be more complicated, in transfers and markets for example, but at least in that one place I should be able to add this fairly easily.

**Comment by wmbutler** [comment]
@svk31 I've been struggling with where to display the total value of a wallet. Seems like it might go nicely on the the main menu to the left of the gear icon. I personally want to know the net worth of my wallet at all times.

**Comment by wmbutler** [comment]
Maybe here with a dropdown for BTS %, BTS, USD, CNY, EUR

Might be enough to satisfy the basics...

![screen shot 2015-11-23 at 11 23 58 am](https://cloud.githubusercontent.com/assets/1254810/11342312/b8edf552-91d4-11e5-9409-643c86026eae.png)

**Comment by svk31** [comment]
Yea that looks good to me, but in that case the percentage doesn't really make sense, unless you meant that it only applies to your BTS holdings?

**Comment by wmbutler** [comment]
Correct. I thought that's what the OP was referring to....oh, yeah. Agreed. Leave the BTS% out of that and we can have that somewhere else.

**Comment by wmbutler** [comment]
@luckybit2014 what do we do about ridiculously small percentages...just display them anyway?

**Comment by valzav** [comment]
I support the idea to show BTS percentage owned by users. This way we stress out that user own a certain amount of stake in Bitshares DAC and has right to vote on different issue and participate in DAC's government.

**Comment by wmbutler** [comment]
Sounds good. I'll work up a UX.

**Comment by svk31** [comment]
I decided to have a quick look, took me 5 minutes finally to make this:
![image](https://cloud.githubusercontent.com/assets/6890015/11349373/301c3ace-922c-11e5-850f-4db7b74961f7.png)
I have to admit it can actually be quite interesting.

**Comment by wmbutler** [comment]
Nice!

**Comment by kenCode-de** [comment]
Possible to add one more row to that table that totals up the equivalent value column? Call it "Total Value" or "Net Worth" or something?

**Comment by luckybit2014** [comment]
@wmbutler Just display it anyway. Information is valuable and even if it is a ridiculously small percentage, display it if it can be displayed. If a person holds less than 1 BTS or something then maybe don't display that if you want to set a reasonable limit but more than 1 BTS and display it.

**Comment by luckybit2014** [comment]
@svk31 Your mockup is exactly what I had in mind. Thanks!

**Comment by svk31** [comment]
It's not a mockup it's the real thing, going live tomorrow ;)

**Comment by luckybit2014** [comment]
Excellent, you guys are fast.
