### ISSUE TITLE
Account drop-down options are inconsistent with selected third-party account

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#523]
On the market page, the drop-down options are limited to your own accounts (which makes sense) but it is possible to land on this page with somebody else's account selected via the dashboard (in this case I selected fav). This makes it inconsistent with the options available in the drop-down.

![04](https://cloud.githubusercontent.com/assets/11573977/11337720/57eaa384-91ef-11e5-976c-f6871f9ac7e2.png)

**Comment by wmbutler** [comment]
I don't really see this as a huge issue. Obviously you can't make any trades if you don't own that account...need to think through the best way to handle it....maybe an icon next to the account that indicates it's not one of your accounts essentially disabling trade buttons, etc. Will slate this for UI in mid December.

**Comment by svk31** [comment]
Sorry wmbutler but this was such an easy fix I just did it: if you've previously selected an account that isn't yours and then go to the trade page, that account will now be included in the dropdown.
