### ISSUE TITLE
Tighten up Market right side panel

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#524]
This is mostly my fault but it's an easy fix. We need some consistency on the Market/Trade page in the right panel. Currently it's:

![screen shot 2015-11-23 at 8 37 19 am](https://cloud.githubusercontent.com/assets/1254810/11337786/9cf0d08e-91bd-11e5-8258-2caea558d773.png)

Let's change it to:

Notes:
- My Markets matches My History both on left tab
- horizontal lines dividing items
- mm/dd added to date column
- Proposing a more obvious contrast for the inactive tab (compare MY HISTORY to MY MARKETS on the UI below) I think MY HISTORY better represents and inactive tab.
- This has been added to the December 2 milestone

![screen shot 2015-11-23 at 8 58 42 am](https://cloud.githubusercontent.com/assets/1254810/11338154/6e812ce6-91c0-11e5-868a-e8ac76453123.png)

**Comment by svk31** [comment]
I agree with the contrast for inactive/active tabs, matching all/my tabs and the lines between rows.

But the day/month is left out for a reason: lack of space.. There are already issues with overflow in this column. There's a tooltip though when you hover over the date that shows the full date.
