### ISSUE TITLE
OS X Light Wallet Bug

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#525]
On main Dashboard, user can click on account to open it the first time, but after going to Dashboard and attempting to click on the account (or any other account) the user is no longer allowed in.

![screen shot 2015-11-23 at 10 33 13 am](https://cloud.githubusercontent.com/assets/1254810/11340820/ca5ca254-91cd-11e5-9e5b-78aa16d6f1a1.png)

**Comment by svk31** [comment]
This sounds very strange, can you post steps to reproduce please? What does "allowed in" mean in this case?

**Comment by wmbutler** [comment]
Clicking on a 'card' shown above (the second time) does not result in any action being performed. You just continue to see the card view.

**Comment by svk31** [comment]
I've never seen this nor can I reproduce it on my own Mac.

If you can reproduce it, please open the dev tools and see what it says in the console.

View -> Toggle DevTools

**Comment by wmbutler** [comment]
Reproduce OSX LightWallet
- Quit OS X lite client
- Open OS X Lite client
- Click on your account that has a **zero balance** card from the Dashboard
- Click on Trade

From this point on, my client is essentially frozen. And this error repeats:

![screen shot 2015-11-24 at 9 06 07 am](https://cloud.githubusercontent.com/assets/1254810/11368978/a43c48fa-928a-11e5-94c4-89accc2aaddc.png)

**Comment by wmbutler** [comment]
Same bug as #520 This happens when the account in question has no funds and attempts to go to the Trade page.
