### ISSUE TITLE
More small tweaks to My History

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#527]
- [x] Match reds and greens for up and down price action (same shades of red and green as in the markets)
- [x] Look at logic for color change (I would assume that red means the price has gone down relative to the previous trade and green means it has gone up. There are some inconsistencies apparent in the screenshot below.

![screen shot 2015-11-23 at 6 06 49 pm](https://cloud.githubusercontent.com/assets/1254810/11352918/5e2c5f12-920d-11e5-8845-f0ffc7ad12fa.png)

**Comment by svk31** [comment]
The market history colors don't indicate price change, they indicate whether the triggering order was an ask or a bid. That's why it used the same colors as the depth chart and orderbook.

The trailing zeros: you want them white?

**Comment by wmbutler** [comment]
I get the ask or bid. Still would be nice if we used more standard colors but I'm not too hung up on it.

I would make every digit in the numbers the same color....or maybe this is a precedent I'm not familiar with?

**Comment by svk31** [comment]
It used to be that way and it was very hard to read the numbers, I find it's much better this way. It's inspired by Coinbase's exchange, but it has to work a bit differently since we have so many assets with different precisions and valuations..

**Comment by wmbutler** [comment]
OK,

How about this as a compromise. I think the odd colored zero's need to be less visible. If you look at coinbase, the contrast is waay down.

Coinbase:
![screen shot 2015-11-24 at 6 01 08 pm](https://cloud.githubusercontent.com/assets/1254810/11383322/65b55fae-92d5-11e5-961d-5c5c8213e89d.png)

Us:
![screen shot 2015-11-24 at 6 02 19 pm](https://cloud.githubusercontent.com/assets/1254810/11383350/92d5963e-92d5-11e5-9fc1-4ef94ae30213.png)

Might as well match the reds and greens to Coinbase for everything?

![screen shot 2015-11-24 at 6 03 45 pm](https://cloud.githubusercontent.com/assets/1254810/11383392/cb9d53f8-92d5-11e5-9e59-a2607d33a147.png)

**Comment by svk31** [comment]
I don't see why we can't have our own colors, and at the end of the day the color scheme is up to the hosting party anyway, like OL has different colors for most things. I'll make the zeros less prominent at least.

**Comment by wmbutler** [comment]
Closing and letting this be handled by #538
