### ISSUE TITLE
Market Volumes in the Same Unit

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#529]
Currently, market volume stats have different units depending on pairs. This is really confusing and incorrect. IMO, all market volume should be converted into BTS.

**Comment by svk31** [comment]
Yes, I initially wanted to at least sort them by BTS equivalent value, or do it like you say, but the conversion component was broken. I've since fixed it so I could add this now. Anyone else have an opinion on this issue?

**Comment by svk31** [comment]
Does it make sense to show BTS volume for a market like BTC:USD for example though?

**Comment by wmbutler** [comment]
This is a tough issue. Wonder if @bytemaster might weight in on this.

**Comment by kenCode-de** [comment]
I think this is the component mentioned above: https://github.com/cryptonomex/graphene-ui/blob/master/web/app/components/Utility/EquivalentValueComponent.jsx
