### ISSUE TITLE
Support for high latency connections

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene-ui#530]
This guy has a satellite connection and can't get passed init-error due to high latency
https://bitsharestalk.org/index.php?topic=20185.msg259870;topicseen#new

**Comment by wmbutler** [comment]
Fringe case, but worth a peek if it's just the initial load. I doubt this is a simple setting of MAX_LATENCY. Pushing this to late December for discussion.

**Comment by wmbutler** [comment]
This is a limitation of sockets and probably not worth the effort.
