### ISSUE TITLE
Issued Assets are not displaying, sometimes

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#531]
In the Linux Light Wallet, v2.0.151119 click on an account that has registered at least 1 UIA. 
Then click on Assets in the left menu. 
No assets show up in the main frame panel (sometimes). 
I can't figure out how to reproduce this error. Sometimes my uia's show up, sometimes they don't.

**Comment by wmbutler** [comment]
Still having issues or is this resolved with 1125 @kenCode-de ?

**Comment by kenCode-de** [comment]
The assets are showing now. Tomorrow, who knows..

**Comment by wmbutler** [comment]
Re-open if you need to. Closing.
