### ISSUE TITLE
Blocktrades Bridge bug?

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#535]
Is this a bug? 
http://i.imgur.com/M7tCEyy.png

**Comment by dnotestein** [comment]
The older version of this page defaulted to LTC rather than BTC. Is that what you mean? If so, the updated version of the code defaults to BTC pricing info now. If it's something else at issue, please let me know.

**Comment by kenCode-de** [comment]
No, sorry I mean the fields look like they have been duplicated. I'm confused, are those fields supposed to be displayed twice like that?

**Comment by svk31** [comment]
Does not seem to happen any more, closing
