### ISSUE TITLE
Create New Account should hide after clicking on "plus-circle"

### ISSUE THREAD

**Issue by b33lz38v8** [cryptonomex/graphene-ui#536]
![image](https://cloud.githubusercontent.com/assets/15835208/11412563/456eeeae-93ac-11e5-90e9-16a9138e4a00.png)

**Comment by svk31** [comment]
There was an old issue for this that I guess got closed. I was never able to reproduce this myself though.

**Comment by wmbutler** [comment]
It used to be a bug but it's def gone now!
