### ISSUE TITLE
Additional Information on Buy/Sell Button

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#537]
Now, buy and sell button is confusing because the buttons don't tell what asset is sold or bought.
So, we can enhance these buttons by adding targeted asset.

For example, in BTS:BTC market, Buy -> Buy BTS, Sell -> Sell BTS.
In BTC:BTS market, Buy -> Buy BTC, Sell -> Sell BTC.

**Comment by wmbutler** [comment]
I think this is a great idea. Right now the only way the user knows which asset they are purchasing is from the Buy line. It would be nice to reinforce which asset is being purchased.

Current Look:
![screen shot 2015-11-26 at 9 17 48 am](https://cloud.githubusercontent.com/assets/1254810/11424865/aa95ed1a-941e-11e5-95e3-b92543702e61.png)

Proposed Look:
![screen shot 2015-11-26 at 9 28 42 am](https://cloud.githubusercontent.com/assets/1254810/11425077/1ffd9980-9420-11e5-9a6c-39a1b79edb35.png)

**Comment by svk31** [comment]
I remember why I removed this now: 
![image](https://cloud.githubusercontent.com/assets/6890015/11430880/9b47b5f4-948d-11e5-9714-7271d76f50d7.png)

**Comment by wmbutler** [comment]
I'll keep working on this... there should be an elegant solution.

**Comment by wmbutler** [comment]
See most recent UX for #538. Marking this as a duplicate.
