### ISSUE TITLE
Turkish ui buttons stop responding.

### ISSUE THREAD

**Issue by bitsacer** [cryptonomex/graphene-ui#539]
I switch it few times between EN and TR and on TR buttons dont respond , specially membership and permissions but generally almost all gets stuck, not responding

**Comment by wmbutler** [comment]
Confirmed. Reproduce:
- Change language to Turkish
- Go to Dashboard
- Pick and account card
- Click on Membership (3rd one down)

![screen shot 2015-11-26 at 9 38 22 am](https://cloud.githubusercontent.com/assets/1254810/11425271/aa70951c-9421-11e5-9e40-78abfd668464.png)

**Comment by bitsacer** [comment]
see here https://youtu.be/l2EXbcH93d0 , lightwallet in Turkish not responding

**Comment by svk31** [comment]
The reason for this was that you had translated the links inside the help files, see my changes in the above commit and you'll understand what I mean.

**Comment by wmbutler** [comment]
@bitsacer please review for future pull requests.

**Comment by bitsacer** [comment]
Is every square bracket a link or only those with hashes ? Because if thats the case I need to fix the rest.

**Comment by bitsacer** [comment]
square bracket-translatable link name-square bracket(non-translatable/path-to/filename.md) I thought this was what a link looks like

**Comment by bitsacer** [comment]
Hi,  I have made changes on transifex but they dont show on github as it used to .

iPhone'umdan gönderildi

1 Ara 2015 tarihinde 20:55 saatinde, Sigve Kvalsvik notifications@github.com şunları yazdı:
