### ISSUE TITLE
Not Collected For Translation

### ISSUE THREAD

**Issue by bitsacer** [cryptonomex/graphene-ui#540]
These have not been collected for translation
Boxes on trading view, "BORROW USD", "INDICATORS"
On explore window new addition FEES
Fees section ,
"fauacet adress"

**Comment by rngl4b** [comment]
My bad, github <--> transifex integration server has been down for a couple of days. It's fixed now, new contents                   should be available on transifex.

Besides that, in this fast commit/release stage some fix and feature branches may be merged into Master (from where we pull language sources) very close  to the release time. In such cases it's more likely to have those translations available one release behind.

**Comment by wmbutler** [comment]
ok, so are we good here? Please close if yes.

**Comment by rngl4b** [comment]
My bad, github <--> transifex integration server has been down for a couple of days. It's fixed now, new content is available on transifex.

Besides that, in this fast commit/release stage some fix and feature branches may be merged into Master (from where we pull language sources) very close  to the release time. In such cases it's likely to have some translations available one release later.

**Comment by rngl4b** [comment]
By the way, I would not suggest any change to the development process to improve translation timing at this point, as it will be solved when a Stable branch becomes appropriate.
