### ISSUE TITLE
core_exchange_rate should be setable to zero when creating an asset

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene-ui#543]
https://bitsharestalk.org/index.php/topic,20263.msg260990.html#msg260990

**Comment by wmbutler** [comment]
@jcalfee is this one in your realm? Moving to 1216.

**Comment by svk31** [comment]
Seems xeroc was mistaken and it's not actually possible to set a zero or null cer. I've added the ability to set the CER on creation however, and also hid the asset selection in asset update for assets that have a valid (CORE + the asset to update) combination of CER assets.
