### ISSUE TITLE
Active account name is missing on the top toolbar of the market page

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#545]
[Chrome/Win7]
[release 151125]

When you access a market from explorer/markets, the market page is not displaying the active account name.

![05](https://cloud.githubusercontent.com/assets/11573977/11430529/594179b0-9488-11e5-9abc-a65918f3c023.png)

**Comment by svk31** [comment]
It's an account selector so it only appears if you have more than one account.

**Comment by svk31** [comment]
That being said we should rethink the relationship between followed accounts and linked accounts, currently any account you browse to becomes your current account, which shouldn't be the case. Imo current accounts should only be chosen from accounts you control.

**Comment by neura-sx** [comment]
Nope, the behavior I described is clearly a bug. When you reload the page the active account name shows up on the top toolbar as it should. It just fails to show up when you access the page from explorer/markets.

**Comment by wmbutler** [comment]
So, let's work this one as a bug, but I still kind of like the idea of allowing a user to star accounts and have only the starred accounts show up in the dropdown. It puts the power in the hands of the user.

**Comment by svk31** [comment]
Ah yea I think I see why this is happening, the current "active route" implementation is a bit hacky. Ideally we'd upgrade to react-router v1 which would simplify things but it breaks a lot of things unfortunately.
