### ISSUE TITLE
Unnecessary scroll-bars on the Create Asset confirmation screen

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#547]
![06](https://cloud.githubusercontent.com/assets/11573977/11431152/2737fc46-9492-11e5-83ab-425567ca603e.png)

**Comment by c055** [comment]
windows, right?

**Comment by neura-sx** [comment]
Yes, Chrome / Win7

**Comment by wmbutler** [comment]
Easy fix for 1209.
