### ISSUE TITLE
Misplaced layout for asset details page

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#548]
Firefox / Win7
release 151125

All elements are there but there is huge vertical spacing between them.
Happens in FF only, in Chrome works fine.

![ass](https://cloud.githubusercontent.com/assets/11573977/11432054/06a36f42-94a6-11e5-9110-f8f7082f0cf1.png)
![ass2](https://cloud.githubusercontent.com/assets/11573977/11432053/06a31fd8-94a6-11e5-83d5-b6c5a5c1fa79.png)

**Comment by wmbutler** [comment]
I would vote to roll this into #474 and put a Browser Not Supported here until we can fully support. Seems to me like we need to focus in on one browser for now and then roll browser support out after we add features. It's not that big of a deal to say we only support Chrome for now. Unless there are some flavors of UNIX without a Chrome Browser.

**Comment by wmbutler** [comment]
Close if you are ok with this as a compromise @neura-sx

**Comment by neura-sx** [comment]
I'm OK.
