### ISSUE TITLE
Unstyled (or misplaced) UI elements on the market page

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#549]
Firefox/Win7
2.0.151125

There are probably unintended (or badly styled) UI elements as part of the text input fields.
Happens only in FF/Win 7, in Chrome those elements do not show up at all.

![ff](https://cloud.githubusercontent.com/assets/11573977/11432149/164e5ea0-94a8-11e5-9a4f-41a42696f9ab.png)

**Comment by wmbutler** [comment]
That's how FF handles number fields. This falls under #474 in IMO. I really hope you agree. @neura-sx

**Comment by svk31** [comment]
It's due to a CSS hack to remove the up/down arrows that apparently FF ignores, I can have a look to see if there's also a FF version.

**Comment by neura-sx** [comment]
I agree with wmbutler. So it's up to svk to close this issue if there is no easy solution for the CSS hack.
