### ISSUE TITLE
Empty price history chart for small time intervals

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#550]
FF/Chrome on Win7
2.0.151125

When you choose very small time intervals, the price history chart is completely empty. It should show a row of empty candles, not empty space. It's very confusing for the user on low liquidity markets - s/he expects to see a chart and there is just empty space.

![empty](https://cloud.githubusercontent.com/assets/11573977/11432193/f1c8324e-94a8-11e5-915d-60c55ed5e0af.png)

**Comment by wmbutler** [comment]
#474 Let's stop FF support for now, at least until we get things working perfectly in Chrome.

**Comment by neura-sx** [comment]
This an issue not related to a particular browser - I see it in both FF and Chrome.

**Comment by wmbutler** [comment]
How about this for a UI solution.

![screen shot 2015-11-28 at 5 35 44 am](https://cloud.githubusercontent.com/assets/1254810/11451365/f4beef30-9591-11e5-9fd0-c883c18a0267.png)

**Comment by neura-sx** [comment]
A placeholder saying "NO MARKET DATA" is only valid when there haven't been any trades yet or there is some other reason for the last trading price to be unknown.

But when the last trading price is known (and it's always the case when there has been at least one trade in the past) - then the standard solution is to draw empty candles. And this is what I suggest.

**Comment by wmbutler** [comment]
I see your point. Empty candles at the last price traded. Thanks for the clarity. Placing this in the current sprint as a bug...not a killer bug but a bug.
