### ISSUE TITLE
Misplaced line below My History headers

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#551]
Chrome/Win7
2.0.151125

This is a cosmetic bug - there is a fragment of a random line below My History headers.
Happens only in Chrome, in FF this line is placed properly.

![line](https://cloud.githubusercontent.com/assets/11573977/11432230/a6f4850a-94a9-11e5-823a-cbb6d68c4d42.png)

**Comment by wmbutler** [comment]
Confirmed bug. This happens when there are 0 items in My History.
