### ISSUE TITLE
Orders page is completely empty

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#552]
When i have no open orders this page should say something like "You have no open orders".
Otherwise it looks like something is wrong.

It could also say something like this "To place orders you need to go to markets" and refer the user to the explorer/markets page.

![space](https://cloud.githubusercontent.com/assets/11573977/11439268/9b3dba14-94fa-11e5-9e3d-f9599dd77dd8.png)

**Comment by clayop** [comment]
The account test78 has no orders.
http://cryptofresh.com/u/test78

**Comment by wmbutler** [comment]
![screen shot 2015-11-28 at 5 43 39 am](https://cloud.githubusercontent.com/assets/1254810/11451398/041eb9f0-9593-11e5-9b51-10c1a87db59f.png)

**Comment by neura-sx** [comment]
I'd make this text a bit smaller - just use the normal font size (and please without capital letters).

**Comment by wmbutler** [comment]
I'll leave that to @svk31
