### ISSUE TITLE
Vertical space on the market page is not used effectively

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#553]
Could we have the price history chart take up more vertical space when this space is available?
As we have it now, it seems like we are wasting a lot of space while the chart would look much nicer (and more dynamic) if it was able to be higher.

![space](https://cloud.githubusercontent.com/assets/11573977/11443953/defe6c5e-9521-11e5-93f4-9e3780587a57.png)

**Comment by wmbutler** [comment]
Might be nice to have but I'm going to push this out to late January and let there be some discussion first. We have a number of things planned for the market section.

**Comment by neura-sx** [comment]
But can't the chart have a bit of flexibility and expand vertically to some extend WHEN there is empty space below?
I'm sure the modern js layouts are smart enough to figure this out and accommodate to different screen sizes.

**Comment by wmbutler** [comment]
Sure, I just don't see this as a high priority.

**Comment by svk31** [comment]
The design has changed quite a lot since this was opened so I'll close it, reopen if you really think it's still necessary.
