### ISSUE TITLE
Definitions and explanations under voting not collected for translation

### ISSUE THREAD

**Issue by bitsacer** [cryptonomex/graphene-ui#555]
Voting section has few definitions and explanations under tabs that were not collected for translation.

**Comment by rngl4b** [comment]
Can you confirm this is fixed in version 2.0.151202?

**Comment by bitsacer** [comment]
If you are asking me , yes fixed .There is one more thing I noticed, in help go to Bitshares on the left under Table of contents, click Bitshares, those links under "THIS WALLET" dont work . Not in Turkish nor in English, but they work on github's review page.

**Comment by bitsacer** [comment]
Guide strings need to be collected for translation here too : http://docs.bitshares.org

**Comment by wmbutler** [comment]
@bitsacer please close this issue and open a new one. Thanks.

**Comment by rngl4b** [comment]
Created a new issue #593, please close this one.
