### ISSUE TITLE
What does "Settle" mean?

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#556]
RE: Account Overview > Balances 

Guys, this is exactly what I have been preaching about on the forum since day one. Users will request more and more features over time. These features eventually get added, but will also clutter up the UI so bad that nobody knows what does what. 

It took me a decade to refine my Tek9 Pro eBusiness software to the point where my grandma could use it, even after we had added over 400 new features. 

The only way to have 400 new features in our existing UI is start using color, breadcrumbs, a lighter theme, Outlined menu flow, more tooltips, and PLEASE, for the love of my grandma, think of her (and the degraded quality of her vision!) when you release a new UI.

**Comment by svk31** [comment]
Settling is a core mechanic of Bitshares 2.0 market pegged assets. It lets you request settlement of your assets (USD, CNY, etc) at feed price 24hrs later. It is a way of ensuring holders of bit assets can get them converted to BTS at a fair price regardless of the current market status.

**Comment by kenCode-de** [comment]
Ok, well how is my grandma supposed to know that? Right now, it's just a button that doesn't explain any of that to her. I want mass adoption of BitShares.

**Comment by svk31** [comment]
Your grandma will have to use another wallet in my opinion, something built from the ground up to be simple and accessible, which will not provide access to all features like this reference implementation has to do.

**Comment by wmbutler** [comment]
@kenCode-de settling is sort of a hornets nest right now anyway. Ultimately, I'd hope this could go to a buy/sell BTS screen which I've UX'd but this issue won't be solved in even the next month. There are a lot of politics on this topic.
