### ISSUE TITLE
Deposit/Withdraw needs a drop-down select menu, not tabs

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#557]
My grandma has no idea what a bridge or a gateway is and could care less. How about some tooltips, or color, or even an onscreen text (font size=1) explanation of what each item is..

Also, right now the wallet only supports Blocktrades, CCEDK, Metaexchange and Transwiser. 

What happens when we support 15 different bridges and gateways? Well, guess what, now more time and money must be spent to rearrange the page all over again. Or, were you planning on a page where we must start scrolling sideways to view them all? 

Sorry for being so brash, but I mean come on.

**Comment by svk31** [comment]
Please don't open issues like this without looking at existing issues, there's already an issue dealing with the deposit change that includes mockups of how we envision it should look after revamp.

**Comment by kenCode-de** [comment]
I know that. My point is that time and money were spent to do it wrong FIRST. Do it right the first time and we all save time and money.

**Comment by wmbutler** [comment]
Then contribute to the discussion on the issue itself please.
