### ISSUE TITLE
The new "Net Worth" number in top-right corner

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#559]
There is no need to start cluttering the main menu bar with our net worth number, or whatever else users start asking for. 

I had no idea what that number was until I noticed that it matched the number in my Account Overview balances. This screen is enough, don't start cluttering the UI having that same number in multiple places. 

A tooltip here would be nice as well. Remember, my grandma is not a geek.

**Comment by wmbutler** [comment]
My thought here was that it should be the total net worth of all accounts in your wallet in your currency of choice. We are getting there but not quite there yet.
