### ISSUE TITLE
Problem with last update

### ISSUE THREAD

**Issue by SteemitFbAdmin** [cryptonomex/graphene-ui#563]
Since the last update, whenever I got to a market, I cannot scroll down like I use to. 

Neither the mouse roll or trying to click on the side to scroll down works.

The only way I found to put a buy or sell order is by using TAB.

I use chrome with Windows 10

**Comment by wmbutler** [comment]
This is the first I've heard of this. Can any other Windows users confirm? Please update Chrome to the latest version, quit, reload and try again. Report back if you could. Also, reply with your specific version of Chrome after the upgrade. If there are any Win/Chrome users out there, please post your observations here.

**Comment by SteemitFbAdmin** [comment]
It's back to normal.
