### ISSUE TITLE
This wallet has already been imported

### ISSUE THREAD

**Issue by roadscape** [cryptonomex/graphene-ui#565]
When trying to import from 0.9.3, I'm getting the message "This wallet has already been imported", even though it displays new unclaimed balances.

I don't remember how I imported the account in the first place.. it was possibly from a pasted private key. So this might be an edge case but I'd like to be able to merge my incomplete wallet fragments.

**Comment by jcalfee** [comment]
You are correct, it stops on the first duplicate key.  You could also see this behaviour if you did not claim a balance but tried to import the same wallet again.  I can enhance it and let it import the wallet if their are new keys and just ignore the duplicates.

**Comment by wmbutler** [comment]
@jcalfee is 1202 ok for this?

**Comment by roadscape** [comment]
You guys are awesome, thanks :)
