### ISSUE TITLE
Theme / Skin Switch for Dark & Light theme on GUI settings 

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#576]
(or as alternaitve on top right nav)

**Comment by c055** [comment]
i can do the light skin part .. but maybe i would need some assistance on the js settings switch part ..

**Comment by wmbutler** [comment]
ok, late December

**Comment by jonnybitcoin** [comment]
Is there any way the less technical amongst us could try out different styles and colours of the gui by making small changes. this would be great for those looking to host there own exchanges/gateways and want to differentiate between others.

**Comment by c055** [comment]
yep .. this shouldn't be a problem at all, as each skin use its own .scss file ..
(just some chart styles have to get exported to these files as well)

**Comment by c055** [comment]
sry for the delay btw .. had to create a [worker proposal ](https://github.com/cassiopaia/worker-proposals-bts) before.. to be able to continue contributing to BTS related tasks directly again asap

**Comment by jonnybitcoin** [comment]
great did your worker proposal get approved?

**Comment by c055** [comment]
just published before 10 secs :) 

http://cryptofresh.com/workers

Proposal 1.14.28

**Comment by c055** [comment]
new proposal 1.14.28

**Comment by wmbutler** [comment]
@cassiopaia nice, looks like you are going to get it!

**Comment by svk31** [comment]
OK I've just added support for theming, it works by using a mixin `_theme-template.scss` that you simply pass colors to and it generates a new theme. I've tried to add most selectors that use theme colors to the mix-in, but chances are I missed some, so if you see any feel free to move them to the mix-in.

I also added a `colors.js` file that contains some theme colors that are used directly in the javascript and can't be applied through css. Probably some are missing here too, so the same applies.

**Comment by c055** [comment]
nice!

**Comment by jonnybitcoin** [comment]
yay, Is there any way for a layman like me to try out different colours themes?

**Comment by svk31** [comment]
Do you have the GUI running locally in a dev server?

**Comment by jonnybitcoin** [comment]
no I can't get it working locally. Would a digitalocean node droplet be good enough?

**Comment by jonnybitcoin** [comment]
I got it hosted at  http://188.166.149.61:8080/
I've changed some text colours yay! is it just the theme.scss files I should be playing with?

**Comment by c055** [comment]
currently i'm stucking on getting wallet run locally .. :/ have to dive into more ... once this will work i will create a series of colour themes

**Comment by svk31** [comment]
Well you could sure but you'd need to edit the theme colours in the terminal I guess, and make sure you can access the website externally.

**Comment by jonnybitcoin** [comment]
@cassiopaia if you want to access my hosted version via ftp to try out different themes I'll send you the password if you like?

**Comment by c055** [comment]
yea .. before i have to get GUI locally working .. still some local path problems with npm etc .. :/ 
will ping u then

**Comment by cassiopaia** [comment]
cass@bitshares.org

**Comment by jonnybitcoin** [comment]
sent

**Comment by c055** [comment]
got it thx .. will delete mail here... to avoid spam

**Comment by jonnybitcoin** [comment]
same
