### ISSUE TITLE
Remove date/time below price chart

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#578]
Date/Time already exist in navigation bar (under price chart). If we remove the date/time right below the price chart, we can save more space.

**Comment by svk31** [comment]
I'm not sure I agree, since the dates in the navigator are not very visible and too spaced out. Either way this will no longer be relevant once we replace Highstock with react-stockcharts. I won't be spending much time changing the exchange charts until that transition is complete.

**Comment by c055** [comment]
makes sense -- love react charts :) eager to see them in action
