### ISSUE TITLE
[Lite wallet] - All website links result in broken pages

### ISSUE THREAD

**Issue by wildbunny** [cryptonomex/graphene-ui#581]
If you click on visit website for blocktrades, or metaexchange in the deposit/withdraw section, the resulting pages open in some weird hybrid browser which doesn't appear to support javascript, or at least doesn't support angular.js

Can we change this so the website links actually open in the user's real web browser?

**Comment by wmbutler** [comment]
I'd classify this as a high priority bug.

**Comment by kenCode-de** [comment]
Agreed.. It does appear to be JS related too. 

I think it would be better to load up the computer's default browser, not Electron, but the full-on browser itself like Chrome, with the tabs and everything.

**Comment by wmbutler** [comment]
Agreed.
