### ISSUE TITLE
Failed to broadcast the transaction (now <= trx.expiration)

### ISSUE THREAD

**Issue by roadscape** [cryptonomex/graphene-ui#583]
Running a local web wallet, freshly updated, and my balance claims keep expiring.

This happens when I try to broadcast as little as 6-7 total claims.

**Comment by jcalfee** [comment]
It sounds like this happens every time.  Here is my post on the topic(below).  I wonder, can you get it to go through if you set your clock to GMT+5?

> Maybe it is a time zone problem.  The server is in GMT+5 (Eastern Standard Time), you can put your clock to EST.

https://bitsharestalk.org/index.php/topic,20081.msg258550.html#msg258550

**Comment by jcalfee** [comment]
You could also try in the console to expire in 15 minutes instead of 15 seconds. 

``` js
chain_config.expire_in_secs = 15 * 60
```

**Comment by wmbutler** [comment]
@roadscape also, is your time on your local computer synced to an ntp server?

**Comment by jcalfee** [comment]
> The time for my BTS claim from broadcasting to expiring is 120 seconds.

Wow, this is over 3g?  Still only 6 or 7 claims?

**Comment by 38PTSjuggler** [comment]
I tried to change the system time without success. Where can I change that ?:chain_config.expire_in_secs = 15 \* 60 

Do you mean in developer tools in the browser? If yes, where?

**Comment by roadscape** [comment]
@wmbutler - I'm using OSX, which I believe uses ntp by default

@jcalfee - this worked!! thanks!

```
chain_config.expire_in_secs = 15 * 60
```

---

I set the expiration back to 15 seconds and I started profiling the page right before clicking 'Claim Balance' and ended right when I got the expiration message. From clicking the button to getting the error was approx 60-90s.. so it's definitely hanging on something. 

Here's the profile, hope it helps:

![screen shot 2015-12-04 at 12 33 40 pm](https://cloud.githubusercontent.com/assets/5168676/11597788/889fa8ac-9a83-11e5-87d7-63993b01fe6c.png)

**Comment by roadscape** [comment]
@38PTSjuggler - if you are using chrome on android...

Go to the claim balances page and **paste this into the URL bar**:

```
javascript:chain_config.expire_in_secs=15*60;alert('it works!');
```

And hit 'Enter' (or "Go") as if you were loading a website. Now try importing, it should work.

**Comment by wmbutler** [comment]
@svk31 do we need to bake this into the next revision? If so, remove the question tag please. Thanks.
