### ISSUE TITLE
Total Value in header

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#584]
@svk31 this is a bit of a challenge, but a worthwhile one I believe. Can you display in the header the total value of all asset types?

For instance, if I own USD / CNY / GOLD / BTS, can you display the estimated value of all those assets in the desired asset type? I understand that it's probably a challenge, but it would be pretty awesome to be able to see the net value of your account across all asset types.

**Comment by kenCode-de** [comment]
I think @svk31 did this one already :)

**Comment by svk31** [comment]
Yes, if I understand you correctly that's how it works already after my previous changes. It shows the total for all assets that you own over all accounts for which you have the private keys in your current wallet.

**Comment by wmbutler** [comment]
ok, I think I see what's going on here. Don't you think it would also make sense to display values for:
- [x] assets locked up on buy/sell orders
- [x] collateral positions

As it stands I have a number of each of those and so my balance is severely off.

**Comment by svk31** [comment]
Yes I think I should be able to add that as well.

**Comment by svk31** [comment]
I should probably subtract the outstanding debt from margin positions as well no?
