### ISSUE TITLE
15s view in BTS:USD

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#587]
Just hoping to make some incremental improvements here. You can see that there is a dark horizontal band an a few tick marks on the left side. This seems like a scaling / math issue coupled with some highcharts magic.

![screen shot 2015-12-04 at 3 22 54 pm](https://cloud.githubusercontent.com/assets/1254810/11600502/1af497dc-9a9b-11e5-8eaa-cb530d3f840e.png)

**Comment by svk31** [comment]
The issue here is that since there's no data I just show a straight line for the latest price over the interval that was checked for data. There's also a straight black line from the current price indicator (you're missing the label though for some reason). They overlap which makes for a thick line, but not much to be done about it tbh. As long as there's no data but we want to show the latest price there's not much to be done I think.

**Comment by wmbutler** [comment]
I think this should show dashes at the last price level known....

 `- - - - - - - - - - - - - - - - - - - - - - - -`

It would be great if the straight black line did not exist. Sounds like you are saying there is a technical hurdle with this. What if we change the background color to the same color so we don't see it :+1:

**Comment by svk31** [comment]
From what I can see it already does pretty much what you're suggesting, could you have another look pls?

**Comment by wmbutler** [comment]
Here is BTS:USD at 15s intervals. It should have `-  -  -  -` evenly spaced across the screen at 15s intervals and not have the black horizontal line. I'm fine consolidation this all under the react stock chart enhancement though. Let me know how you'd like to proceed.

![screen shot 2015-12-07 at 7 27 17 pm](https://cloud.githubusercontent.com/assets/1254810/11644269/93e1224e-9d18-11e5-89cc-1a06228b24fd.png)

**Comment by wmbutler** [comment]
this can happen after we switch to react charting.

**Comment by clayop** [comment]
Glad to here to switch to react charting. But please make sure that users can choose time intervals they want. From feedback from traders, 15s, 1m, 3m are meaningless in crypto market. He suggested me 5m, 15m, 30m, 1h, 2h, 4h, 1d, 1w.

**Comment by svk31** [comment]
These have to be set in the witness node config, the GUI will display whichever ones are available from the witness node it's connected to.
