### ISSUE TITLE
Dashboard makeover

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#590]
I think the dashboard screen needs a makeover. Here is my justification:
- Wallet holders need to be able to star their most used accounts. Starred accounts should show up in the dropdown on the trading page. This ultimately gives users more flexibility and control.
- The card view is gitchy but not particularly functional. I think that all a user needs to know is the balance of that account in their chosen currency. Maybe eventually each account could have a pref for currency but not really sure how much ppl will care about that.
- Need to be able to filter accounts
- Need to be able to sort accounts
- It is not necessary to see the "icon" for the account on the dashboard
- Clicking on star in header sorts starred accounts to top

![screen shot 2015-12-05 at 2 15 19 pm](https://cloud.githubusercontent.com/assets/1254810/11609660/a427331a-9b5a-11e5-90cd-13557b82ac8a.png)

**Comment by svk31** [comment]
Agreed. We could add some more info to the table perhaps, "In open orders", "In collateral" maybe?

**Comment by wmbutler** [comment]
Well, the problem as I see it is that there might be variable amounts of information, which would mean we couldn't reliably display at a fixed row height. I think simply displaying the value would be preferable for this reason.

For instance, I could have 15 different collateral positions in an account right? How could you ever responsibly display this on the account list?

**Comment by svk31** [comment]
Yea I just meant the total value of the BTS locked in collateral, and the total value of all assets in open orders. In your preferred unit. So it would still just be one line.

**Comment by wmbutler** [comment]
Something like this?

![screen shot 2015-12-05 at 2 56 38 pm](https://cloud.githubusercontent.com/assets/1254810/11609888/6998cba4-9b60-11e5-8c1e-f9e75235be62.png)

**Comment by svk31** [comment]
Yep something like that :) Maybe "As collateral" or "Locked as collateral" would be more clear?

**Comment by jonnybitcoin** [comment]
can it show last account overview by default when clicking on dashboard

**Comment by wmbutler** [comment]
What do you mean "last account overview"?

**Comment by jonnybitcoin** [comment]
dashboard shows all your accounts. click an account and it will show you an overview of that account. 
I'm saying everytime you click dashboard it should remember your last account overview and show it by default.

**Comment by wmbutler** [comment]
Instead of the list? I'm not sure I agree. Remember, your most recent account is active in the dropdown...

**Comment by svk31** [comment]
I supppose you want users to be able to star accounts elsewhere? As in the Account section for example, or from the account search in explorer?

**Comment by wmbutler** [comment]
@svk31 no, I was just thinking all accounts would appear here and you could star or unstar them which would make them appear/disappear in the dropdown.

**Comment by wmbutler** [comment]
Unstarred accounts would still be here, they would just be light gray stars instead of yellow stars.

**Comment by svk31** [comment]
Hm ok, I think it would be nice to be able to not show some accounts in the dashboard myself, quite a few people would like to hide their collateral-holder-x accounts for example. We could show an overview that includes all your accounts in the settings for example so that users could find them again once hidden.

**Comment by wmbutler** [comment]
Seems like an extra screen to me. I have a LOT of collateral accounts and I'd be fine if they were just sorted to the bottom. It would be a lot easier to just have one screen from a programming standpoint too.

Maybe you could also reduce the contrast on the account when it's unstarred... since the user can sort by starred accounts, it would be like they weren't there at all.

**Comment by svk31** [comment]
OK that works for me

**Comment by wmbutler** [comment]
I would drop the:
- 'as collateral' for just 'collateral'
- 'in open orders' for just 'open orders'
