### ISSUE TITLE
Example not clear Documentation of account/permissions and general introduction things

### ISSUE THREAD

**Issue by bitsacer** [cryptonomex/graphene-ui#594]
Documentation of account/permissions and general introduction things- - Multi-Hierarchical Flexible Multi-Signature

**Comment by bitsacer** [comment]
Controller(33%) or Treasurer(33%) together with(+) wither(?) the Tax Manager (10%) or Accounting (10%) to(=) spend funds(43%). < 51%

**Comment by wmbutler** [comment]
I don't understand the question. @xeroc @cassiopaia can you offer any help?

**Comment by bitsacer** [comment]
maybe I am wrong ? there is an example in Help, permissions.md, Multi-Hierarchical Flexible Multi-Signature, have a look at it . I just could not understand it .

**Comment by rngl4b** [comment]
"wither" is a typo, I'll create a PR now. The example is ok, any combination of account weights that sums 51% can approve a transaction, i.e. Chief alone, Treasurer + Controller, Treasurer + Tax Manager + Accounting, or Controler + Tax Manager + Accounting.

**Comment by bitsacer** [comment]
thats what I am saying,  the last "or" should have been "and" (+) .  

"Controller or Treasurer together with wither the Tax Manager or Accounting to spend funds."

**Comment by bitsacer** [comment]
@rngl4b ..together with Tax Manager and Accounting to spend...

**Comment by rngl4b** [comment]
You are right, missed that. #596

**Comment by bitsacer** [comment]
can I close this one ?

**Comment by rngl4b** [comment]
Yes please, thank you for the advise.

**Comment by bitsacer** [comment]
cheers
