### ISSUE TITLE
Electron light wallet --data-dir param

### ISSUE THREAD

**Issue by testzcrypto** [cryptonomex/graphene-ui#602]
Please add possibility to specify electron light wallet data directory where to keep wallet data. In current version all data stores at %APPDATA%\BitShares2-light (under Windows).

**Related links:**
https://www.chromium.org/user-experience/user-data-directory
https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname
https://github.com/atom/electron/issues/647
https://github.com/atom/brightray/pull/89

**Comment by wmbutler** [comment]
I'm not convinced this is an issue. @svk31 ?

**Comment by svk31** [comment]
I have no idea how the electron stuff works, @valzav can you take this one please?

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#27
