### ISSUE TITLE
Unable to pay BTS as fee for transfer with light wallet 2.0.151209

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#608]
Screenshot attached.

![transfer-gui](https://cloud.githubusercontent.com/assets/9946777/11812419/1a5f2c8e-a33c-11e5-9aae-ea7a656ba0c7.png)

**Comment by svk31** [comment]
Is this still an issue with the latest version?

**Comment by abitmore** [comment]
It seems to have been fixed in v2.0.151216.
