### ISSUE TITLE
Firefox browser unsupported

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#610]
I am getting the following message when I go to bitshares.openledger.info

```
Unsupported browser

The Browser you are using has not been fully tested to support the Bitshares Wallet. We highly recommend that you backup your wallet and import it using the Chrome Browser until we have had more time to fully test your browser of choice. Use at your own risk.

Google Chrome
```

Here is relevant system information:

```
$ cat /etc/issue
Ubuntu 14.04.3 LTS \n \l
$ dpkg -l | grep firefox
ii  firefox                                     42.0+build2-0ubuntu0.14.04.1            amd64        Safe and easy web browser from Mozilla
ii  firefox-locale-en                           42.0+build2-0ubuntu0.14.04.1            amd64        English language pack for Firefox
```

My user-agent string:

```
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0
```

Firefox from official repository on Ubuntu LTS release is not in any way an unusual platform.  Is Firefox really unsupported, or is it just not properly detecting my browser?

**Comment by valzav** [comment]
Yes, currently we display this for all browsers except Chrome because we had resources to test it in Chrome only.

> On Dec 16, 2015, at 1:38 PM, theoreticalbts notifications@github.com wrote:
> 
> I am getting the following message when I go to bitshares.openledger.info
> 
> Unsupported browser
> 
> The Browser you are using has not been fully tested to support the Bitshares Wallet. We highly recommend that you backup your wallet and import it using the Chrome Browser until we have had more time to fully test your browser of choice. Use at your own risk.
> 
> Google Chrome
> Here is relevant system information:
> 
> $ cat /etc/issue
> Ubuntu 14.04.3 LTS \n \l
> $ dpkg -l | grep firefox
> ii  firefox                                     42.0+build2-0ubuntu0.14.04.1            amd64        Safe and easy web browser from Mozilla
> ii  firefox-locale-en                           42.0+build2-0ubuntu0.14.04.1            amd64        English language pack for Firefox
> My user-agent string:
> 
> Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0
> Firefox from official repository on Ubuntu LTS release is not in any way an unusual platform. Is Firefox really unsupported, or is it just not properly detecting my browser?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/cryptonomex/graphene-ui/issues/610.

## 

Regards,
Val

**Comment by wmbutler** [comment]
Closing but we know this needs to be a priority after base features and bugs are in place.
