### ISSUE TITLE
Unergonomic toggle between Table View and Card View

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#613]
Those two complementary buttons are on the opposite sides of the screen - which is bad UX.

![cv](https://cloud.githubusercontent.com/assets/11573977/11877896/7088d2e2-a4f2-11e5-9019-18ff4fe867a2.png)

![tv](https://cloud.githubusercontent.com/assets/11573977/11877899/7326c8d8-a4f2-11e5-8d64-6d86018eedcb.png)

**Comment by wmbutler** [comment]
Let's keep the toggles on the right side.
