### ISSUE TITLE
Enhancement - Trade UI - Consider removing the "favorite" stars from "My Markets" tab and make them visible only when hovering. Reduces bloat

### ISSUE THREAD

**Issue by ValentinJesse** [cryptonomex/graphene-ui#621]
Something similar to this:

![2015-12-21_13-45-18](https://cloud.githubusercontent.com/assets/7979136/11930107/4891edce-a7e9-11e5-926c-881e3eb604ed.png)

**Comment by wmbutler** [comment]
Not sure I understand. The star indicates that it's a favorite.

**Comment by svk31** [comment]
He wants the stars to be hidden unless you hover over a market.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#28
