### ISSUE TITLE
Enhancement - Trade UI - Consider removing the *** .table>tbody>tr>td { border-bottom: 1px solid #ddd;} *** Reduces bloat and eye strain (+ pics)

### ISSUE THREAD

**Issue by ValentinJesse** [cryptonomex/graphene-ui#622]
From this
![2015-12-21_13-56-11](https://cloud.githubusercontent.com/assets/7979136/11930276/a2b74212-a7ea-11e5-910f-b8bce4acdbb7.png)

To this
![2015-12-21_13-54-58](https://cloud.githubusercontent.com/assets/7979136/11930279/a6470796-a7ea-11e5-86a7-1b5412e69451.png)

**Comment by c055** [comment]
we should reduce the border noise all over the market page as well .. IMO with small changes we would gain a big eye pleasure effect ...

**Comment by valzav** [comment]
I'm not sure it's good idea to remove horizontal lines at all - they help eyes to scan table rows. Probably making them less visible (darker) would be enough.

**Comment by c055** [comment]
yep sry .. my fault, ment this .. !

**Comment by wmbutler** [comment]
I agree with @valzav I'd keep them and go lighter as a compromise. Personally I like them as is. But I UX'd it :)

**Comment by svk31** [comment]
This looks quite different now so I'm closing it,  but feel free to open a new one if you still see possible improvements after the next release.
