### ISSUE TITLE
How do I withdraw bitBTC to my friends BTC address?

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#623]
I have bitBTC. 
One of my employees wants to be paid in BTC (he does not use Bitshares). 
How do I use the Withdraw screen to send him my market-pegged bitBTC so that it will be converted on-the-fly? 
He wants exactly 1BTC, so I need AT LEAST that much bitBTC (since I have to pay the fees/spread). 

It is not clear to me in the Withdraw screen on how to do that. The Bridge thing needs some UI/UX work for me to make this happen for him, please.

**Comment by c055** [comment]
when you want to withdraw BTC then u sould use blocktrade and trade tradeBTC to BTC ..

**Comment by kenCode-de** [comment]
Well, I'm trying to avoid relying on any centralized exchanges like OPENBTC, and UIA's like tradeBTC, etc. 

We have a bitBTC Smartcoin and I would like to start using it extensively to move money into and out of the wallet easily without relying on a third-party.

**Comment by c055** [comment]
Well, this won't work without any 3rd party .. AFAIK

**Comment by kenCode-de** [comment]
So the DEX will never have its own Gateway so that I can directly deposit BTC to bitBTC either?

**Comment by dnotestein** [comment]
BlockTrades will offer direct BTC to bitBTC (and vice-versa) as bridge options before too long.

**Comment by kenCode-de** [comment]
SWEET! We really need to push liquidity there. I love CCEDK, but I want to utilize as many of our tools as possible too. Thanx!

**Comment by c055** [comment]
ok just to be clear .. blocktrades is also a 3rd party service you would use then .. :)

**Comment by c055** [comment]
will close this issue .. let me know if i should re-open it ..
