### ISSUE TITLE
can't write memo with Chinese char

### ISSUE THREAD

**Issue by pch957** [cryptonomex/graphene-ui#624]
I can transfer with chinese memo from cli_wallet, and it can display correct on web page.
but when I transfer with chinese memo from web wallet, it can't display correct.

**Comment by clayop** [comment]
Korean too.

**Comment by svk31** [comment]
I've looked into this and it appears to be an issue with the decoding. Reassigning to @jcalfee

**Comment by jcalfee** [comment]
@valzav is deploying this fix to the testnet
