### ISSUE TITLE
Button labels and background colors on some of the modals/popups

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#627]
This should be a quick css fix: 
I can't read the text label on some of the popup dialog boxes. It has white-ish text on a light gray background making it impossible to read. 

For example, go to an account's balances overview screen. 
Click on a Smartcoin like BTC or EUR. 
Click Settle. 

The dialog box that pops up has a button on there but I cannot read the text on it. The colors are out of whack. Please and thanx again guys :) ken

**Comment by svk31** [comment]
Think this is OK now.
