### ISSUE TITLE
Market Should support BTS fees for UIA and BitAssets

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#628]
When a UIA issuer forgets to fund the fee pool, users shouldn't be left stranded.  The GUI should always provide an option to pay the fee in BTS.

**Comment by svk31** [comment]
It already does, it defaults to BTS if fee pool has insufficient funds.

**Comment by bytemaster** [comment]
I see, the SELL button gets greyed out due to insufficient funds but doesn't tell the user that is the reason.  I thought it was due to the fee pool being empty.

The numbers should really be displayed with "," in the separators place. At the very least, if the sell button is disabled, a mouseover should explain why.
