### ISSUE TITLE
Improvements aimed at increasing voting participation

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#630]
Voting apathy is a serious vulnerability for the blockchain. It can be assumed that a lot of users don't vote because they don't realize that. These are simple changes that are aimed to alleviate this problem to some extent:

(1) If the system finds out that an account has a balance of e.g. 100k BTS (or more) and is not voting (i.e. no proxy set and there is no support for at least 10 witnesses), it should display a red warning in the footer (just as we have it for the wallet backup reminder).

(2) On the voting page there should be a clear instruction that the easiest way to vote is to select a proxy. To facilitate the choice of proxies a link to this forum board should be offered in the GUI:
https://bitsharestalk.org/index.php/board,104.0.html

(3) It's much easier to vote when you have a list to choose from (as we have it for worker proposals) instead of typing an account name. Currently we cannot compile a list of active proxies but a list of available accounts should be doable for witnesses and committee members.

**Comment by abitmore** [comment]
Better to vote by select/click but not input. Currently only worker proposals are being voted this way.

**Comment by neura-sx** [comment]
@abitmore , very good point. I'll add it to the list above.

**Comment by wmbutler** [comment]
Voting needs a UX overhaul as well. I'll work on this.

**Comment by abitmore** [comment]
Some suggestions in this post: https://bitsharestalk.org/index.php/topic,20962.0.html, too long and unfinished so haven't copy&pasted here.

**Comment by svk31** [comment]
Moved to bitshares-ui
