### ISSUE TITLE
Unable to edit description on asset

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#631]
I want to edit the description on BTSPOS, but the client yields this error in red text: 

Failed to broadcast the transaction: 
base.amount > share_type(0): 

UPDATE ASSET  
Asset to update BTSPOS
Issuer  bitshares-munich
New owner account   -
Core rate   n/a
New options 
root:{} 12 items
max_supply:1000000000
market_fee_percent:0
max_market_fee:1000000000000000
issuer_permissions:79
flags:128
core_exchange_rate:{} 2 items
whitelist_authorities:[] 0 items
blacklist_authorities:[] 0 items
whitelist_markets:[] 0 items
blacklist_markets:[] 0 items
description:This is just a token for testing purposes, it will not be issued or sold.
extensions:[] 0 items
Fee 20.26367BTS

**Comment by svk31** [comment]
That looks like it's related to an invalid core exchange rate, is one of the values set to 0 perhaps?

**Comment by kenCode-de** [comment]
Uuuh, I have no idea what that means, sorry. I have not really used that asset at all, so was hoping to just delete it actually to free up the name.

**Comment by svk31** [comment]
OK I just checked your asset and it does indeed have an invalid Core Exchange Rate (in Primary Settings), so you won't be able to update it unless you fix that.

Either way you can't delete an asset.

**Comment by kenCode-de** [comment]
Hmm, I tried changing "Quote Asset" and then "Base Asset" to BTSPOS and I got the exact same error. What should I change them to? Right now they both say BTS in those quoted fields..

**Comment by svk31** [comment]
Change one of them to be BTSPOS, then set non-zero values for each asset to get an actual price for the core exchange rate.

**Comment by kenCode-de** [comment]
That did the trick, you are AWESOME!! THANK YOU THANK YOU!! :)
