### ISSUE TITLE
Incorrect asset listed in "net worth" tooltip, top-right corner of screen

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#633]
That tooltip says i have: 

DELETIP: 0.00000 BTS 

None of my accounts list that asset, so it should not be showing in that popup tooltip in the top right corner when mousing over my "net worth" number.

**Comment by wmbutler** [comment]
@svk31 do you have enough info to squash this bug? Can you reproduce?

**Comment by svk31** [comment]
Yes I think I know why, should be an easy fix. Balance objects stick around even if they're empty
