### ISSUE TITLE
I can't see the memo texts

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#636]
In the Recent Activity section and if I click on the green Transfer icon, neither section shows me the full memo. I need to see those memos because it is how I keep track of what an expense was for. Please make the memos visible for all transactions. If the memo is too long for the width of the field, then maybe just snip part of it off and hide it, revealing the "more..." link so I can click that to see the rest of the memo text.

**Comment by wmbutler** [comment]
How about a hover tooltip to reveal the memo as a quick fix.

**Comment by kenCode-de** [comment]
Sometimes the memo doesn't show at all. Closing and reopening the linux light client helps sometimes, but not all the time. Most of the time the memo is not displayed. Hard to reproduce to troubleshoot this one, sorry @svk31

**Comment by svk31** [comment]
Most likely your display issues are due to the wallet being locked: the wallet must be unlocked in order to decode memos. I'll see about adding an indication that the transfer has a memo attached but an unlock is needed to see it.

**Comment by kenCode-de** [comment]
yep, that's exactly what it was. you have to click to a different screen to see the change, but that was it exactly. interesting. thanx again @svk31 :)
