### ISSUE TITLE
Adjust CSS style for Select options where size > 1

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#64]
I noticed in our gui when a select options has a size attribute it should vertically become higher by size=N items  (or at least to a reasonable height).  It does not, it stays at only one item high and tries to show a scrollbar.  The CSS property culprit is app.css:{select:  height: 2.4rem}.  I can't find this anywhere and also I'm not sure what might be the best fix.  It would be nice if 2.4rem only applied to selects of size one.  Does anyone know about this?  thanks...

**Comment by valzav** [comment]
I see what you are talking about - there is foundation rule that limits the height of select box. I would suggest to not use size= attribute at all - this way it's going to be a normal drop down.

**Comment by jcalfee** [comment]
Ok .. I'll remove my in-line style like you suggest.
