### ISSUE TITLE
Issues with vesting balance

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#640]
- For witnesses which have 2 vesting objects, the page shows only one object.
- How about the accounts which have a vesting balance caused by the "merger"?
  (I've posted a comment to #500 but I think it's better to open a new issue)

**Comment by svk31** [comment]
The Membership page only shows the cashback vesting balance which is the vesting fees from accounts you've referred/registered.

Merger vesting balances can be claimed by going to Wallet Management Console -> Lookup balances.

However, the others I'm not sure, I see xeroc for example has 3 vesting balances, I'll look into why that is and where we should put their respective claim buttons.

**Comment by svk31** [comment]
I've added a new page to the account page that shows and lets you claim all of your vesting balances.
