### ISSUE TITLE
The "EXPIRATION" column on the "Orders" page is confusing

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#642]
See https://bitshares.openledger.info/#/account/abit/orders/
The "expiration" time makes sense only when the order hasn't been included in the chain.

**Comment by svk31** [comment]
No, this is the actual expiration time of the order. If the order is not filled by that time, it will be cancelled. The expiration time will be user modifiable in the future but for now it's just set to 5 years in the future by default.

See #6
