### ISSUE TITLE
Please make links in the memo field click-able

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#644]
I click on one of the transactions in my Recent Activity, it brings that block's details up in full screen. 
In the memo field of one of the transactions I pasted a hyperlink.. http://..... 
Please link that link so it loads that link in the users default browser like Chrome, IE, whatever.. 
Thank you! :)

**Comment by svk31** [comment]
Not gonna do this for security reasons, someone can send you a memo with a malicious link. If you want to open links you should do so manually.
