### ISSUE TITLE
[Market OL] Bug(?) on display date @  recent history widget

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#648]
<img width="468" alt="bildschirmfoto 2016-01-03 um 01 01 13 1" src="https://cloud.githubusercontent.com/assets/6280810/12076680/b9c27e2a-b1b5-11e5-86bd-2b456409c1b8.png">

**Comment by svk31** [comment]
Is this still happening for you? Cause I can't reproduce it.

**Comment by c055** [comment]
yea

**Comment by svk31** [comment]
Closing this since we've had no other reports of it and I can't reproduce it.
