### ISSUE TITLE
Witness UI does not update when vote change takes effect

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#649]
A bunch of witness votes went into effect shortly after the meltdown just after midnight, Jan. 4, 2016, UTC.  Leaving the witness UI open to the table view left the "Active Witnesses" at 25 in the UI (when it had actually been reduced to 21) and the numbering had gaps, this was fixed on reloading the UI.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#31
