### ISSUE TITLE
STEALTH - Wallet Data Format

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#650]
This issue is designed to document the data the wallet will need to maintain for stealth operations  

```
 {
    "labeled_keys" : [[LABEL,KEY],...], 
    "blind_receipts" : [ {
           fc::time_point                  date;
           public_key_type             from_key;
           string                              from_label;
           public_key_type             to_key;
           string                              to_label;
           asset                              amount;
           string                              memo;
           authority                         control_authority;
           stealth_confirmation::memo_data data;
           bool                                used = false;
           stealth_confirmation       conf;
    },...] 
}
```

The format of stealth_confirmation is defined here:

https://github.com/cryptonomex/graphene/blob/master/libraries/chain/include/graphene/chain/protocol/confidential.hpp#L97-L121

The JavaScript API that needs to be implemented should mirror the C++ API found here:

https://github.com/cryptonomex/graphene/blob/master/libraries/wallet/include/graphene/wallet/wallet.hpp#L727-L799

This should be implemented by creating a ConfidentialWallet class in Javascript

```
   let wallet = new Wallet( ... ) /// create load current wallet
   let cwallet = new ConfidentialWallet( wallet ) /// uses current wallet to store that data defined above
   cwallet.FUNCTION_CALL(...) /// should match the C++ API linked above 
```

To properly implement the cwallet API calls will require making some calls to advanced crypto methods
that are not currently implemented in Javascript.  These methods are defined in c++ here:

https://github.com/cryptonomex/fc/blob/master/src/crypto/elliptic_secp256k1.cpp#L405-L552

For starters we will assume these calls exist, and simply relay them to a C++ node to evaluate and return the result. Then we can replace the RPC calls with Javascript implementations. After we have proven the rest of the system works.

**Comment by xeroc** [comment]
I think this should be referred to in this issue:

https://github.com/cryptonomex/graphene/issues/500
