### ISSUE TITLE
I need a bitBTC (Smartcoin) deposit address

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#652]
In the POS systems, we allow the customer to pay with Bitcoin as well, but it will be sent to the (required) merchant's BitShares account. I love CCEDK (OPENBTC), but I would rather give preference to our own Smartcoins, bitBTC is much preferred. 

The Deposit/Withdraw screen needs a gateway plug for our own DEx, even if just for that single coin right now.  

This lowers our risk and dependence on CCEDK too. (please understand I hold Ronny with the highest respect) 

The POS systems may be launched as early as March so please can we push support for our own Smartcoin in this way asap?

**Comment by xeroc** [comment]
In BitShares there is no such thing as an "address", only account names!

What you could do to allow people to use Bitcoin on the Bitcoin blockchain using the keys the have in the wallet, is to derive a bitcoin address from the BitShares account active key. The private key would allow access to bitcoins on the bitcoin blockchain that way as well.

> The Deposit/Withdraw screen needs a gateway plug for our own DEx, even if just for that single coin right now.

What are you talking about?

> The POS systems may be launched as early as March so please can we push support for our own Smartcoin in this way asap?

What smartcoin are you going to start?

**Comment by kenCode-de** [comment]
I'm sorry but I do not think you understood any of what I am asking for. Can one of the core devs maybe read into this too? Thank you for your understanding xeroc.

**Comment by valzav** [comment]
@kenCode-de OPENBTC is IOU, not smartcoin.
If you want to add your own tab to Deposit/Withdraw and have your own BTC IOU there, just implement it as react component talking to your gateway backend and submit a pull request.

**Comment by kenCode-de** [comment]
All bitcoin accepted at the POS  should go straight to bitBTC. 
Not OPENBTC. 
To accomplish that, we need to generate a btc address, see what  i mean?

**Comment by kenCode-de** [comment]
If somebody wants to send me bitcoin, i would like to send them a btc public address that maps/routes their bitcoin to bitBTC in my bitshares account.

**Comment by dnotestein** [comment]
The problem is that no one is yet offering bitBTC for BTC. It's something BlockTrades plans to do in a little bit, once we have a pricing engine established for it.

**Comment by kenCode-de** [comment]
Well these POS systems will definitely bring the needed volume to the bitBTC smartcoin.

**Comment by kenCode-de** [comment]
I want to attract the bitcoin community to our POS as well, and the map i mentioned above might just do the trick, no? If not, how do we accomplish this?

**Comment by abitmore** [comment]
Like CCEDK (acts as a bridge, or in your word a map/route) who can convert BTC (of bitcoin network) to OPENBTC (of bitshares network) for you, if you want to convert BTC paid by a customer to bitBTC to a merchant, you need another bridge as @dnotestein mentioned above. The bitshares network itself can't do it without a 3rd party or some side-chain technology. However it seems that nobody is providing the bridge service which you need.

**Comment by kenCode-de** [comment]
I just used the Blocktrades bridge for the first time today, worked great! I used mycelium to send some bitcoin to the provided btc address and it put my bitcoin right into my bitshares (BTS) balance. frign awesome :)  Merchants are going to love that feature since they will no longer have to think about btc volatility. 

Next is bitBTC... can you please email me, or add me to your newsletter or something so that we can implement that into our wallet as well as soon as Blocktrades has it ready??? 

Please and thank you :)

**Comment by kenCode-de** [comment]
By the way, Bitcoin to BTS is nice, but what about Bitcoin to EUR? or USD? CNY? etc etc 
BTS and BTC both might seem a bit risky for some, so I think shifting right into a market-pegged-to-fiat would be ideal.

**Comment by dnotestein** [comment]
Sure, I'll let you know as soon as we've implemented support for bitBTC, bitEUR, bitUSD, etc. We supported all of these in the past for BitShares 1.0 and we just need to overcome some technical hurdles to support them again on BitShares 2.0. It shouldn't take too long; it's on our roadmap for immediately after we get our liquidity bots running.

**Comment by kenCode-de** [comment]
btsbots? or another market maker? this is awesome. 

please do @dnotestein MUCH appreciated. all of our wallets will use Blocktrades then.
