### ISSUE TITLE
no link to the hosted gui from this github page

### ISSUE THREAD

**Issue by jonnybitcoin** [cryptonomex/graphene-ui#656]
on this github page there is no website or description. Surely it should be 
www.bitshares.org/wallet

**Comment by svk31** [comment]
@valzav I think that's a good idea but I can't seem to find a way to edit the description, could you handle it please?

**Comment by valzav** [comment]
@jonnybitcoin I'm not sure CNX wants to promote www.bitshares.org/wallet, official wallet is Open Ledger
