### ISSUE TITLE
Fill operations contain no information about market fees

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene-ui#658]
This is a repost of https://github.com/cryptonomex/graphene/issues/464

As shown in the screenshot attached to that ticket, fill operations should show fees, but don't.  Me and @svk31 both thought the backend wasn't recording the fees, but it's actually recorded in the code and the JSON -- it just needs to be displayed.

Note the screenshot is a month old, if the problem's been fixed already, feel free to close this.

**Comment by svk31** [comment]
I guess the reason I missed this is that it's not very logical that the fee is not subtracted from what you see in the 'receives' field, especially since it doesn't work that way anywhere else (normal transfers for example).

I'll add some logic to subtract the fee.
