### ISSUE TITLE
Can we make the UIA name longer than 16 characters please

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#659]
The Smartcoins POS systems allow the merchant to automatically offer their rewards with each customer purchase. In the POS settings screen though, there are so many UIA's listed in there already, it would be nice if the merchant's UIA were easier to find, and more explanatory. This way when the customer looks in their mobile wallet, they will see that merchants UIA as a nice little reminder and there is no question what it's for. 

STARBUCKS.REWARDS for example is 17 characters. 
MEDIAMARKT.REWARDS is 18 characters. 
CIRCUITCITY.REWARDS is 19 characters. 
ALBERTSONS.REWARDS is 18 characters. 
JOES.COFFEE.ON.MAIN.STREET is 26 characters. 

Some small businesses have more than 1 location (like Joe's Coffee) and it would be nice if they could offer their own token too. You get the point. Can we please expand UIA length to say 32 chars?

**Comment by svk31** [comment]
This is not a GUI issue, you should raise this issue in the graphene repo as it's a blockchain restriction.
