### ISSUE TITLE
Cursor moves improperly when inserting characters in edit box

### ISSUE THREAD

**Issue by dnotestein** [cryptonomex/graphene-ui#662]
When you type a character into the middle of a text string in an edit box (e.g. in the amount field of the transfer form), it moves the cursor to the end of the edit box. This is extremely annoying.

**Comment by steempower** [comment]
This should be a high priority, it is very frustrating and hopefully should only take a very short amount of time to resolve
+5% 

When selecting price box, default value should disappear or if not disappear when i place my cursor to the right hand side of the default value (0) and try to enter a '.' (so the price would be a fraction of the base currency e.g 0.02 BTS/BTC/....). it should allow me to do so. Currently i click to the right hand side of the 0 and press '.' the cursor jumps to the left of the 0.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#32
