### ISSUE TITLE
Two identical columns for displaying fees

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#668]
The two identical columns on the /explorer/fees page are very confusing.

They only make sense when the Preferred Unit of Account is not BTS but for all new users this is not the case and when they look at those two columns they have no clue what's going on.

So I guess we need some column headers or just remove the second column if the Preferred Unit of Account is set to BTS.

![untitled](https://cloud.githubusercontent.com/assets/11573977/12353242/785c650e-bb8d-11e5-8c21-298b0a30a1a9.png)

**Comment by svk31** [comment]
After xeroc's recent changes there were 4 columns, I felt that was too much so I've reduced it to two again, but I only kept the "equivalent value" ones.

cf458c5cfe9eecec9523ec76377cc876b0f72bc7
