### ISSUE TITLE
Refferal code field in account creation lacks input validation.

### ISSUE THREAD

**Issue by netixen** [cryptonomex/graphene-ui#674]
The ui doesn't warn the user if what he entered is a valid refferal code.
A user can make the mistake of typing an account name. Either checking or showing how a valid code looks would be helpful.

**Comment by xeroc** [comment]
This should be part of the definition of "rich memos" .. so that we can have arbitrary content and still know what to verify against which rules ..

**Comment by valzav** [comment]
I will remove referral code input - it's not supported by the faucet yet and I don't have time to finish it.

**Comment by netixen** [comment]
Don't urls like https://bitshares.openledger.info/?r=<account name>#/ work?

**Comment by valzav** [comment]
@netixen they work. Referral codes are not related to them.

**Comment by svk31** [comment]
Looks like this was removed, can you confirm @valzav ?
