### ISSUE TITLE
Send button stays disabled

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#678]
Linux light client, current version: 2.0.160120.

I click on an account now in the Overview list, the i click on the TRansfer tab at the top, and the from field keeps defaulting to a different account. So, if I go in that field and re-type the account i want to send from, the fee field at the bottom disappears and the send button stays disabled. I have no way to send funds from my old delegate.kencode account to my kencode account. Both accounts reside in the same wallet.

**Comment by valzav** [comment]
I'll take a look. We are planning new release tomorrow, I'll include a fix.

**Comment by kenCode-de** [comment]
I am now running the latest v...121, the from field is fixed. 

the fee field at the bottom is still gone though, and the send button stays disabled. I have no way to send funds from my old delegate.kencode account to my kencode account. Both accounts reside in the same wallet.

**Comment by valzav** [comment]
Is anybody else experiencing missing fee issue?

**Comment by valzav** [comment]
@kenCode-de, fee won't be shown if your account's balance is zero, make sure you have funds.

**Comment by kenCode-de** [comment]
Well, the funds are there. I claimed them from vesting: 
http://cryptofresh.com/b/2862177 

The funds show in my BTS balance too: 
http://cryptofresh.com/u/delegate.kencode 

The wallet won't let me send those BTS to anyone though, the Send button remains disabled.

**Comment by svk31** [comment]
I found the fee field bug but can't reproduce the send button staying disabled.

**Comment by kenCode-de** [comment]
Found it! 
- clicked on my delegate.kencode account in overview 
- click on transfer tab 
- from delegate.kencode to kencode (send button is still disabled) 
- 1310bts balance that i can send, so i clicked on that link. 
- send button still disabled 
- i changed the amount to send to just 2bts (the send button lit up!) 
- i clicked the available balance link again, it changed my 2bts entry to 1310bts 
- i sent my delegate.kencode bts balance to kencode successfully: 
  http://cryptofresh.com/b/2910469 

so i guess the disabled-send bug resides in the send button detecting the balance or something?

**Comment by svk31** [comment]
Should be ok now, please reopen if it still occurs after the next release.
