### ISSUE TITLE
UN-follow does not work quite right

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#679]
I imported the wif as per the instructions: 
http://cryptofresh.com/u/announce 

I sent a couple of 1 BTS tests as you can see there on CF. 

In my wallet though it automatically makes me Follow 2 accounts: 
twitter.puppies 
announce 

I have no need to follow those 2 accounts. I unfollow them, close my wallet and open my wallet and then those 2 accounts reappear as Followed accounts. bug?

**Comment by valzav** [comment]
very strange, it shouldn't follow any accounts automatically

**Comment by roadscape** [comment]
Those 2 accounts share the same memo key.. so it seems the wallet "follows" all accounts which you have a key for?
