### ISSUE TITLE
Reopen #638 (issue about enforce wss API servers from secure domains)

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#680]
Reopen #638 
Some API servers setup by community members added in #666, but 3 of them start with "ws://" but not "wss://", it doesn't work if enforce "wss://" on these servers.

By the way, although both "wss://bitshares.dacplay.org:8089" and "wss://bitshares.dacplay.org:8089/ws" work on my computer, is it better to add "/ws" at the end of every API server?

**Comment by svk31** [comment]
No idea about the /ws, but we shouldn't show insecure api servers imo so I've removed them.

**Comment by AlexChien** [comment]
The correct api to use should be wss://bitshares.dacplay.org/ws wss://bitshares.dacplay.org/ws , this will give you secure api as well as load balance benefit.  The end point you mentioned are still accessible only for backward compatible purpose because they were announced at earlier days.
