### ISSUE TITLE
BitShares 2.0.160121 - Fiat withdraw screen on Light Wallet - no navigation

### ISSUE THREAD

**Issue by bitsacer** [cryptonomex/graphene-ui#682]
On the light-wallet navigation buttons missing on OpenLedger's withdraw screen

**Comment by valzav** [comment]
I don't see any issues, please post some screenshot

**Comment by bitsacer** [comment]
deposit link opens a tab on the browser, its the withdraw link that opens on the light wallet and there is no way to navigate back .

![screen shot 2016-01-22 at 7 38 19 pm](https://cloud.githubusercontent.com/assets/15133633/12518433/45a1497c-c141-11e5-8a9c-74c59fed613e.jpg)

**Comment by bitsacer** [comment]
once I arrive on this screen how do I navigate back ?

**Comment by bitsacer** [comment]
This issue still persists, Light wallet - withdraw screen. once on that page there is no navigating back, have to restart the application

**Comment by svk31** [comment]
@valzav You could try wrapping it in an iframe perhaps for the light client?

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#34
