### ISSUE TITLE
Fiat deposits and withdrawals - Links are confusing

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#683]
Running latest v...121 light client 
Just FYI, I have never used OpenLedger, but I do have a CCEDK.com account.

In Overview, click an account, click deposit/withdraw, click ccedk, click "Click here to register for deposits". This loads up an external browser window which looks a little shady. Can't I just enter my CCEDK login info here with the hash and 2FA info? I'd rather not have to photocopy my passport again and all that kyc stuff. 

click "Click here to register for withdrawals". This loads up a screen in the wallet which is better, but the menu across the top is gone now, so there is no way to Back button to the previous screen. There also needs to be something at the top of this page that says what this registration is for, what you will now be able to accomplish by registering here, etc. Why should I register....? A sales pitch of sorts, but keep it short and to the point.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#35
