### ISSUE TITLE
hide/burn Assets

### ISSUE THREAD

**Issue by btswolf** [cryptonomex/graphene-ui#687]
add a option to hide/filter and/or burn unwanted assets from the balances menu.

**Comment by bitsacer** [comment]
so what will this do?

**Comment by svk31** [comment]
![image](https://cloud.githubusercontent.com/assets/6890015/12623997/074fcb7c-c52d-11e5-9836-bac8dec3cd34.png)

**Comment by bitsacer** [comment]
Oh man, neat !
