### ISSUE TITLE
Delete connection from settings

### ISSUE THREAD

**Issue by testzcrypto** [cryptonomex/graphene-ui#688]
Today possible to add new connection but impossible to delete, it's required if for example user add wrong connection string.

**Comment by svk31** [comment]
Works fine for me so some more details on how to reproduce would be nice. Which browser and OS for starters?

**Comment by testzcrypto** [comment]
Opps, yes, if I change connection when I get "-" button, but if I get for settings first time "-" invisible even I have more than one connection defined, checked at Chrome and Firefox:
https://cdn.pbrd.co/images/10fzCYAP.png

**Comment by svk31** [comment]
The GUI does not allow you to remove the default connection (openledger in this case), can you try one of the others? Or try adding one then removing it.

**Comment by testzcrypto** [comment]
No, it's possible to remove the default connection, remove one of non default connection when you get "-" at default connection, remove default connection:
https://cdn.pbrd.co/images/10guASIm.png
https://cdn.pbrd.co/images/10gB8t8c.png

**Comment by testzcrypto** [comment]
Probably it's interface issue, after refresh, all connection removed this way gets back.
Maybe better it "-" button will be always visible but grayed out for default connection?
