### ISSUE TITLE
Failed to Create Wallet: Buffer Required/Failed to Create Account

### ISSUE THREAD

**Issue by VoR0220** [cryptonomex/graphene-ui#69]
It seems I followed all the steps that someone should follow when attempting to create an account. Beyond this it could get very confusing for a non technical person. A simple attempt to create an account. I got this when I attempted it. Suggestions? Thoughts to where the problem may lie? 
![screenshot from 2015-07-21 21 48 35](https://cloud.githubusercontent.com/assets/7756785/8816941/8e8ad68e-2ff2-11e5-812f-879eb1eed0d7.png)

**Comment by valzav** [comment]
Probably accounts creation is broken right now because of graphene api changes, will take a look tomorrow. You may have a better idea of what's going on if you take a look at dev console. We are planning to improve errors reporting in future releases.

**Comment by VoR0220** [comment]
sounds good. Looking forward to helping to solve this one.
