### ISSUE TITLE
the new ccedk fiat thing is very confusing

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#691]
deposit/withdraw screen, click ccedk tab. 

this text is displayed 3 times: 
Click here to register for deposits 

this text is displayed 3 times too: 
Click here to register for withdrawls 

VERY confusing. 
Worse yet, both of the "here" hyperlinks appear to load the same form, but one is in my external browser and the other keeps you in the wallet with no way to cancel and go Back (button). 

This screen also needs an explanation, an upsell, and a fine print disclaimer underneath of the fiat section. My grandma should feel very comfortable when sending all of her private, high security info to some invisible entity behind the scenes here. This screen is far too scary (and risky) as it sits now.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#37
