### ISSUE TITLE
Need better price precision on markets with low precision assets

### ISSUE THREAD

**Issue by dnotestein** [cryptonomex/graphene-ui#692]
As an example, see screenshot of current BTS:OPEN.USD market. When viewed this way, it looks like the bid and ask price are the same, because only 3 digits of precision are given.
![image](https://cloud.githubusercontent.com/assets/5102968/12561891/53be21f2-c370-11e5-988a-a16535f1e4fb.png)

**Comment by svk31** [comment]
It's not easy finding the right balance between too many and too few decimals when we have so many combinations of assets with different valuations and precisions.

In this case the biggest problem is that you set the precision of OPEN.USD to 2, it should've been 4 like the real USD asset. Currently the GUI handles prices like this one, X / BTS, by adding 1 decimal to the precision of X. I'll add one more decimal which should allow you to distinguish most prices in this market. In the next update of the GUI you won't be able to enter prices either that have precision higher than the quote asset.
