### ISSUE TITLE
x-axis (prices) in predictions market chart can be fixed to 0...1

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene-ui#693]
In contrast to regular markets, where the spread defines `x_min` and `x_max`. I think prediction markets can be fixed to 0...1

**Comment by svk31** [comment]
What happens when you invert the market though?

![image](https://cloud.githubusercontent.com/assets/6890015/12681900/24cf87fc-c6b1-11e5-893f-b1e7ee2132c4.png)

**Comment by xeroc** [comment]
It makes no sense to invert those markets IMHO.
prediction markets should always have the `quote/backing-asset` orientation and axes limited 0..1.
