### ISSUE TITLE
Deposit/Withdraw screen inconsistency (bridge or gateway?)

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#696]
I'm use latest light client 160127 on linux

Open wallet > Dashboard click account in Overview > Deposit/Withdraw > Blocktrades 

Blocktrades has a Bridge and Gateway (with coin addresses listed and Generate button). 

Now click CCEDK at the top. 

CCEDK has Fiat and Bridge (but in the Blocktrades screen you call it a Gateway). 

So, where the coin addresses are listed with the "Generate button", is that a Gateway or a Bridge? 

I hope I explained this one well enough, those section header names should match.

**Comment by svk31** [comment]
Looks like emfrias fixed this one, closing.
