### ISSUE TITLE
I do not want to auto-Follow

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#697]
Ever since I imported that wif so that I can post in the "announce" thingy (http://cryptofresh.com/u/announce), it keeps on making me Follow these accounts (and more are appearing in my dashboard overview too which is making this even worse): 

ANNOUNCE 
BSIP10-WORKER (this one just appeared today) 
COMMITTEE-TRADE (this one just appeared today too) 
TWITTER-PUPPIES 

I keep UN-following them but they keep re-appearing in my dashboard accounts overview.

**Comment by abitmore** [comment]
Is it safe to "ignore" an account? How to get the control of an account back after ignored?

**Comment by abitmore** [comment]
OK I got it. But see #724 please.
