### ISSUE TITLE
Create Asset Fails

### ISSUE THREAD

**Issue by VoR0220** [cryptonomex/graphene-ui#70]
When trying to call Create Asset in the top right corner, blank page with "Cannot GET /true" is shown. Is asset creation not enabled quite yet from the backend?

**Comment by svk31** [comment]
It's enabled in the backend but not yet implemented in the GUI

**Comment by VoR0220** [comment]
Where might I help in implementing this? Where would this action be processed?

**Comment by svk31** [comment]
I believe @ChronosCrypto is working on this atm

**Comment by VoR0220** [comment]
thanks. On an unrelated sidenote you think you could give me a quick hint with this question: https://bitsharestalk.org/index.php/topic,17673.0.html

**Comment by svk31** [comment]
Closing this, use #37 instead for comments about asset creation.
