### ISSUE TITLE
Swop the position of markets and trade history

### ISSUE THREAD

**Issue by jonnybitcoin** [cryptonomex/graphene-ui#706]
I really think it would be a much better layout if markets box was on top of trade history box. Basically just swapping them round. 

This would be much more familiar to many traders and this is where poloniex and other exchanges often position their markets. ie the top right.

**Comment by svk31** [comment]
I'm trying out a different layout, adding a mini depth chart visible at all times and moving the market history to the bottom center. While this is how Poloniex does it I personally prefered to have the history visible, what do you think?

![image](https://cloud.githubusercontent.com/assets/6890015/13016500/716d98ba-d1bf-11e5-996d-2df1e6795f64.png)

**Comment by jonnybitcoin** [comment]
I think moving trade history to bottom is a great idea.
I like the market pairs in this new position.
I like the current set up where you can swop between depth charts /price charts.
I think being able to veiw both at the same time is too much and depth chart is to small with this layout. 
The space below market pairs is ideal for a trollbox and would match polos UX.

**Comment by svk31** [comment]
OK thanks for the input!

I was gonna leave the swapping between depth and price charts too, and yea I guess a trollbox would fit there. The one I have designed already works like this one https://conversejs.org/ so you can hide it though.

**Comment by mindphlux1** [comment]
I do like this as well - however I would suggest to put the full width depth to the bottom of the 'orders' screen .. polo has it like that too. The position of the mini depth would be the perfect place for a trollbox (add little more height)

**Comment by svk31** [comment]
Will keep it like in the screenshot until the trollbox is ready, at which point I might replace the small depth chart.
