### ISSUE TITLE
Light wallet GUI 2.0.160203 - not ignoring all accounts 

### ISSUE THREAD

**Issue by bitsacer** [cryptonomex/graphene-ui#717]
Is there a limit to how many accounts a user can ignore, some dont get ignored

**Comment by svk31** [comment]
Yes, 20 I believe I set it too. Arbitrary, but I just didn't want it to be unbounded.

**Comment by svk31** [comment]
Do you have that many accounts in your wallet that you want to ignore?

**Comment by bitsacer** [comment]
let me count hold on

**Comment by bitsacer** [comment]
yes around 35

**Comment by bitsacer** [comment]
almost all created after the launch of 2.0 . paid for

**Comment by bitsacer** [comment]
You did not have to do it for me, but thank you ...
