### ISSUE TITLE
What the heck is a "Vesting Balance"?

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#722]
There should be some sort of explanation on that new Vesting Balances screen as to what that money is from, where it sits before it is claimed, how it accumulates, etc.

**Comment by xeroc** [comment]
http://docs.bitshares.eu/bitshares/user/vesting.html

**Comment by noisy** [comment]
@xeroc I think all wallet user's ask those question. There is a rule in UX, that empty tab/page should never be shown to the users. I think that "This account has no vesting balances" do not mean anything to most users.

In my opinion in case when "This account has no vesting balances" is displayed, tab "Vesting balances" should not be displayed at all.

@kenCode-de could you agree to change title of reported issue by you to:

> Please remove "Vesting Balances" tab when it is empty.

?

**Comment by kenCode-de** [comment]
Well, I dunno, I think if we have that feature we should at least provide a brief explanation as to what a Vesting Balance is. Then if people want to start accumulating a vesting balance, show a couple of examples of things that will start giving them interest or dividends etc (i know i know, but explain the differences).
