### ISSUE TITLE
Translation Request

### ISSUE THREAD

**Issue by bitsacer** [cryptonomex/graphene-ui#723]
This is not an issue but a request. On OpenLedger's welcome page  it greets as "Welcome to OpenLedger" . Currently In Turkish translation it is " Welcome to Graphene" . I would like it to be " Welcome to Blockchain" in Turkish since I believe the terminology has a wider recognition and it conveys a more familiar message. The "Graphene" is already appearing on the bottom left corner all the time. So it would  be " Blokzincirine Hoşgeldiniz" which is the translation of " Welcome to Blockchain" . Any thoughts?

**Comment by svk31** [comment]
I think you can translate it whichever way you think fits best.
