### ISSUE TITLE
Is there a page to show all ignored accounts?

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#724]
Is there a page to show all ignored accounts? Once ignored some accounts, I may want to re-use some of them again after some time. It's hard to remember all the account names and find out which one is best.

**Comment by kenCode-de** [comment]
The latest version of the wallet has a cool new ignore button on the overview screen.

**Comment by abitmore** [comment]
Ah OK. Found it. Thanks.
