### ISSUE TITLE
Reopen #717: ignored accounts still show up

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#726]
For example, I have 10 wallets in my light client, every wallet has same 10 accounts which I want to ignore, and some other accounts I want to ignore. I ignored the accounts in the first wallet, then switch to the second wallet, same accounts show up. I ignore them again and switch to the third wallet, then switch back to the second wallet, the accounts show up again.

**Comment by bitsacer** [comment]
https://github.com/cryptonomex/graphene-ui/issues/717

**Comment by abitmore** [comment]
Closing. It works fine with 2.0.160309 now.
