### ISSUE TITLE
Blocktrades Bridge in Deposit/Withdraw, impossible to read menus

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#733]
Blocktrades Bridge in Deposit/Withdraw, impossible to read menus

The <select> menus have white text on a light gray background, impossible to read. 

And secondly, do not allow non-numeric entry into the text fields.

**Comment by svk31** [comment]
Not sure what you mean, this looks perfectly legible to me:

![image](https://cloud.githubusercontent.com/assets/6890015/13123004/3504c188-d5ba-11e5-8d2a-0feb0a3ce6a4.png)

I did change the input types though.

**Comment by kenCode-de** [comment]
click on one of those _select_ menu drop-downs..

**Comment by svk31** [comment]
Gotcha, thanks!
