### ISSUE TITLE
Autofill to sell total balance to sell brings up minus numbers

### ISSUE THREAD

**Issue by jonnybitcoin** [cryptonomex/graphene-ui#735]
When I try and sell bitusd I click the highest bid offer and it populates correctly. 

Then when I try to fill in my whole bitusd (8.8506) balance by clicking on the total amount I have in my account it populates the sell order with minus figures. 
![screen shot 2016-02-15 at 19 27 06](https://cloud.githubusercontent.com/assets/15330829/13058288/2a3c9254-d41a-11e5-8362-821341940408.png)

**Comment by svk31** [comment]
Thanks but this was fixed already here: https://github.com/cryptonomex/graphene-ui/commit/634ecddafa25e50e1fc5d5748f85ac6b9c1cacfc
