### ISSUE TITLE
Asset update bug fixed?

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#737]
Is the bug described in [this thread](https://bitsharestalk.org/index.php/topic,20870.0.html) fixed? 
(In short, unexpected flags and permissions change.)

**Comment by svk31** [comment]
Yes it was fixed when I added support for prediction markets and smartcoins in this commit: https://github.com/cryptonomex/graphene-ui/commit/74950d61901b30d415bfdb2ea55dad915809c23d
