### ISSUE TITLE
UI proposal:  View vertical menu on any page by toggling hamburger icon

### ISSUE THREAD

**Issue by jonnybitcoin** [cryptonomex/graphene-ui#742]
See proposed UI mockup image below. 
I personally find navigating to pages listed on the vertical menu too slow. 
- Add burger icon to top left corner which will slide out/in the vertical menu.
- Move account selection drop down (in header) to far left and show on every page.

Disadvantage would be the slide out vertical menu would cover some of the info when open. (youtube.com does this and it looks fine)

![uiconcept](https://cloud.githubusercontent.com/assets/15330829/13163927/f087be58-d6a8-11e5-9517-d0e4d488671a.png)

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#40
