### ISSUE TITLE
is it bug? diplay  out of sync  but synced &can't enter explorer-blockchain webpage

### ISSUE THREAD

**Issue by todasun** [cryptonomex/graphene-ui#743]
BitShares-2.0.160216-x64-cli-tools.exe
BitShares-light_2.0.160217.exe
windows7 sp1 64bit os
in the capture  that's synced  same as http://cryptofresh.com/
but display  out of sync  & can't enter  exploer----blockchain 
![qq](https://cloud.githubusercontent.com/assets/10720816/13166586/7135343a-d704-11e5-9fca-d86694b46fcc.png)

**Comment by svk31** [comment]
Could be due to your local computer clock being out of sync, could you
verify that please?

**Comment by todasun** [comment]
thank you  it works .
it's better to display the reason " system time is wrong"  & it's best to autosync the system time with time server
