### ISSUE TITLE
Issues with account create/update

### ISSUE THREAD

**Issue by roadscape** [cryptonomex/graphene-ui#745]
Users are reporting issues with creating accounts and updating votes, and it may be because "the extensions field on account create/update operations is now a struct not an array".

Source: https://bitsharestalk.org/index.php/topic,21530.msg280473.html#msg280473

It's suspected that this is a graphene bug; the full issue details were filed on that repo:
https://github.com/cryptonomex/graphene/issues/593

**Comment by svk31** [comment]
Fixed in graphene core, closing.
