### ISSUE TITLE
24 hour market percent change is not correct

### ISSUE THREAD

**Issue by mvandeberg** [cryptonomex/graphene-ui#748]
See cryptonomex/graphene#592 for details. 

Displayed 24 hour market percent change does not match what is expected.

**Comment by svk31** [comment]
Looks like the reason is your convention for using QUOTE/BASE for prices. I denote prices in the QUOTE:BASE market as BASE / QUOTE, like most exchanges I know. Because of this it gets very confusing when calling get_ticker with my existing definitions of QUOTE and BASE assets in a given market.

**Comment by mvandeberg** [comment]
This seems to be a larger issue in bitshares. All of our API calls take base, quote which to me implies a BASE:QUOTE market. I don't think there is any documentation of these specifics in the graphene code. I can change the semantics of the call to match a QUOTE:BASE market.

**Comment by svk31** [comment]
To be honest I'm not sure what the correct convention is, so I'm not sure you should change it. I could work around it in the GUI as well.
