### ISSUE TITLE
GUI development for BSIP10 percentage based transfer fee

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#754]
This ticket is for tracking GUI works of BSIP10.
- The BSIP10 feature requirement/description is [here](https://github.com/bitshares/bsips/blob/master/bsip-0010.md).
- main back-end develop branch is [here](https://github.com/abitmore/bitshares-2/tree/dev-transfer-fee). 

Things to be done:
- [ ] check whether the transfer feature in current GUI is compatible with new back-end
- [ ] add an selection box on the "create asset" page and "update asset" page, so the issuer can set fee mode easily
- [ ] show transfer fee mode on asset details page, and maybe somewhere related (please indicate)
- [ ] use new transfer_v2_operation to do all transfers, or use new operation on assets with percentage fee mode but use the original transfer_operation on assets with flat mode
- [ ] transaction history / Recent activity (should I list the pages which contain a list of history?)
- [ ] block detail page (the page after click on a transaction in the history)
- [ ] extend fee estimation to handle percentage fees (only needed if GUI estimates fees independently but not call get_required_fees API).
- [ ] check if the fee schedule page work with new back-end
- [ ] adjust "Fees and cashback" section of membership page, and maybe description of "Fee Division", and maybe some related pages (please indicate)
- [ ] [optional] deal with the No. 4 issue described in BSIP10 document (overpay fee to avoid trx failure)

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#41
