### ISSUE TITLE
Add warning when creating UIA that number of decimal places cant be changed

### ISSUE THREAD

**Issue by jonnybitcoin** [cryptonomex/graphene-ui#756]
Add warning when creating UIA that number of decimal places cant be changed. 

I think there was a warning before.
Also
when creating UIA it is called decimal places 
when on update asset it shows as precision: 2

**Comment by roadscape** [comment]
IIRC as of the last update, Graphene lets you change otherwise unchangeable permissions if the supply of your asset is 0. Not sure if it lets you change precision as well, but that would be great..
