### ISSUE TITLE
UI idea.. "DEX" and "SEND"

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#761]
RE: https://bitsharestalk.org/index.php/topic,21773.0.html 

I am not a Trader, and sometimes in my old age (nearing age 50) looking up there at the menu across the top and I see "TRADE" and "TRANSFER" (especially having the same first letter), I think it would be better #1 for brand recognition if we use the word DEX instead of TRADE, and #2 use SEND instead of the word TRANSFER. 

Everybody knows what Send and Receive means (we use those terms in our POS and mobile wallets too). Send and Receive are also universally translate-able (into the 44 languages that we have implemented). 

DEX is just an awesome word that screams what it is that we are most capable at. 

EDIT: i changed the word DEX to EXCHANGE

**Comment by jonnybitcoin** [comment]
I agree EXCHANGE is better than TRADE

**Comment by btswolf** [comment]
+5 for Exchange
