### ISSUE TITLE
Display CER in the asset settings as asset/BTS

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene-ui#762]
It should be more clear to the end user that the CER makes you a profit if people pay the fee in your asset and the CER is higher than the market rate (in BTS) while it makes a loss if the CER is lower than market rate ..

This is only true if you display the CER as asset/BTS .. because you sell asset in exchange for BTS.

**Comment by svk31** [comment]
Right you are, seems to only happen with UIA markets, not ones involving bit assets.

**Comment by svk31** [comment]
Fixed in bitshares-ui
