### ISSUE TITLE
UI/UX: Need ability to search Recent Activity memos

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene-ui#769]
Right next to the CSV link would be a great place to put a search field. Maybe even add from/to date range fields. 

Then, ability to export just those search results to CSV would be cool too. I need to be able to quickly prove every payment that was received from someone.

**Comment by xmr-karnal** [comment]
Agreed, this would be very useful.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#44
