### ISSUE TITLE
if set the connection API as  127.0.0.1::8090 , cannot pass the loading page

### ISSUE THREAD

**Issue by pureland** [cryptonomex/graphene-ui#770]
if set the connection API as  127.0.0.1::8090 , cannot pass the loading page
if wrong IP format is set  like :: replace : 
 cannot pass the loading page

**Comment by svk31** [comment]
the problem is that you're not using a `ws://` or `ws://` protocol, but I'll push a fix to enforce that. To restore the defaults, open the dev tools, go to the tab `"Resources" -> "Local storage"`, then find your website and delete the entry `__graphene__settings_v3`

**Comment by abitmore** [comment]
Not only forcing `ws://` or `wss://`, but also a validation of the whole URL is needed.

```
Uncaught SyntaxError: Failed to construct 'WebSocket': The URL 'ws://123.456.7.8/' is invalid.
Uncaught SyntaxError: Failed to construct 'WebSocket': The URL 'ws://testnet.bitshares.eu::8090/ws' is invalid.
Uncaught SyntaxError: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'http' is not allowed.
```

We can probably just catch any `SyntaxError` then redirect to `init-error` page.
