### ISSUE TITLE
Market: maybe incorrect default price filled into buy/sell box when clicking on a margin call order

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#771]
Someone reported that when he clicked on a yellow order then clicked "buy" button directly (without checking of the price), the price in the new order (shown in block history) is much higher than the price shown in order book, and another strange thing, the final price he paid is between those two prices.

I guess when there is a yellow order shown on the order book (margin call orders?), when clicking on the order, the price filled into buy/sell box is probably incorrectly set to feed price.

**Comment by svk31** [comment]
This should be fixed now with the market update.
