### ISSUE TITLE
Transfer: update "available" after empty

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#772]
Assume I have 10 IOU and 100 BTS in my account.
Steps:
- click on "Send"
- input "to", select "IOU" from "amount" box: the "available" amount is updated
- click "available", click "send": asset in the amount box is updated to "BTS" and unable to change, "available" is updated to "0 IOU" but didn't change to "XXX BTS"

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#45
