### ISSUE TITLE
GUI does not show Market Trades in view only mode (no registered Account)

### ISSUE THREAD

**Issue by btswolf** [cryptonomex/graphene-ui#774]
GUI does not show Market Trades in view only mode (no registered Account)
![image](https://cloud.githubusercontent.com/assets/11035520/13725136/387e12d2-e899-11e5-96b4-98d835632fcb.png)

**Comment by btswolf** [comment]
also no Order Book
no buy and sell orders

**Comment by abitmore** [comment]
> also no Order Book

Scroll a bit down to show order book? Looks like you're in horizontal order book mode?

**Comment by btswolf** [comment]
yeah looks likes but wasn`t.
however fixed now and already working on OL.
