### ISSUE TITLE
Unable to create new account on openledger, but on bitshares.org/wallet it works ok

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene-ui#778]
Please watch video which shows recorded bug:

https://youtu.be/Adn4uCHRnqI

To be honest I wasn't sure whether this is correct place to report bug which reproduce only on openledger. In the other hand, openledger is advertised by bitshares project as main web wallet.

If this is not proper place, please tell me, where those type of bugs should be reported.

**Comment by valzav** [comment]
@noisy thanks for the video, I think this is the issue that @svk31 has addressed in this commit https://github.com/cryptonomex/graphene-ui/commit/fb53569459e98846d7aaec847eab45d1f07af440
We will deploy it to OL tomorrow.

**Comment by noisy** [comment]
@valzav BTW, how is responsible to deploy wallets on OL? Is this right place to report bugs which reproduce only on OL?

**Comment by svk31** [comment]
The question remains of how on earth the URL gets set to `http://` since it's not like that in our code, but like valzav said my commit should fix this issue.

valzav deploys to OL, and yea it's best if you report issues here.
