### ISSUE TITLE
BUY/SELL widgets collapses incorrectly

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene-ui#779]
Current behavior:
https://www.youtube.com/watch?v=9pq9V-Ruvlg

Expected behavior:
- collapsed widget should not leave open box empty
- clicking on arrow should collapse only one widget.

version: 2.0.160309

**Comment by svk31** [comment]
It just doesn't make sense to collapse them in this view since you won't gain any space, same goes for collapsing them independently: it serves no purpose. I'll change it so the behaviour is correct though as the breakpoints change.
