### ISSUE TITLE
Rename option "CSV" to "export as CSV file"

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene-ui#780]
Not all users has to know what is CSV. Option should be more descriptive.

![selection_198](https://cloud.githubusercontent.com/assets/201263/13733123/d4a8416e-e98e-11e5-9217-b07a89330031.png)

During Usability Tests I already seen once, that someone tried to backup a wallet by clicking CSV option. I think this is because right now this option is just bellow all balances. When people see their balances they think that somewhere close should be a button to backup account with that balances.

Knowing that, we could even rename "CSV" to "export recent activity as CSV file" or move this link "export as CSV file"/button to left (closer to "Recent activity" headline)

![selection_200](https://cloud.githubusercontent.com/assets/201263/13733244/89f58bfc-e990-11e5-9cd5-e761d61f97e4.png)

![selection_199](https://cloud.githubusercontent.com/assets/201263/13733245/8e0d6516-e990-11e5-9a40-8bd842290cd7.png)

**Comment by noisy** [comment]
@svk31 This is yet another reason why things should be reviewed (with Pull Requests) before merging to master branch (like in any projects which cares about quality and users feedback):

This should not looks like that:
![selection_233](https://cloud.githubusercontent.com/assets/201263/14162512/ba02425e-f6ec-11e5-87ef-a5e202a830bd.png)

First of all, this should not be represent as link. And even if it that would be a good idea (and it is not), then brackets should not be a part of link, like this:

![selection_234](https://cloud.githubusercontent.com/assets/201263/14162560/28f04486-f6ed-11e5-9215-253c6de35fc9.png)

But still... this should not be a link, from Users perspective this action generate something... so this should be a **button**, not a link, like this:

![8e0d6516-e990-11e5-9a40-8bd842290cd7](https://cloud.githubusercontent.com/assets/201263/14162580/64ff9b16-f6ed-11e5-8453-39a2e31a2d45.png)

I don't want to be ungrateful, but I would prefer make things in slower pace but once and correctly, and not quickly but with multiple fixes to production.

**Comment by svk31** [comment]
Buttons are too big imo, and I don't want to waste the vertical space by moving it below the title. I'll put it inside the brackets though.
