### ISSUE TITLE
An account controlled by another account is not shown as "My Account"

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#783]
Steps:
- create an account A
- create an account B
- change B's permission to account A and weight 1 (remove original key)
- B is not shown as "My Account", thus can't transfer or trade, but can vote

(IMO it's an advanced feature so maybe low priority)

**Comment by svk31** [comment]
This ties in with proposed transactions which is in another branch but currently on hold due to a lack of data from the API, see https://github.com/cryptonomex/graphene/issues/442.

**Comment by xeroc** [comment]
@abitmore 
If you use the public key instead of the name, then the wallet should figure out that his is your account!

**Comment by abitmore** [comment]
@svk31 It doesn't need to propose a transaction if the authority's weight is more than the threshold already. I'll take a look at that API issue.

@xeroc I know that, thanks.

**Comment by abitmore** [comment]
@svk31 it seems the solution of https://github.com/cryptonomex/graphene/issues/442 described by @theoreticalbts won't affect this issue.
