### ISSUE TITLE
Show status of all API servers?

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#784]
Show status of all API servers on init-error page and/or config page and/or a dedicated page? Status includes: up/down, latency, load(if apply), location(if apply), and maybe an description. So user can select fastest server, or maybe eventually auto-select.

Related to #770.

**Comment by btswolf** [comment]
GUI should ask automatically (timeout) to switch API connection after lost connection/blockchain sync problems.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#49
