### ISSUE TITLE
UI proposal: Add deposit/withdraw to top menubar

### ISSUE THREAD

**Issue by jonnybitcoin** [cryptonomex/graphene-ui#787]
Add Deposits/Withdrawls button to top menu instead of side menu.

Lots of noobs seem to get stuck on deposits and withdraws and this is a commonly used page.

Also it may become even more used if it was more prominent. 

makerx have this implemented already.

**Comment by noisy** [comment]
:+1:

**Comment by svk31** [comment]
Implemented in https://github.com/cryptonomex/graphene-ui/commit/92bd7d4c7149c2b48795160ffaec29852701f1c0
