### ISSUE TITLE
Pricing in order confirmation window

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#789]
https://bitsharestalk.org/index.php/topic,21961.msg192149.html

Copy & paste here:

Another UI fix would be to adjust the price in the order confirmation windows to be quoted in the same asset base as the market. For instance, we can view any of the markets in either ASSET-BTS or BTS-ASSET --i prefer using ASSET-BTS to normalize them all to a BTS base; however, even when i'm viewing the market as ASSET-BTS, for some markets (e.g. BTS-BTC) automatically show the BTS-ASSET price in the trade confirmation window. This is confusing and sometimes leads me to post trades at the wrong price bc sometimes the automatic fill in the Buy/Sell windows reverts to the the last trade. 

A good fix would be to ensure the confirmation window posts the quote in the same base unit as the market we're trading.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#51
