### ISSUE TITLE
Missing Authority while claiming multiple balances

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#794]
This issue is with GUI 2.0.160314. At least GUI 2.0.160217 doesn't have this issue.

See this post: https://bitsharestalk.org/index.php/topic,21952.0.html

Multiple `balance_claim_operation` in one transaction, signed by GUi, but got rejected by witness_node. In the console log (attached below), we can see the operations weren't sorted, the keys decoded from signatures are not same to keys in transaction. Probably the signatures are generated as if the operations were sorted? @jcalfee 

![bug3a](https://cloud.githubusercontent.com/assets/9946777/13965147/725edb36-f06d-11e5-947b-10c5ecdc59f9.png)

**Comment by jcalfee** [comment]
Yes, the witness node probably sorted the operations and got a different transaction hash than the UI.  The different hashes will cause each public key recovered from each signature and tx hash ( as seen in in `sigs`) to miss-match the balance owner keys.

So what I need to confirm is: how to sort the operations?  The witness node is probably taking the binary encoding of the operation then sorting them.  @theoreticalbts, is this correct?

Was sorting added in a hard-fork (multi-operation balance claims are common and should have come up before)?  Maybe something else is happening...

**Comment by abitmore** [comment]
@jcalfee I don't think witness_node sorts operations in a transaction. Operations in a transaction is a `vector`, so the original order will be kept as is.

This should be a GUI issue since GUI 2.0.160217 works fine with latest witness_node, but GUI 2.0.160314 not.

**Comment by jcalfee** [comment]
I had to add static_variant sorting in JS .. even though the witness node does not re-order (sort) static variants, my code was getting out of sync in the Json and Hex serializations.  I added sorting to make it more deterministic.  I'm porting to master, don't test yet...

**Comment by jcalfee** [comment]
I was able to claim a multi-operation balance claim (see last commit)...

**Comment by svk31** [comment]
@jcalfee Could you apply the fix to master as well please?

**Comment by abitmore** [comment]
@svk31 master should have been fixed already
