### ISSUE TITLE
Request: show a warning about core_exchange_rate at asset create/update page

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#796]
The fact: 
1. half of asset creation fee will go to the fee pool.
2. funds in the fee pool belongs to the asset issuer, and it can be withdrawn safely if no outstanding asset exists (a bit tricky though)
3. any asset holder can sell the asset back to the issuer at core_exchange_rate if the fee pool is not empty. If the issuer didn't set the rate correctly/safely, funds in the fee pool is unsafe. See https://cryptofresh.com/u/asshole1 and https://cryptofresh.com/u/acc12 for example.

**Comment by abitmore** [comment]
See http://docs.bitshares.org/bitshares/user/assets-faq.html#fee-pool

> Warning
> Make sure your core exchange rate is higher than the lowest ask, otherwise, people will buy your token from the market and drain your fee pool via implicit arbitrage.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#52
