### ISSUE TITLE
Disable negative voting for workers in GUI

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#798]
Need to disable negative voting feature for workers in GUI. Maybe clear historical negative votes automatically when account is being updated. See https://github.com/cryptonomex/graphene/issues/607

**Comment by svk31** [comment]
Looks like my assumption of negative votes always having an id of odd numbers was wrong, so I've removed that filter. If you run into issues with negative votes, use the approve/reject buttons to reset your position on that worker.
