### ISSUE TITLE
A solution of "bid and ask orders with same prices appear on the order book"

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#800]
For every order displayed on the order book, round down the `price`, and place a "+" sign after the price if there are some digits killed. If move mouse onto the "+" sign, show the real price in a tip box.

When clicking on an ask order on the order book, if there is a "+" sign after the price, while updating the "place bid order" area, automatically add 1 minimum unit to the price (aka round the price up).

When clicking on a bid order on the order book, no matter whether there is a "+" sign after the price, set the price in "place ask order" area to rounded down price of the bid order on the book.

With this approach it should be always possible to match the orders on the book when placing a new order.

At the end, there will still be orders with "same prices" on the book, but users can see the real and different prices by moving mouse onto the "+" signs.

Thoughts?

**Comment by abitmore** [comment]
With above solution, perhaps there will be always a fraction of the new order left on the market. Sometimes but not always, it's able to full fill the best orders on the book without leaving a fraction. Current GUI is probably trying to achieve this goal, and succeeded in most cases. So it's possible to optimize the above solution.

Perhaps also need to add "+" signs to the `amount` or `volume` columns, because only the `for_sale` amount is always accurate.

How to know whether there are digits killed in a `price`? Analysis here:

GUI knows details of every order on the book. For each order, there are a `for_sale` field and a "price" field described as a `base_amount` in combined with a `quote_amount`. To be simple, assume `for_sale` and `quote_amount` is in same asset. 
- If the order is displayed as an ask order, `ask_price = quote_amount / base_amount`. Let `r_ask_price = round_down(ask_price)`, then check whether `r_ask_price * base_amount` equals to `quote_amount`, if the result is `false`, there are digits killed.
- If the order is displayed as a bid order, `bid_price = base_amount / quote_amount`. Let `r_bid_price = round_down(bid_price)`, then check whether `r_bid_price * quote_amount` equals to `base_amount`, if the result is `false`, there are digits killed.

**Comment by svk31** [comment]
Should be fixed now after the market-update branch was merged.

The solution was (among many others) to round *up* for bid orders. See MarketClasses.js for more info:

https://github.com/cryptonomex/graphene-ui/blob/master/web/lib/common/MarketClasses.js#L113
