### ISSUE TITLE
get no trading data

### ISSUE THREAD

**Issue by Shentist** [cryptonomex/graphene-ui#802]
for predection market assets they did not show in the Trading section if i search for them

**Comment by svk31** [comment]
![image](https://cloud.githubusercontent.com/assets/6890015/14184997/3ee2505a-f778-11e5-9b24-0b517fbcdf7a.png)

They do for me. What were you searching for?

**Comment by svk31** [comment]
Closing for lack of info. The search functionality is still finicky so might simply be related to that.
