### ISSUE TITLE
Add this Favicon

### ISSUE THREAD

**Issue by jonnybitcoin** [cryptonomex/graphene-ui#805]
Add this favicon.  see below
for those who don't know, a favicon is the tiny symbol shown in your browser tabs for the website you are on.

I've taken the blue one that was used on bitshares.org and made a dark version for the exchange. 
this is important for differentiating between the 2 tabs. 

you will have to rename the file extention from .png to .ico

![favicon](https://cloud.githubusercontent.com/assets/15330829/14227639/2c8dd11c-f8fa-11e5-87c8-3a73733692f1.png)

**Comment by xeroc** [comment]
For me .. the BitShares wallet already has a favicon. The blue one

**Comment by svk31** [comment]
I agree it should be differentiated from the standard blue bitshares icon, but we probably need a new one for Openledger.
