### ISSUE TITLE
Report an issue

### ISSUE THREAD

**Issue by vsrole** [cryptonomex/graphene-ui#809]
When I open BitShare2-light 16.0330 ,   click   'Deposit/Withdraw'    -     'CCEDK',
page will get stuck

**Comment by dnotestein** [comment]
Is this still happening now?

**Comment by svk31** [comment]
![image](https://cloud.githubusercontent.com/assets/6890015/14291751/4f2cd840-fb65-11e5-8aef-fcf2b99af466.png)

**Comment by svk31** [comment]
That commit should fix it.
