### ISSUE TITLE
Stealth: Newly created account does not show public key

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene-ui#811]
Created a new account and wallet, then created a new private account. The public key does not show, saying the wallet needs to be unlocked, but it's already unlocked. Clicking on the padlock icon does nothing.

![image](https://cloud.githubusercontent.com/assets/6890015/14342679/bb717b82-fc9b-11e5-9cbf-e3c71caa4ea5.png)

**Comment by svk31** [comment]
Additional comment: Navigating around does not help, I had to refresh the page and after unlocking the key then showed.

**Comment by jcalfee** [comment]
I improved the locking event and pushed that code last weekend.  It did fix an issue as you're describing here.

866a32063b442f36e66ce48bf2bd38ee4781cfa4
