### ISSUE TITLE
Stealth: exception on transfer when changing "from" account

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene-ui#812]
This exception freezes the GUI.
1. Enter an account in from that you control
2. Change the from account to be an account you don't control
3. Enter the account from step 1 again

![image](https://cloud.githubusercontent.com/assets/6890015/14342892/9cbc4cec-fc9d-11e5-884b-9a47b9c0df20.png)

**Comment by jcalfee** [comment]
The transfer screen at http://stealth.cnx.rocks/#/transfer does not lock up.  I see the error.. The minimized code is not showing this (on my local computer):

```
Uncaught Invariant Violation: findComponentRoot(..., .0.0.0.2.0.0.0.3.0.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
invariant   @   invariant.js:39
ReactMount.findComponentRoot    @   ReactMount.js:764
ReactMount.findReactNodeByID    @   ReactMount.js:679
getNode @   ReactMount.js:162
SimpleEventPlugin.didPutListener    @   SimpleEventPlugin.js:571
EventPluginHub.putListener  @   EventPluginHub.js:153
wrapper @   ReactPerf.js:66
putListener @   ReactDOMComponent.js:234
assign.notifyAll    @   CallbackQueue.js:65
ON_DOM_READY_QUEUEING.close @   ReactReconcileTransaction.js:81
Mixin.closeAll  @   Transaction.js:202
Mixin.perform   @   Transaction.js:149
Mixin.perform   @   Transaction.js:136
assign.perform  @   ReactUpdates.js:86
flushBatchedUpdates @   ReactUpdates.js:147
wrapper @   ReactPerf.js:66
Mixin.closeAll  @   Transaction.js:202
Mixin.perform   @   Transaction.js:149
ReactDefaultBatchingStrategy.batchedUpdates @   ReactDefaultBatchingStrategy.js:62
batchedUpdates  @   ReactUpdates.js:94
ReactEventListener.dispatchEvent    @   ReactEventListener.js:204
```

It is not the Recent Transactions.. It appears on the 1st char (backspace) going from a public account (in the to field) to account not found.  Do you see in any eslint errors about html elements matching?  Eslint in this project is not working for me..

Do you still have the locking up issue?  Maybe the node was slow and this issue it not related and non-critical.

**Comment by svk31** [comment]
Still happens for me, exactly the same steps with a newly created wallet. Can't really debug myself without setting up the stealth branch, and that didn't work last time I tried.

![image](https://cloud.githubusercontent.com/assets/6890015/14589177/f70d6c3a-04db-11e6-9a36-780ace3b4518.png)

**Comment by jcalfee** [comment]
fyi http://stackoverflow.com/questions/36180855/warning-js45-warning-flattenchildren-encountered-two-children-with-the-s

**Comment by jcalfee** [comment]
I retest with a newly created wallet..

**Comment by svk31** [comment]
Closing since stealth was put on hold indefinitely.
