### ISSUE TITLE
Private key viewer may be showing wrong public key....

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#813]
To reproduce, goto an account permissions and click on a public key.  A dialog comes up ("Private key viewer").  Then click on (show) and copy the WIF private key into this browser console command:

``` js
PrivateKey.fromSeed("5J...").toPublicKey().toPublicKeyString()
```

Does the output match the PUBLIC KEY in the dialog?  I checked a few accounts and none of them matched.  This is probably a display issue.

```
Private key viewer

PUBLIC KEY
BTS4ydWKd...

PRIVATE KEY (WIF - WALLET IMPORT FORMAT)
(show)

BRAINKEY POSITION
Non-deterministic

IMPORTED FROM ACCOUNT
...
```

**Comment by nmywn** [comment]
Same here.

**Comment by xeroc** [comment]
You need to use `PrivateKey.fromWif('<wif>')` if you import a wif key.
`fromSeed` (AFAIK) is used to get a key from a brainwallet

**Comment by jcalfee** [comment]
Your right, not an issue...
