### ISSUE TITLE
Possible settings initialization logic error in SettingsStore.js

### ISSUE THREAD

**Issue by rulatir** [cryptonomex/graphene-ui#822]
I am porting to React Native and I get settings as undefined form SettingsStore.

It appears that in dl/src/SettingsStore.js, the `settings` map doesn't get initialized with the `defaultSettings` map **if** the `settings_v3` key is not already present in the persistent storage. The only two places where `settings` are initialized form `defaultSettings` as of b2f6e4164207aee8af322f6fc7fcdf7ce73c8a5f are on line 146 which is only executed under the `ss.get("settings_v3")` condition, and in onClearSettings() which isn't exactly what I want to do on every startup of the app.

I suspect this is a bug.

**Edit**: I know that there's no localStorage in React Native; I modified dl/src/common/localStorage.js to provide a working shim (over realm).

**Comment by svk31** [comment]
I'll update localStorage.js to use a default value for gets so it won't fail.
