### ISSUE TITLE
Don't feed empty object to Immutable.List() and Immutable.Set()

### ISSUE THREAD

**Issue by rulatir** [cryptonomex/graphene-ui#826]
Now that `ss.get()` returns `{}` when key is missing and no other default is provided, we need to provide e.g. `null` or `[]` as the default when we do things like:

```
this.preferredBases = Immutable.List(ss.get("preferredBases"));
```

Should become:

```
this.preferredBases = Immutable.List(ss.get("preferredBases", null));
```

Otherwise the immutables throw.

**Comment by svk31** [comment]
This is why I used arrays as defaults whenever an Immutable.List was defined though.

```
this.hiddenAssets = Immutable.List(ss.get("hiddenAssets", []));
this.preferredBases = Immutable.List(ss.get("preferredBases", [CORE_ASSET, "BTC", "USD", "CNY", "OPEN.BTC"]));
```

**Comment by rulatir** [comment]
Ah sorry! I am actually working with graphene-ui-testnet code and this might have been their change that dropped the default `[]`, I'll look again.

**Edit**: I missed your commits from today.
