### ISSUE TITLE
Apply svk's color scheme to FormatAsset

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#84]
FormatAsset is also used when user's import there balance in several columns: vested, unvested, claimed, unclaimed.  This will help readability.

**Comment by svk31** [comment]
You can now do `<FormattedAsset color="success" etc... />` for example, I've reused the standard success, alert, info, warning colors and added a "fee" color.

@cassiopaia It might be interesting to have some different color presets for stuff like balances, prices, received/sent, what do you think?

**Comment by c055** [comment]
sure .. but guess better talk to @valzav before, as he has choosen the actual color palette! Anyway, let me know if i could help on this …:)

**Comment by jcalfee** [comment]
What about coloring the decimals a different color from the who number?  Like what we do in the exchange?  Sorry, my ticket was vague...
