### ISSUE TITLE
BitShares 2.0.160504 GUI light client freezes after clicking settings icon

### ISSUE THREAD

**Issue by arhag** [cryptonomex/graphene-ui#842]
I can reliably trigger this bug in v2.0.160504 of the GUI light client by starting the client (or even reloading it) and then pressing the Settings icon.

When I do this and look at DevTools console I get a:

```
Uncaught TypeError: Cannot read property 'map' of undefined
```

Clicking anything else after this will not respond with any view changes expected and I get other TypeError exceptions in the console each time I click such as:

```
Uncaught TypeError: Cannot read property 'componentWillUnmount' of null
```

**Comment by svk31** [comment]
On which OS? I checked on OSX and it works fine for me there.

**Comment by arhag** [comment]
This was on Windows 10.
