### ISSUE TITLE
Privacy enhancements to wallet network behavior

### ISSUE THREAD

**Issue by xmr-karnal** [cryptonomex/graphene-ui#854]
Based on a discussion ~1week ago on bitsharestalk.org, I'd like to propose the following:
- Allow selecting a wss:// endpoint per wallet, to help prevent the server from correlating requested balances (that map to account name) with the users' ip address.
- When switching between wallets, tear down the connection to the server; Add an option to re-establish the connection after about $selectable seconds.
- Implement SOCKS5 proxying support, possible HTTP as well, so that the client can further gain in privacy by hiding the originating ip address from the server.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#57
