### ISSUE TITLE
Trollbox:  Welcome message is also limited to 140 characters.

### ISSUE THREAD

**Issue by nmywn** [cryptonomex/graphene-ui#855]
So it's look like this:
"Welcome to Bitshares: This is a peer to peer chatroom, with no moderation and no guaranteed unique usernames. It can be disabled in the settings. Message frequenc"

I think user do not need know about limits (easier fix).

**Comment by svk31** [comment]
Good catch, I have a fix ready.

**Comment by nmywn** [comment]
Now i have something like this:
![openledger 2016-07-03 08-48-56](https://cloud.githubusercontent.com/assets/18205812/16544166/35b6ceb2-40fb-11e6-82cd-90a781541087.png).
Im at https://bitshares.openledger.info/#/dashboard and refreshing page, because many times chat history doesn't loading. Found that best way to retrieve history is refresh page there.

Most time welcome messages are doubled, but also tripled and so on. My record is 5 for now.
