### ISSUE TITLE
Not possible to type brainkey on MacOS

### ISSUE THREAD

**Issue by xmr-karnal** [cryptonomex/graphene-ui#856]
Just tried the Mac version of the latest wallet (2.0.160524b), and restoring from brainkey ..

Typing in the brainkey box does nothing.

Tried to set a password first, tried to create a new wallet and then restore to a different (!default) wallet with the brainkey, same issue.

The Linux version is fine.

**Comment by svk31** [comment]
Unable to reproduce, might have been an earlier bug. I've added a specific "restore from brainkey" option as well now since it wasn't clear how to restore using a brainkey.
