### ISSUE TITLE
Problem loading latest web wallet on one of our computers

### ISSUE THREAD

**Issue by dnotestein** [cryptonomex/graphene-ui#863]
One of our machines gets stuck loading https://bitshares.openledger.info/, all you see is the three marching dots.
Everything worked until the July 3ish update.

On the websocket connection, we see a few calls to get APIs and get_chain_id succeed, then it gets stuck
in a loop calling get_objects(2.1.0).  We see the response for get_objects and it looks correct, but a second later it makes another get_objects(2.1.0) call as if it never processed the reply.

Nothing interesting on the console, other than that we see "not yet synced, retrying in 1s" instead of "synced and subscribed".

Running latest Firefox and Chrome on Windows.  It doesn't have anything to do with cookies, local databases, etc.   We have cleared those and tried accessing different copies of the wallet that we had never visited before.  So bitshares.openledger.info, bitshares.org/wallet, openledger.hk, freedomledger.com all fail.  x.makerdao.com still works, since it's an old version.

**Comment by svk31** [comment]
I'm guessing this was due to an unsynchronized clock. The latest release included a fix to this kind of issue with a warning telling you to synchronize your clock.
