### ISSUE TITLE
Please add detail of a multi signature transaction

### ISSUE THREAD

**Issue by imYao** [cryptonomex/graphene-ui#867]
Why GUI wallet didn't offer a view of multi signature transactions? Very inhuman!
Each one of multi-signer need to know the detail of the multi-sig transaction to prevent cheating.

Such as:
- Transfer?
- Trade Oder? 
- Modify the weights and thresholds?

Thanks for your job.

**Comment by xeroc** [comment]
Multisig is not per-transaction, but per account:
http://docs.bitshares.eu/bitshares/user/account-permissions.html

Once you proposed a transaction you will see the proposal and it's details in the overview

**Comment by imYao** [comment]
Where I can see the overview when someone initiate a multi signature transaction? He may cheating me if I don't know what he want to do.
![https://s19.postimg.org/kuyqx98gj/details_of_multisig_transaction.png](https://s19.postimg.org/kuyqx98gj/details_of_multisig_transaction.png)
![https://s19.postimg.org/3vpshzx8z/details_of_multisig_transaction_02.png](https://s19.postimg.org/3vpshzx8z/details_of_multisig_transaction_02.png)

**Comment by svk31** [comment]
This is a valid concern at least for account update operations because the actual details are hidden. The reason for that is simply that there's too much data to display concisely in the overview. I'll see if I can add a popup that shows the full operation details.

**Comment by imYao** [comment]
@svk31 Thanks so much!

**Comment by xeroc** [comment]
@svk31 could you please also show the proposal ID somewhere in the overview already?
Makes searching them on cryptofresh.com alot easier! Thanks

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#62
