### ISSUE TITLE
Please add SHA1 when GUI wallet release everytime

### ISSUE THREAD

**Issue by imYao** [cryptonomex/graphene-ui#868]
Please add SHA1 when GUI wallet release to prevent cheating.
Thanks for your job.

**Comment by svk31** [comment]
I've wanted to do this actually but I've yet to figure out _how_! Is there a guide somewhere for how to do this?

**Comment by imYao** [comment]
I generally use HashTab to verify SHA1:
![https://s19.postimg.org/nlco86uj7/Hash_Tab.png](https://s19.postimg.org/nlco86uj7/Hash_Tab.png)

Just post the SHA1 of the wallet file in github when you release. You are official release!

**Comment by svk31** [comment]
Ok I looked into this again and it seems it's even easier than I thought, not sure why I never found this before when searching for it. Missing the "digest" keyword perhaps. Anyway, I can do this with openssl as such:

`openssl dgst -sha256 filename.exe`

Is SHA1 sufficient? Or should I use another algorithm?

**Comment by imYao** [comment]
SHA1 **and** another will be better.

**Comment by svk31** [comment]
Ok I'll do that then.

**Comment by svk31** [comment]
9c27d767083b2f32645fed56372ebcb9cbea40d0

**Comment by svk31** [comment]
Closing, hashes will be included for the next release.
