### ISSUE TITLE
User experience Optimization: API & Language selection should displayed in the home page and start page

### ISSUE THREAD

**Issue by imYao** [cryptonomex/graphene-ui#869]
User experience Optimization: API & Language selection should **displayed in the home page and start page.**
Thanks for your job.

**Comment by xeroc** [comment]
I don't understand this issue ..
you looking for something like this?
http://docs.bitshares.eu/api/

**Comment by imYao** [comment]
@xeroc sorry, I didn't explain it clearly. I mean, for **newbies**:

If you are an American, don't understand Chinese, what do you want to do when you open a Chinese website? I will change the Default Language first.

API servers are in different countries, the default API server of BitShares 2.0 GUI is OpenLedger, some people may be difficult to access OpenLedger, he might have been unable to enter the wallet home page, all the time. He need to change the Defaule API server first.

I hope you can understand this now.

**Comment by svk31** [comment]
This is something we talked about for the revamp of account creation but got lost somewhere, it's definitely something we should do.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#63
