### ISSUE TITLE
The unit of fee is wrong when create a new bitshares account with 0 bts in balance.

### ISSUE THREAD

**Issue by kimziv** [cryptonomex/graphene-ui#873]
![42b056fb15cc34c0986d0d95ed36750a](https://cloud.githubusercontent.com/assets/301489/18045396/3de8ae20-6e05-11e6-895c-3ae78bbc8e08.jpg)

The unit of fee is wrong when create a new bitshares account whith 0 bts in balance.
1. create a new bitshares account A.
2. dposit some BTC to  account A.
3.  sent open.BTC to another account B. 

you will see the unit fee is open.BTC:2.64174 open.BTC.

please fix the UI  error.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#65
