### ISSUE TITLE
MARKET TRADE / MY TRADES

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#874]
![screen shot 2016-08-31 at 6 07 45 pm](https://cloud.githubusercontent.com/assets/1254810/18148131/e73132ee-6fa5-11e6-8dc1-8a7e08325a80.png)

This is a cosmetic bug. To reproduce, you must be on an asset that you have already traded in the past in the Exchange tab.
- choose the MARKET TRADES tab
- Scroll down a bit
- Switch to MY TRADES tab
- None of your transactions will appear until you scroll up.

**Comment by steempower** [comment]
This also occurs on all list boxes including buy / sell orderbook's

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#66
