### ISSUE TITLE
Firefox 48.0.2 Windows 10 x64 Pulling random GUI

### ISSUE THREAD

**Issue by brekyrself** [cryptonomex/graphene-ui#876]
Firefox 48.0.2 on windows 10 x64

When I load openledger it seems to grab a random version.  For example today it's loading 2.0.160703.  Last few days it was pulling August builds from the 13th and 28th.  Clearing cache does not help, might be on the openledger side?

This may also be related to the chat showing under 10 users online while it usually shows 75-200 people online.

**Comment by svk31** [comment]
This is simply due to the Openledger team pushing different versions. The chat server had issues that have since been fixed.
