### ISSUE TITLE
Bug in the Markets tab (OS x client  v2.0.160829)

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#877]
- Market for BitUSD/BTS
- Issued Buy order for 93 BitUSD at 192.66528 BTS/USD (see screenshot, My Open Orders)

The buy order precisely matches the sell offer but the trade is not executing. Possibly a rounding error of some sort:

![screen shot 2016-09-18 at 8 11 16 pm](https://cloud.githubusercontent.com/assets/1254810/18620280/d6d611f4-7ddc-11e6-9d1c-e8c6b46200d9.png)

**Comment by svk31** [comment]
Should be fixed now after the merging of the market-updates branch.
