### ISSUE TITLE
Cannot create account with private testnet

### ISSUE THREAD

**Issue by ehajredini** [cryptonomex/graphene-ui#878]
I have setup a privat testnet, and ws is up and running, but cannot create the account and getting an error included by pic. I also cannot find the config file in chain folder, like it is explained here: http://docs.bitshares.org/testnet/6-webwallet.html
![create-account](https://cloud.githubusercontent.com/assets/7700571/18634482/5011dc66-7e81-11e6-843a-d4bb43f281fb.png)

**Comment by svk31** [comment]
Most likely you need to change your faucet address in the Settings to `http://testnet.bitshares.eu`

**Comment by xeroc** [comment]
He needs to modify graphenejs-ws and add his own private network chainid:
https://github.com/svk31/graphenejs-ws/blob/master/lib/src/ChainConfig.js
