### ISSUE TITLE
Balances Asset display idea

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#879]
This might be pretty complicated, but it would really be great to see the 
- [ ] market value per share in the chosen currency on the balances screen
- [ ] green/red based upon whether it's up or down in the past 24 hours
- [ ] Numbers aligned to the decimal regardless of the length of the symbol

![screen shot 2016-09-19 at 11 33 08 am](https://cloud.githubusercontent.com/assets/1254810/18638227/58b45ebc-7e5d-11e6-8544-bbfb093b8b87.png)

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#67
