### ISSUE TITLE
Multi-sign problem

### ISSUE THREAD

**Issue by name55** [cryptonomex/graphene-ui#881]
![image](https://cloud.githubusercontent.com/assets/17917840/18806736/29f1888e-8268-11e6-974a-661cb5c674ba.png)
1.bebtc-test is my  account to do some tests,active key ower list is 8 person,it should be only the man in the   list can approve a transaction,but we fond anyone can approve a transaction,it not safe.
2.bebtc-test account has no QBITS,but can approve a QBITS transaction.

**Comment by xeroc** [comment]
Anyone can add an approval. It will just be ignored if it is not in the set of required approvals. The users that approve dont nees to have any funds except for the fee to pay for the approval ..
