### ISSUE TITLE
UX Terrorism: We stop user-growth by making them buy vowels

### ISSUE THREAD

**Issue by faddat** [cryptonomex/graphene-ui#884]
So therefore, I shouldn't need to buy a vowel.  

Especially considering that the cli wallet lets me ask Yolanda for as many vowels as I'd like.

**Comment by svk31** [comment]
Nothing to do with the UI, the pricing is set on the blockchain level.

**Comment by faddat** [comment]
Sorry what?  

I'm really, really confused then.  Maybe let's reverse the tape here-- WHY DO WE COMMIT UX TERRORISM BY MAKING USERS BUY VOWELS WHEN THEY ARE MOST LIKELY TO ADOPT OR REJECT THE PLATFORM?

**Comment by svk31** [comment]
Please stop yelling.

![image](https://cloud.githubusercontent.com/assets/6890015/21658445/ebd60200-d2c6-11e6-9500-362fd8434bcb.png)

If you think the fee is too high, take it up with the committee members, it doesn't belong here.

**Comment by faddat** [comment]
Alright it's cool man I'm going to yell outside the graphene-sphere now.  I tried.
