### ISSUE TITLE
Make BTC the default deposit/withdrawal type on OpenLedger gateway

### ISSUE THREAD

**Issue by dnotestein** [cryptonomex/graphene-ui#886]
Currently the default deposit type is AGRS, but AGRS addresses are the same format as BTC addresses, so it's a common error for users to accidentally send BTC to an AGRS deposit address. The best solution is probably to make BTC the initial default for depositing coins.

**Comment by abitmore** [comment]
Better fork the project and make new modifications there.

//Edit: operators should run their own customized UI (perhaps this repo is dedicated to OL?); 3rd party entries in the "official" client should be maintained by themselves and changes should be requested by them via pull requests.

**Comment by dnotestein** [comment]
I've assigned this issue to Adam. Adam, Matta can show you where the code for this page is, he's worked on this code in the past.

**Comment by svk31** [comment]
Pretty sure this is fixed now, closing.
