### ISSUE TITLE
Enhance BlockTrades bridge to allow conversion between BitShares asset types

### ISSUE THREAD

**Issue by dnotestein** [cryptonomex/graphene-ui#888]
Currently the BlockTrades bridge only "Deposits" of coins from other blockchains in exchange for BitShares asset types, or "Withdrawal" of coins from other blockchains in exchange for BitShares asset types.

However, the BlockTrades API also supports conversion between different types of BitShares assets. For example, the API allows for exchange between BTS and bitUSD, but the bridge does allow this conversion. 

We need to add a third conversion besides Deposit and Withdrawal: "Internal Conversion"
The input list will show a list of bitshares assets we accept as inputs, and the output list will show a list of bitshares assets that we can output based on those inputs.

I'm assigning Matta and Wojtek to this task.

**Comment by svk31** [comment]
Closing since this has already been added.
