### ISSUE TITLE
Show all ask/bid button in the DEX is not displayed for orderbook.length < 13, but only top 10 orders are shown

### ISSUE THREAD

**Issue by steempower** [cryptonomex/graphene-ui#896]
'show all asks/bids' button on the bottom of the buy/sell order book is only displayed if there is greater than 13 orders on the orderbook, but only the top 10 orders are shown in the orderbook; resulting in orders 11, 12 & 13? being hidden and no button to show all orders is displayed

**Comment by svk31** [comment]
Thanks, I actually knew about this one and fixed it in the Openledger repo, but looks like I missed it here. Will be fixed when I merge the market-update branch.
