### ISSUE TITLE
dl and web 'npm install' build environment issues.

### ISSUE THREAD

**Issue by grctest** [cryptonomex/graphene-ui#898]
dl:

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
> npm WARN graphene-dl@0.0.1 license should be a valid SPDX license expression

web:

> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN prefer global coffee-script@1.12.2 should be installed with -g
> npm WARN prefer global cover@0.2.9 should be installed with -g
> npm WARN prefer global node-gyp@3.5.0 should be installed with -g
> 
> > contextify@0.1.15 install /home/bitshares/bitshares-2-ui/web/node_modules/contextify
> > node-gyp rebuild
> 
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
> gyp ERR! build error
> gyp ERR! stack Error: not found: make
> gyp ERR! stack     at F (/home/bitshares/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/which/which.js:63:19)
> gyp ERR! stack     at E (/home/bitshares/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/which/which.js:72:29)
> gyp ERR! stack     at /home/bitshares/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/which/which.js:81:16
> gyp ERR! stack     at /home/bitshares/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
> gyp ERR! stack     at /home/bitshares/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
> gyp ERR! System Linux 4.4.0-31-generic
> gyp ERR! command "/home/bitshares/.nvm/versions/node/v5.12.0/bin/node" "/home/bitshares/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/bitshares/bitshares-2-ui/web/node_modules/contextify
> gyp ERR! node -v v5.12.0
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> 
> 
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
> npm WARN Graphene-UI@1.1.0 license should be a valid SPDX license expression
> npm ERR! Linux 4.4.0-31-generic
> npm ERR! argv "/home/bitshares/.nvm/versions/node/v5.12.0/bin/node" "/home/bitshares/.nvm/versions/node/v5.12.0/bin/npm" "install"
> npm ERR! node v5.12.0
> npm ERR! npm  v3.8.6
> npm ERR! code ELIFECYCLE
> 
> npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the contextify package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs contextify
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls contextify
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/bitshares/bitshares-2-ui/web/npm-debug.log

I experienced the above errors with the bitshares-2-ui and graphene-ui. I experienced a python build error too due to not having installed it (would be worth adding to dependencies in the readme).

How can I proceed past the above errors?

edit: Installed make & g++.

Edit: After installing both make and g++ the following issues remained:

> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN prefer global coffee-script@1.12.2 should be installed with -g
> npm WARN prefer global cover@0.2.9 should be installed with -g
> npm WARN prefer global node-gyp@3.5.0 should be installed with -g
> 
> > contextify@0.1.15 install /home/bitshares/bitshares-2-ui/web/node_modules/contextify
> > node-gyp rebuild
> 
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
> npm WARN Graphene-UI@1.1.0 license should be a valid SPDX license expression

No 'ERROR' messaged remained, I was able to proceed past the npm install at this point.

**Comment by svk31** [comment]
You need to install node v6. There's an update coming soon to package.json that should remove most of the warnings.

**Comment by svk31** [comment]
Update to package.json is live, closing.
