### ISSUE TITLE
overflow-y not working

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene-ui#90]
Several components are having overflow issues in the y direction, normally grid-content should make things overflow but it isn't working. Examples are Dashboard.jsx and Block.jsx

@cassiopaia Can you have a look please? If you link several accounts you should be able to reproduce the issue in Dashboard.jsx

**Comment by c055** [comment]
ok i'll take a look !

**Comment by valzav** [comment]
@svk31 - I don't see any overflow issue on Dashboard. Could you post a screenshot here?

**Comment by jcalfee** [comment]
He sent me one earlier .. it is in the block explorer
![pasted image at 2015_07_27 08_11 pm](https://cloud.githubusercontent.com/assets/204121/8919730/7a65d8a4-3487-11e5-8f2c-5e4784a381cf.png)

**Comment by svk31** [comment]
Here's one from the Dashboard:

![image](https://cloud.githubusercontent.com/assets/6890015/8924791/a8d44e08-3501-11e5-91a3-ca7bb43095bd.png)

You need to have quite a lot of accounts linked, I got all of these from importing the testnet private keys.

**Comment by valzav** [comment]
This was caused by this rule:
.grid-block {
  overflow: visible;
}

I removed it. Now if you see unnecessary scrollbars appear somewhere, please apply no-overflow class to this particular element.

**Comment by svk31** [comment]
Resolved so closing, to keep in mind if we notice weird overflow behaviour
