### ISSUE TITLE
WebSocket errors and recovery

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#91]
`WebSocket is already in CLOSING or CLOSED state.`
Re-create by stopping and starting a local witness node then continue to use the wallet.  `WebSocket is already in CLOSING or CLOSED state.` will be logged in the console.

**Comment by jcalfee** [comment]
Here is a message that is already trapped, the user needs to be warned because the app just fails in strange ways with no explanation :

```
WebSocket connection to 'ws://localhost:8090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
WebSocketRpc.js:18 !!! WebSocket Error  ws://localhost:8090
```

**Comment by jcalfee** [comment]
Here is a re-connecting websocket package.  I suggest that this will be far better than customizing our code.   It has its own configuration and works by wrapping the web socket.  I wonder if we could perhaps plugin our notice system to the package and not have to change our core websocket classes.

https://github.com/joewalnes/reconnecting-websocket

**Comment by valzav** [comment]
I'll give reconnecting-websocket a try later today

**Comment by valzav** [comment]
reconnecting-websocket does its job but we need to re-login upon reconnect - I'm implementing this..
